#if CONFIG_IDF_TARGET_ESP32C3
#define DEFAULT_SDA_PIN 6
#define DEFAULT_SCL_PIN 7
#define DEFAULT_LED_PIN 5
#define DEFAULT_BTN_PIN 19
#elif CONFIG_IDF_TARGET_ESP32
#define DEFAULT_SDA_PIN 16
#define DEFAULT_SCL_PIN 17
#define DEFAULT_LED_PIN 23
#define DEFAULT_BTN_PIN 19
#endif