// SPDX-License-Identifier: LGPL-2.1-or-later

namespace {
const char html_prefix[] = R"--(
<!doctype html>
<html lang=en>

<head>
    <meta charset=utf-8>
    <title>EspLog</title>
</head>
)--";

constexpr char html_suffix[] = "</html>";

const char html_body[] = R"--(
    <body>
    <h1>EspLog</h1>
    <div class="container">
    <div class="column ">
        <div class="center button_cloumn" style="max-width: 33rem;">
            <svg class="rec_btn command_btn" viewBox="0 0 24 24" onclick="post_command('command=record')" x="0px"
                y="0px" width="24" height="24">
                <circle cx="12" cy="12" r="4" fill="#ff0000" />
            </svg>
            <svg class="stop_btn command_btn" viewBox="0 0 24 24" onclick="post_command('command=stop')" x="0px" y="0px"
                width="24" height="24">
                <path d="M 8 8 L 16 8 L 16 16 L 8 16 L 8 8" fill="#000000" />
            </svg>
            <svg class="calibrate_btn command_btn" viewBox="0 0 24 24" onclick="post_command('command=calibrate')"
                x="0px" y="0px" width="24" height="24">
                <circle cx="12" cy="12" r="4" stroke="#42ab05" stroke-width="1" fill="#00000000" />
            </svg>
        </div>
    </div>
    <div class="column">
        <div class="center status_column" style="max-width: 33rem;">
            <div id="network_activity"></div>
            <div id="status_table">
                Loading...
            </div>
        </div>
    </div>
    <div class="column">
        <div class="center download_column" style="max-width: 33rem;min-height:1rem;">
             <div id="files_table">
                Loading...
            </div>
        </div>
    </div>
    </div>
</body>)--";

const char html_stylesheet[] = R"--(
<style>
    .rec_btn {
        background-color: #ff99c4;
    }

    .stop_btn {
        background-color: #ffe499;
    }

    .calibrate_btn {
        background-color: #a7d6fc;
    }

    .command_btn {
        height: auto;
        float: left;
        width: 33.33%;
        padding: 0;
        margin: 0;
    }

    .command_btn:active {
        background-color: #505050;
    }

    .cmd_btns:after {
        content: "";
        display: table;
        clear: both;
    }
    .container {
        display: flex;
        flex-wrap: wrap;
    }

    .button_cloumn {
        background-color: aliceblue;
    }

    .center {
        margin-left: auto;
    margin-right: auto;
    }

    .status_column {
        background-color:bisque;
    }

    .download_column {
        background-color: cornsilk;
    }
    .column {
        flex-grow: 1;
        flex-basis: 33%;
        padding-left: .1rem;
        padding-right: .1rem;
    }

    @media screen and (max-width: 67rem) {
        .column {
            flex-basis: 100%;
        }
    }

    .status_table {
        font-size: 1.2rem;
        font-style: bold;
    }

    .status_table_name_cell {
        width: 18rem;
    }

    .status_value_table_cell {
        padding-left: 2rem;
    }

    .download_table {
        font-size: 2rem;
    }

    .download_table_name_cell {
        width: 8rem;
    }

    .delete_btn {
        border: none;
        padding: 0 0 0 0;
    }

    .delete_btn:active {
        background-color: #505050;
    }

    .download_table_mid_cell {
        padding-left: 1rem;
        padding-right: 1rem;
    }

    #network_activity {
        width: 100%;
        height: 0.5rem;
    }
</style>
)--";

const char settings_style[] = R"--(
    <style>
    .setting_name {
        font-weight: bold;
    }

    .apply_btn {
        background-color: lightgreen;
        font-weight: bold;
    }

    .apply_btn:active {
        background-color: gray;
    }

    .cell {
        padding-left: 0.5em;
        padding-right: 0.5em;
    }
    </style>
)--";

const char js_settings[] = R"--(
    <script type="text/javascript">
    function apply_setting(s) {
        let elem = document.getElementById(s);
        let btn_elem = document.getElementById(s + "__btn");
        btn_elem.style.color="red";
        let xhr = new XMLHttpRequest();
        xhr.open('POST', '/settings');
        xhr.onload = function() {
            btn_elem.style.color="black";
        };
        xhr.send(s + "=" + elem.value);
        xhr.timeout = 10000;
    }
    </script>
)--";

const char js_xhr_status_updater[] = R"--(
<script type="text/javascript">
    var ind_state = false;
    var indicate = function() {
        var elem = document.getElementById("network_activity");
        ind_state = !ind_state;
        if (ind_state) {
            elem.style.backgroundColor ="orange";
        } else {
            elem.style.backgroundColor ="black";
        }
    };
    var update = function(path, element, interval, timeout, indicate) {
        let controller = new AbortController();
        let restarted = false;
        function restart(t) {
            if (!restarted) {
                restarted = true;
                setTimeout(()=>{update(path, element, interval, timeout, indicate);}, t);
            }
        }
        let to = setTimeout(()=>{ controller.abort(); }, timeout);
        fetch(path, {signal: controller.signal}).then((resp)=>{
            resp.text().then((text)=>{ 
                clearTimeout(to); 
                document.getElementById(element).innerHTML = text; 
                indicate(); 
                restart(interval); 
            }, (error) => { clearTimeout(to); restart(1000); });
        }, (error) => { clearTimeout(to); restart(1000); });
    };
    function make_updater(path, element, interval, timeout, indicate) {
        
        var xhr = new XMLHttpRequest();
        var do_request = function() {
            xhr.open('GET', path);
            xhr.timeout = timeout;
            xhr.send();
        }
        xhr.onload = function() {
            setTimeout(do_request, interval);
            indicate();
            document.getElementById(element).innerHTML = xhr.responseText;
        };
        xhr.onerror = function() {
            setTimeout(do_request, 1000);
        };
        xhr.ontimeout = xhr.onerror;
        do_request();
    }
    var status_last_update = (new Date()).getTime();
    var files_last_update = (new Date()).getTime();
    update( '/status', 'status_table', 500, 1000, ()=>{
        indicate();
        status_last_update = (new Date()).getTime();});
    update( '/files', 'files_table', 1000, 1000,  ()=>{
        indicate();
        files_last_update = (new Date()).getTime();});

    setInterval(()=>{ 
        let activity_div = document.getElementById("network_activity");
        if ((new Date()).getTime() - status_last_update > 2000) {
            activity_div.style.backgroundColor = "red";
        }
        if ((new Date()).getTime() - files_last_update > 2000) {
            activity_div.style.backgroundColor = "red";
        }
    }, 1000);

    function post_command(command) {
        let xhr = new XMLHttpRequest();
        xhr.open('POST', '/');
        xhr.send(command);
        xhr.timeout = 10000;
    }
</script>)--";

const char html_update_uploader[] = R"--(
    <div>
        <p style="font-weight:bold; color:red; font-size:1.2em;">WARNING: make sure you select the correct firmware,
            there is NO verification and NO integrity checking!</p>
        <p style="font-weight:bold">Update firmware</p>
        <input id="file_input" type="file">
        <button id="upload_button" type="button" onclick="upload()">Upload</button>
        <div id="upload_log"></div>
    </div>
)--";

const char js_update_uploader[] = R"--(
    <script>
    function upload() {
        let fileInput = document.getElementById("file_input").files;
        let file = fileInput[0];
        let xhttp = new XMLHttpRequest();
        let log_elem = document.getElementById("upload_log");
        log_elem.innerHTML = "";
        let line = document.createElement("p");
        line.innerText = "Starting upload!";
        line.style.color = "green";
        log_elem.appendChild(line);
        
        xhttp.timeout = 40000;
        xhttp.onreadystatechange = function () {
            if (xhttp.readyState == 4) {
                if (xhttp.status == 200) {
                    let line = document.createElement("p");
                    line.innerText = "Upload done, update should start automatically. This will take some time. Please, wait for more than 30 seconds and then power-cycle the device";
                    line.style.color = "green";
                    log_elem.appendChild(line);
                } else {
                    let line = document.createElement("p");
                    line.innerText = "Update failed. Wait around 30 seconds, reboot the device and try again.";
                    line.style.color = "red";
                    log_elem.appendChild(line);
                }
            }
        };
        xhttp.open("POST", "/update", true);
        xhttp.send(file);
    }
</script>
)--";

const char js_wasm_decoder_0[] = R"--(<script type="text/javascript">
var wasm = [
"AGFzbQEAAAABehNgAX8Bf2ACf38Bf2ABfwBgAAF/YAJ/fwBgA39/fwBgBH9/f38AYAN/f38Bf2AA",
"AGAFf39/f38AYAZ/f39/f38AYAR/f39/AX9gBn98f39/fwF/YAV/f39/fwF/YAF/AXxgAn98AX9g",
"A39+fwF+YAJ8fwF8YAJ+fwF/AicBA2Vudh9lbXNjcmlwdGVuX25vdGlmeV9tZW1vcnlfZ3Jvd3Ro",
"AAIDgwGBAQgAAgICAgIAAAIICAMBDQACAgAAAAMDAwMFDgICAQABAgABAAEBAQ8BAAYAAQEBAgIC",
"AAcEBAAACwQCAQEAAgABBAEABAQBBQEBAQEDAwEDBwIBAQEBAAQGBQgHBgMQBQAAEQsFAAUSCQwE",
"AQAAAgIHBwUGBgYFCQkKCgAAAwIAAAQFAXABGxsFBQEBAYAgBggBfwFB0NsBCwetAQsGbWVtb3J5",
"AgAOYWxsb2NhdGVfaW5wdXQAEw9nZXRfb3V0cHV0X3NpemUAFg5nZXRfb3V0cHV0X3B0cgAYBmRl",
"Y29kZQAZGV9faW5kaXJlY3RfZnVuY3Rpb25fdGFibGUBAAtfaW5pdGlhbGl6ZQBbEF9fZXJybm9f",
"bG9jYXRpb24AXglzdGFja1NhdmUAfgxzdGFja1Jlc3RvcmUAfwpzdGFja0FsbG9jAIABCSABAEEB",
"CxoDChEBMzRfamsVFXAEBHJ7eXRwenh1cH1wfAqn0AGBAVYBAX9BrNUAEAIaQbjVABACGiMAQRBr",
"IgAkAEHI1QAgAEEIakEBEA4oAgBBAEEAQQAQDxogAEEQaiQAQdjVABAQGkG81wBBzNYANgIAQfTW",
"AEEqNgIACywBAX8jAEEQayIBJAAgAEIANwIAIAFBADYCDCAAQQhqEEAaIAFBEGokACAACwgAQazV",
"ABAFCwMAAQspAQF/IAAQBiAAKAIABEAgABAHIAAQCBogACgCACEBIAAQCRogARBvCwspACAAKAIA",
"GiAAKAIAIAAQCWoaIAAoAgAgABAUahogACgCACAAEAlqGgsLACAAIAAoAgAQNgsHACAAQQhqCw8A",
"IAAQCCgCACAAKAIAawsnABALQbjVACgCAARAEAxBuNUAEAgaQbjVACgCACEAEA0aIAAQbwsLNABB",
"uNUAKAIAGkG41QAoAgAQDUECdGoaQbjVACgCABAXQQJ0ahpBuNUAKAIAEA1BAnRqGgs6AQJ/QbjV",
"ACgCACEBQbzVACgCACEAA0AgACABRwRAQbjVABAIGiAAQQRrIQAMAQsLQbzVACABNgIACxYAQbjV",
"ABAIKAIAQbjVACgCAGtBAnULDgAgACABQRt0NgIAIAALIAAgACAENgIMIAAgAzYCCCAAIAI2AgQg",
"ACABNgIAIAALfQEBfyAAQQEQDiIAQQRqQQAQDhogAEEIakEAEA4aIABBDGpBABAOGiAAQRBqQQAQ",
"DiIBQQRqQQAQDhogAUEIakEAEA4aIABBFjoAHCAAQYACNgIgIABBJGpBfxAOGiAAQQA2AjAgAEEA",
"OgAsIABBADYCKCAAQTRqEAIaIAALCABB2NUAEBILCQAgAEE0ahAFC6sIAQh/IwBB0ABrIgUkAAJA",
"IABBrNUAEBQiAUsEQCMAQSBrIgckAAJAIAAgAWsiBkGs1QAQCCgCAEGw1QAoAgBrTQRAIwBBEGsi",
"ACQAIABBrNUANgIAIABBsNUAKAIAIgE2AgQgACABIAZqNgIIIAAiASgCBCEAIAEoAgghAgNAIAAg",
"AkYEQCABEFIgAUEQaiQABUGs1QAQCCAAEFggASAAQQFqIgA2AgQMAQsLDAELQazVABAIIQggB0EI",
"aiECAn9BrNUAEBQgBmohBCMAQRBrIgEkACABIAQ2AgwjAEEQayIDJABBrNUAEAgaIANBfzYCDCAD",
"Qf////8HNgIIIANBDGogA0EIahBBKAIAIQAgA0EQaiQAIAAgBE8EQEGs1QAQCSIDIABBAXZJBEAg",
"ASADQQF0NgIIIAFBCGogAUEMahBTKAIAIQALIAFBEGokACAADAELAAshAUGs1QAQFCEEQQAhACMA",
"QRBrIgMkACADQQA2AgwgAkEMaiAIEEIgAQRAIAIoAhAaIAEQbiEACyACIAA2AgAgAiAAIARqIgQ2",
"AgggAiAENgIEIAIQRCAAIAFqNgIAIANBEGokACMAQRBrIgEkACABIAIoAgg2AgAgAigCCCEAIAEg",
"AkEIajYCCCABIAAgBmo2AgQgASgCACEAA0AgASgCBCAARwRAIAIoAhAgASgCABBYIAEgASgCAEEB",
"aiIANgIADAELCyABKAIIIAEoAgA2AgAgAUEQaiQAQazVABAGQazVABAIQazVACgCAEGw1QAoAgAg",
"AkEEaiIAEFlBrNUAIAAQRUGw1QAgAkEIahBFQazVABAIIAIQRBBFIAIgAigCBDYCAEGs1QAQFBpB",
"rNUAKAIAGkGs1QAoAgBBrNUAEAlqGkGs1QAoAgBBrNUAEAlqGkGs1QAoAgAaIAIoAgQhAANAIAAg",
"AigCCEcEQCACKAIQGiACIAIoAghBAWs2AggMAQsLIAIoAgAEQCACKAIQGiACKAIAIQAgAhBEKAIA",
"IAIoAgBrGiAAEG8LCyAHQSBqJAAMAQsgACABSQRAQazVACgCACAAaiEAQazVABAUIQFBrNUAIAAQ",
"NkGs1QAgARA1CwtBnNYAQQA2AgBBmNYAQQA2AgBByNUAIAVBCGoiACAFQcgAakEBEA4oAgBBAEEA",
"QQAQDyIBKQIANwIAQdDVACABKQIINwIAQdjVACAAEBAiAkE0EFxBNGoiASIAKAIABEAgABAUIQMg",
"ABAHIAAgAxA1IAAQCBogACgCACEDIAAQCRogAxBvIAAQCEEANgIAIABCADcCAAsgAkE0aiIAEAga",
"IAEQCBogASAAKAIANgIAIAEgACgCBDYCBCAAEAgoAgAhAyABEAggAzYCACAAEAhBADYCACAAQgA3",
"AgAgAhASQazVACgCACEAIAVB0ABqJAAgAAsNACAAKAIEIAAoAgBrCwQAIAALBAAQFwsUAEG81QAo",
"AgBBuNUAKAIAa0ECdQsJAEG41QAoAgALqRcCE38BfCMAQeAAayIEJAAQFxoQDEG41QAoAgAaQbjV",
"ACgCABANQQJ0ahpBuNUAKAIAGkG41QAoAgAQF0ECdGoaIARBMGohDiAEQShqQQRyIQ8CQANAQZzW",
"ACgCAEGs1QAQFE8NARAXQYAISw0BIARByABqIQhBrNUAKAIAQZzWACgCAGohCUGs1QAQFEGc1gAo",
"AgBrIQFBACELIwBB4ABrIgIkACACIAktAAAiDDYCXAJAIAFBBU0EQCAIEB0MAQsgCS0AASIAQQV2",
"IQ0gAkHYAGogAEEfcRAeIQogAiAJQQJqNgJQIAIoAlAiACgAACEDIAIgAEEEajYCUCACIAM2AlQg",
"AkFAaxACIgchAEH41QAoAgAhAyMAQSBrIgUkAAJAAkAgABA3IANJBEAgABA4IANJDQEgABAIIQYg",
"ACAFQQhqIAMgABAfIAYQOSIAEDogABA7CyAFQSBqJAAMAQsACyABIAlqIRAgAUEATCERAkACQANA",
"IAcQH0H41QAoAgBJBEBBACEFIAJBADoAOiACQQA7ATgDQCAFQQNHBEAgEUUEQCAQIAIoAlBrQQRI",
"DQULIAJBOGogBWoCfyACKAJUQf//AXEhBkH/fiEDQYEBIQEDQCABIAEgA0EBakYNARogCiABIANq",
"QQJtIgAQICAGSgRAIAAhAQwBCyAKIAAiA0EBahAgIAZMDQALIAMLIgE6AAAgCiABECAhACAKIAFB",
"AWoQICAAayEDIAIoAlQiBkH//wFxIABrIAZBD3YgA2xqIgNB////A00EQCACKAJQIQADQCAALQAA",
"IQYgAEEBaiEAIAYgA0EIdHIiA0GAgIAESQ0ACyACIAA2AlALIAIgAzYCVCAFQQFqIQUgASALaiEL",
"DAELCyACIAItADo6AAYgAiACLwE4OwEEIAJBKGoiACACLAAEIAxBGHRBGHUiAXQQIiACLAAFIAF0",
"ECIgAiwABiABdBAiECtB6NUAIAAQPBpB7NUAIABBBGoQPBpB8NUAIABBCGoQPBpBASEAAkAgAi0A",
"OCIBIAFBGHRBH3UiAXMgAWtB/wFxQf8ARg0AIAItADkiASABQRh0QR91IgFzIAFrQf8BcUH/AEYN",
"ACACLQA6IgAgAEEYdEEfdSIAcyAAa0H/AXFB/wBGIQALIAANASMAQUBqIgAkACACQQhqQQEQDiID",
"QQA2AgwgA0IANwIEIABB6NUAQejVABAmNgIwIABB7NUAQezVABAmNgIoIAAgAEEwaiAAQShqECc2",
"AhAgAEHw1QBB8NUAECY2AiAgACAAQRBqIgEgAEEgahAnNgI4IABBEBAiNgIQAkAgAEE4aiABED0E",
"QCAAIAAoAjgQLDYCMCAAIABBMGoiBSAAQRBqIgFEAAAAAAAA4D8QKBAmIgYQPjYCECAAIAEgBRAv",
"NgIoIAMgAQJ/IwBBEGsiASQAIAEgBjYCCCABEE42AgAgASABQQhqECcQPiEFIAFBEGokACAFC0Ho",
"1QAgAEEoaiIBECZB7NUAIAEQJkHw1QAgARAmEA8iASkCADcCAAwBCyAAQYCAgCA2AjAgAEEIakQA",
"AAAAAADwPxAoIQVB6NUAIABBMGoiARAmIQZB7NUAIAEQJiESQfDVACABECYhASADIABBEGogBSgC",
"ACAGIBIgARAPIgEpAgA3AgALIAMgASkCCDcCCCAAQUBrJAAgAkEYaiIBQdjVACADEBogAkEoaiEF",
"IwBBEGsiAyQAIwBBMGsiACQAIAAgASABECY2AhggACABQQRqIgYgBhAmNgIQIAAgAEEYaiAAQRBq",
"ECc2AiAgACABQQhqIgYgBhAmNgIIIAAgAEEgaiAAQQhqECc2AiggACABQQxqIgYgBhAmNgIAIABB",
"KGogABAnECwhBiAAQTBqJAAgAyAGNgIIIANBADYCAAJAIANBCGogAxAjBEAgBUEAQQBBAEEAEA8a",
"DAELIAUgASADQQhqIgAQLyABQQRqIAAQLyABQQhqIAAQLyABQQxqIAAQLxAPGgsgA0EQaiQAQeDV",
"ACACKQMwNwIAQdjVACACKQMoNwIAAkAgBygCBCAHEAgoAgBHBEAjAEEQayIBJAAgASAHQQEQUSEA",
"IAcQCCAAKAIEQdjVABBIIAAgACgCBEEQajYCBCAAEFIgAUEQaiQADAELIwBBIGsiAyQAIAcQCCIG",
"IANBCGoCfyAHEB9BAWohBSMAQRBrIgAkACAAIAU2AgwgBSAHEDgiAU0EQCAHEDciBSABQQF2SQRA",
"IAAgBUEBdDYCCCAAQQhqIABBDGoQUygCACEBCyAAQRBqJAAgAQwBCwALIAcQHyAGEDkiACgCCEHY",
"1QAQSCAAIAAoAghBEGo2AgggByAAEDogABA7IANBIGokAAsMAQsLIAtBB3EgDUcEQCAIEB0MAgsg",
"AiACKAJQIAlrNgIoIAggAkEoahBUIgVBBGohACMAQRBrIgkkACAAQgA3AgAgCUEANgIMIAcQCBog",
"AEEIahBAGiAHEB8iAQRAIAAQOCABSQRAAAsgACAAEAggARBDIgM2AgAgACADNgIEIAAQCCADIAFB",
"BHRqNgIAIABBABBGIAcoAgAhAyAHKAIEIQsjAEEQayIKJAAgCiAAIAEQUSEBIAAQCCEAA0AgAyAL",
"RwRAIAAgASgCBCADEEggASABKAIEQRBqNgIEIANBEGohAwwBCwsgARBSIApBEGokAAsgCUEQaiQA",
"IAVBEGogAkHcAGoQVBoMAQsgCBAdCyAHECELIAJB4ABqJAACQEHE1QAtAAANACAIKAIAIgBFDQBB",
"ACEDQZzWAEGc1gAoAgAgAGoiAEEBajYCAEGs1QAoAgAhAUGc1gBBnNYAKAIAIgJBrNUAKAIAIABq",
"LQAAIgBBBmxqNgIAIAQgCCgCBBAiNgJAIAQgCCgCCBAiNgI4IABBAWshBSABIAJqIQsDQCAEQUBr",
"IARBOGoQI0EBcwRAIARBQGsoAgAhAiAEIANBN242AhggBCAFNgIIIwBBEGsiByQAIARBCGoiACgC",
"ACAEQRhqIgEoAgBIIQggB0EQaiQAIAAgASAIGygCACEGIAAgAigCACACQQRqECQgAkEIahAkIAJB",
"DGoQJBAPGiABIABByNUAEBogBEEoaiEKIwBBMGsiACQAIAAgAUEEaiIHIAcQJjYCGCAAIAFBCGoi",
"CCAIECY2AhAgACAAQRhqIABBEGoQJzYCICAAIAFBDGoiCSAJECY2AgggACAAQSBqIgwgAEEIahAn",
"NgIoAkAgAEEoaiAMRAAAAAAAAAAAECgQKQRAIAogBxAqIAgQKiAJECoQKwwBCyAAIAAoAigQLCIM",
"NgIgIABBEGpBAhAOIQ0gAAJ/IAEgAEEAEA4QLQRAIABBIGoQJCABECQQLgwBCyAMIAEoAgAQLgs2",
"AgggACANIABBCGoQJjYCGCAAIABBGGogAEEgahAvNgIQIAogByAAQRBqIgEQJiAIIAEQJiAJIAEQ",
"JhArCyAAQTBqJABByNUAIAIpAgA3AgBB0NUAIAIpAgg3AgAgA0EBaiEDQZjWAEGY1gAoAgAEfwJA",
"QbzVACgCAEG41QAQCCgCAEcEQEGY1gAQMAwBC0GY1gAQMQsgBAJ/IARBKGoQG0TNv5Szu9QvQaIi",
"E5lEAAAAAAAA4EFjBEAgE6oMAQtBgICAgHgLNgIYIARBGGoQHCAEAn8gDxAbRM2/lLO71C9BoiIT",
"mUQAAAAAAADgQWMEQCATqgwBC0GAgICAeAs2AhggBEEYahAcIAQCfyAOEBtEzb+Us7vUL0GiIhOZ",
"RAAAAAAAAOBBYwRAIBOqDAELQYCAgIB4CzYCGCAEQRhqIgAQHCAEIAsgBkEGbGoiAS4BADYCGCAA",
"EBwgBCABLgECNgIYIAAQHCAEIAEuAQQ2AhggABAcQZjWACgCAAVBAAtBAWo2AgAgBEFAayIAIAAo",
"AgBBEGo2AgAMAQUgBEHIAGoQMgwDCwALAAsLIARByABqEDILIARB4ABqJABBAAvgAwEJfyAAIAEQ",
"JSEBIwBB0AFrIgAkACAAIAEgAhAmNgKoASAAIAFBBGoiBCACQQRqIgUQJjYCoAEgACAAQagBaiAA",
"QaABahBLNgKwASAAIAFBCGoiAyACQQhqIgYQJjYCmAEgACAAQbABaiAAQZgBahBLNgK4ASAAIAFB",
"DGoiByACQQxqIggQJjYCkAEgAEG4AWogAEGQAWoQSyEJIAAgASAFECY2AnggACAEIAIQJjYCcCAA",
"IABB+ABqIABB8ABqECc2AoABIAAgAyAIECY2AmggACAAQYABaiAAQegAahAnNgKIASAAIAcgBhAm",
"NgJgIABBiAFqIABB4ABqEEshCiAAIAEgBhAmNgJIIAAgBCAIECY2AkAgACAAQcgAaiAAQUBrEEs2",
"AlAgACADIAIQJjYCOCAAIABB0ABqIABBOGoQJzYCWCAAIAcgBRAmNgIwIABB2ABqIABBMGoQJyEL",
"IAAgASAIECY2AhggACAEIAYQJjYCECAAIABBGGogAEEQahAnNgIgIAAgAyAFECY2AgggACAAQSBq",
"IABBCGoQSzYCKCAAIAcgAhAmNgIAIAEgAEHAAWogCSAKIAsgAEEoaiAAECcQDyIBKQIANwIAIAMg",
"ASkCCDcCACAAQdABaiQACxIAIAAoAgC3RAAAAAAAAEA+ogsfAEG81QAoAgBBuNUAEAgoAgBJBEAg",
"ABAwDwsgABAxCxYAIAAQQCIAQQRqEAIaIABBEGoQQBoLCwAgACABNgIAIAALEAAgACgCBCAAKAIA",
"a0EEdQspAQF/IAFBgX9OBH8gACgCAEECdEGgC2ooAgAgAUEBdGovAYACBUEACwtTAQJ/IAAQPyAA",
"KAIABEAgACgCACECIAAoAgQhAQNAIAEgAkcEQCAAEAgaIAFBEGshAQwBCwsgACACNgIEIAAQCBog",
"ACgCACEBIAAQNxogARBvCwskAQF/IwBBEGsiASQAIAFBCGogABAeKAIAIQAgAUEQaiQAIAALDQAg",
"ACgCACABKAIARgsMAEEAIAAoAgBrECILLAAgACABKAIANgIAIAAgASgCBDYCBCAAIAEoAgg2Aggg",
"ACABKAIMNgIMIAALUwIBfwF+IwBBEGsiAiQAIAIgACgCADYCCCACQQhqIgAgATQCACAANAIAfiID",
"QoCAgCB/QgKBIANCgICAwAB/fD4CACAAKAIAIQAgAkEQaiQAIAALLgEBfyMAQRBrIgIkACACIAAo",
"AgA2AgggAkEIaiABEDwoAgAhACACQRBqJAAgAAtTACAAAn8gAUQAAAAAAACgQaJEAAAAAAAA4D9E",
"AAAAAAAA4L8gAUQAAAAAAAAAAGYboCIBmUQAAAAAAADgQWMEQCABqgwBC0GAgICAeAs2AgAgAAsN",
"ACAAKAIAIAEoAgBMCy4BAX8jAEEQayIBJAAgASAAKAIANgIIIAFBCGpBAhBPKAIAIQAgAUEQaiQA",
"IAALFwAgACADNgIIIAAgAjYCBCAAIAE2AgAL3QECAX8EfiMAQSBrIgEkACABIAA2AhgCQCABQRhq",
"IAFBEGpBABAOEEkEQCABQRhqIAFBCGpBABAOECMEQCABKAIYIQAMAgsgATQCGCICQhuGIQMgAlAE",
"QEHpCUHDCEEXQasIEF0AC0IBIAJ5p0E/c0EbakF+ca2GIQIDQCACUARAIAQgAyAEVa18pxAiIQAM",
"AwUgBEIBh0IAIAIgAyACIAR8IgVTIgAbfCEEIANCACAFIAAbfSEDIAJCAochAgwBCwALAAtBygpB",
"wwhB0QNBpggQXQALIAFBIGokACAACw0AIAAoAgAgASgCAEgL9gEBAX8jAEEwayICJAAgAiABNgIg",
"IAIgADYCKAJAAkAgAkEgaiACQRhqQQAQDhAjBEAgAkEoaiACQRhqQQAQDhBVRQ0CIAJBKGogAkEY",
"akEAEA4QPSEBEE4hACABDQEgAiAANgIQIAJBEGoQJCEADAELIAIgACACKAIgEFYiADYCGCACQSBq",
"IAJBEGpBABAOEC1FDQAgAkEoaiACQRBqQQAQDhBJIQEQUCEAIAEEQCACIAA2AgggAkEYaiACQQhq",
"ECchAAwBCyACIAA2AgggAkEYaiACQQhqEEshAAsgAkEwaiQAIAAPC0HYCkHDCEGYBUHfCRBdAAtr",
"AgF/An4jAEEQayICJAAgAiAAKAIANgIIIAJBCGohACABKAIAIgFFBEBB5QlB6ghBqQFB1AkQXQAL",
"IAAgADQCAEIchiABrH8iA0ICfyIEIAMgBEIBhn18PgIAIAAoAgAhACACQRBqJAAgAAtZAQJ/IwBB",
"EGsiAiQAIAJBuNUANgIAIAJBvNUAKAIAIgE2AgQgAiABQQRqNgIIIAIhAUG41QAQCCABKAIEIAAQ",
"WiABIAEoAgRBBGo2AgQgARBSIAJBEGokAAuPBAEHfyMAQSBrIgYkAEG41QAQCCIHAn8gBkEIaiEB",
"An8QF0EBaiEFIwBBEGsiAiQAIAIgBTYCDCMAQRBrIgMkAEG41QAQCBogA0H/////AzYCDCADQf//",
"//8HNgIIIANBDGogA0EIahBBKAIAIQQgA0EQaiQAIAQgBU8EQBANIgMgBEEBdkkEQCACIANBAXQ2",
"AgggAkEIaiACQQxqEFMoAgAhBAsgAkEQaiQAIAQMAQsACyECEBchBUEAIQQjAEEQayIDJAAgA0EA",
"NgIMIAFBDGogBxBCIAIEQCABKAIQGiACQf////8DSwRAAAsgAkECdBBuIQQLIAEgBDYCACABIAQg",
"BUECdGoiBTYCCCABIAU2AgQgARBEIAQgAkECdGo2AgAgA0EQaiQAIAEoAggLIAAQWiABIAEoAghB",
"BGo2AggQC0G41QAQCEG41QAoAgBBvNUAKAIAIAFBBGoiABBZQbjVACAAEEVBvNUAIAFBCGoQRUG4",
"1QAQCCABEEQQRSABIAEoAgQ2AgAQFxpBuNUAKAIAGkG41QAoAgAQDUECdGoaQbjVACgCABANQQJ0",
"ahpBuNUAKAIAGiABKAIEIQADQCAAIAEoAghHBEAgASgCEBogASABKAIIQQRrNgIIDAELCyABKAIA",
"BEAgASgCEBogASgCACEAIAEQRCgCACABKAIAaxogABBvCyAGQSBqJAALCQAgAEEEahAhCwQAQQAL",
"BABBAAskACAAKAIAGiAAKAIAIAAQCWoaIAAoAgAaIAAoAgAgABAUahoLKwEBfyAAKAIEIQIDQCAB",
"IAJHBEAgABAIGiACQQFrIQIMAQsLIAAgATYCBAsSACAAEAgoAgAgACgCAGtBBHULQgEBfyMAQRBr",
"IgEkACAAEAgaIAFB/////wA2AgwgAUH/////BzYCCCABQQxqIAFBCGoQQSgCACEAIAFBEGokACAA",
"C2IBAn8jAEEQayIFJAAgBUEANgIMIABBDGogAxBCIAEEQCAAKAIQIAEQQyEECyAAIAQ2AgAgACAE",
"IAJBBHRqIgI2AgggACACNgIEIAAQRCAEIAFBBHRqNgIAIAVBEGokACAAC34BBH8gABA/IAAQCCEE",
"IAAoAgAhBSAAKAIEIQMgAUEEaiECA0AgAyAFRwRAIAQgAigCAEEQayADQRBrIgMQSCACIAIoAgBB",
"EGs2AgAMAQsLIAAgAhBFIABBBGogAUEIahBFIAAQCCABEEQQRSABIAEoAgQ2AgAgACAAEB8QRgtV",
"AQF/IAAoAgQhAQNAIAEgACgCCEcEQCAAKAIQGiAAIAAoAghBEGs2AggMAQsLIAAoAgAEQCAAKAIQ",
"GiAAKAIAIQEgABBEKAIAIAAoAgBrGiABEG8LCxQAIAAgACgCACABKAIAajYCACAACw0AIAAoAgAg",
"ASgCAEoL/QMBA38jAEHwAGsiASQAEE0hAyMAQRBrIgIkACACIAM2AgAgAiAANgIIIAIoAgBFBEBB",
"9AlBwwhBvgFBqQkQXQALIAIoAgggAigCAG8QIiEAIAJBEGokACABIAA2AmggARBONgJgIAEgAUHo",
"AGoiACABQeAAaiICEC82AmggACACQQAQDhAtBEAgAUHoAGogAUHgAGpBBBAOEDwaC0EBIQAgAUHo",
"AGogAUHgAGpBAhAOED0EQCABQegAaiABQeAAakECEA4QShpBfyEACyABQegAaiABQeAAakEBEA4Q",
"PQRAIAEgAUHgAGpBAhAOIAFB6ABqEEs2AmgLIAEgAUHoAGoiAyADECY2AmAjAEEQayICJAAgAiAD",
"KAIANgIIIAJBCGogABBPKAIAIQAgAkEQaiQAIAEgADYCUCABEFA2AkAgARBNNgIgIAEgAUEgakEF",
"EEw2AiggARBQNgIIIAEgAUEIakEDEEw2AhAgASABQeAAaiIAIAFBEGoQJjYCGCABIAFBKGogAUEY",
"ahBLNgIwIAEgACABQTBqECY2AjggASABQUBrIAFBOGoQSzYCSCABIAFB0ABqIAFByABqECY2Algj",
"AEEQayIAJAAgACABKAJYNgIIIABBCGoiAiACKAIAQQJtNgIAIAIoAgAhAiAAQRBqJAAgAUHwAGok",
"ACACCzIAIAAoAgAaIAAoAgAgABA3QQR0ahogACgCACAAEB9BBHRqGiAAKAIAIAAQN0EEdGoaCwsA",
"IABBADYCACAACyMBAn8jAEEQayICJAAgASAAEEchAyACQRBqJAAgASAAIAMbCw4AIAAQQEEEaiAB",
"EB4aCxYAIAFB/////wBLBEAACyABQQR0EG4LBwAgAEEMagscAQF/IAAoAgAhAiAAIAEoAgA2AgAg",
"ASACNgIACyoAIAAoAgAaIAAoAgAgABA3QQR0ahogACgCACAAEDdBBHRqGiAAKAIAGgsNACAAKAIA",
"IAEoAgBJCwkAIAEgAhAlGgsNACAAKAIAIAEoAgBOCxQAIAAgACgCACABKAIAazYCACAACy4BAX8j",
"AEEQayICJAAgAiAAKAIANgIIIAJBCGogARBKKAIAIQAgAkEQaiQAIAALPAEBfyMAQRBrIgIkACAC",
"IAAoAgA2AgggAkEIaiIAIAAoAgAgAUEbdGs2AgAgACgCACEAIAJBEGokACAACwsAQantj5IDEIEB",
"CwsAQar7w+QAEIEBCxEAIAAgACgCACABbDYCACAACwsAQdT2h8kBEIEBCyQAIAAgATYCACAAIAEo",
"AgQiATYCBCAAIAEgAkEEdGo2AgggAAsPACAAKAIAIAAoAgQ2AgQLIwECfyMAQRBrIgIkACAAIAEQ",
"RyEDIAJBEGokACABIAAgAxsLDgAgACABKAIANgIAIAALDQAgACgCACABKAIARwvbAgEBfyMAQSBr",
"IgIkACACIAE2AhAgAiAANgIYAkACQCACQRBqIAJBCGpBABAOEFUEQAJ/IAJBGGogAkEIakEAEA4Q",
"LQRAIAJBEGogAkEIakEAEA4QLQRAIAJBGGoQJCACQRBqECQQVgwCCyACIAJBGGoQJCACKAIQEFY2",
"AgggAkEIahAkDAELIAJBEGogAkEIakEAEA4QLQRAIAIgAigCGCACQRBqECQQVjYCCCACQQhqECQM",
"AQsgAkEYaiACQQhqQQAQDhBJRQ0CIAJBEGogAkEIakEAEA4QPUUNAyACQRhqIAJBEGoQPQRAIAIQ",
"TjYCCCACIAJBEGogAkEYahAvEFc2AgAgAkEIaiACEEsMAQsgAkEYaiACQRBqEC8QVwshACACQSBq",
"JAAgAA8LQeYKQcMIQcwEQZ0IEF0AC0G8CkHDCEHaBEGdCBBdAAtBrwpBwwhB2wRBnQgQXQAL1QEB",
"An8jAEHQAGsiASQAIAEgADYCSAJAIAFByABqIAFBQGtBABAOEEkEQCABQcgAaiABQThqQQEQDhAp",
"DQELQZAKQcMIQbgEQa4JEF0ACyABQfeO/AQ2AkAgAUGOq81tNgI4IAFB0MPYPzYCMCABIAFByABq",
"IgAgABAmNgIoIAEgAUFAayABQShqIgIQJjYCCCABIAFBCGogAUE4ahAnNgIQIAEgAUEQaiACECY2",
"AhggASABQRhqIAFBMGoQJzYCICABQSBqIAAQJiEAIAFB0ABqJAAgAAsJACABQQA6AAALJwAgAyAD",
"KAIAIAIgAWsiAGsiAjYCACAAQQBKBEAgAiABIAAQXBoLCwwAIAEgAigCADYCAAsEABABCzMBAX8g",
"AgRAIAAhAwNAIAMgAS0AADoAACADQQFqIQMgAUEBaiEBIAJBAWsiAg0ACwsgAAuWAwECfyMAQRBr",
"IgQkACAEIAI2AgwgBCADNgIIIAQgATYCBCAEIAA2AgAjAEEQayICJAAgAiAENgIMQQAhASMAQdAB",
"ayIAJAAgACAENgLMASAAQaABaiIDQQBBKBBgIAAgACgCzAE2AsgBAkBBACAAQcgBaiAAQdAAaiAD",
"EGRBAEgNAEHk1AAoAgBBAE4hBEGY1AAoAgAhA0Hg1AAoAgBBAEwEQEGY1AAgA0FfcTYCAAsCfwJA",
"AkBByNQAKAIARQRAQcjUAEHQADYCAEG01ABBADYCAEGo1ABCADcDAEHE1AAoAgAhAUHE1AAgADYC",
"AAwBC0Go1AAoAgANAQtBf0GY1AAQYQ0BGgtBmNQAIABByAFqIABB0ABqIABBoAFqEGQLIQUgAQR/",
"QZjUAEEAQQBBvNQAKAIAEQcAGkHI1ABBADYCAEHE1AAgATYCAEG01ABBADYCAEGs1AAoAgAaQajU",
"AEIANwMAQQAFIAULGkGY1ABBmNQAKAIAIANBIHFyNgIAIARFDQALIABB0AFqJAAgAkEQaiQAAAsG",
"AEGg1gALCgAgACgCPBpCAAshACACBEADQCAAIAE6AAAgAEEBaiEAIAJBAWsiAg0ACwsLWQEBfyAA",
"IAAoAkgiAUEBayABcjYCSCAAKAIAIgFBCHEEQCAAIAFBIHI2AgBBfw8LIABCADcCBCAAIAAoAiwi",
"ATYCHCAAIAE2AhQgACABIAAoAjBqNgIQQQALCgAgAEEwa0EKSQt+AgF/AX4gAL0iA0I0iKdB/w9x",
"IgJB/w9HBHwgAkUEQCABIABEAAAAAAAAAABhBH9BAAUgAEQAAAAAAADwQ6IgARBjIQAgASgCAEFA",
"ags2AgAgAA8LIAEgAkH+B2s2AgAgA0L/////////h4B/g0KAgICAgICA8D+EvwUgAAsLkxQCE38B",
"fkH0CiELIwBB0ABrIgUkACAFQfQKNgJMIAVBN2ohFSAFQThqIRACQAJAAkACQANAIAshCiAEIAxB",
"/////wdzSg0BIAQgDGohDAJAAkACQCAKIgQtAAAiBgRAA0ACQAJAIAZB/wFxIgtFBEAgBCELDAEL",
"IAtBJUcNASAEIQYDQCAGLQABQSVHBEAgBiELDAILIARBAWohBCAGLQACIQcgBkECaiILIQYgB0El",
"Rg0ACwsgBCAKayIEIAxB/////wdzIhZKDQcgAARAIAAgCiAEEGULIAQNBiAFIAs2AkwgC0EBaiEE",
"QX8hDQJAIAssAAEQYkUNACALLQACQSRHDQAgC0EDaiEEIAssAAFBMGshDUEBIRELIAUgBDYCTEEA",
"IQgCQCAELAAAIgZBIGsiC0EfSwRAIAQhBwwBCyAEIQdBASALdCILQYnRBHFFDQADQCAFIARBAWoi",
"BzYCTCAIIAtyIQggBCwAASIGQSBrIgtBIE8NASAHIQRBASALdCILQYnRBHENAAsLAkAgBkEqRgRA",
"An8CQCAHLAABEGJFDQAgBy0AAkEkRw0AIAcsAAFBAnQgA2pBwAFrQQo2AgAgB0EDaiEGQQEhESAH",
"LAABQQN0IAJqQYADaygCAAwBCyARDQYgB0EBaiEGIABFBEAgBSAGNgJMQQAhEUEAIQ4MAwsgASAB",
"KAIAIgRBBGo2AgBBACERIAQoAgALIQ4gBSAGNgJMIA5BAE4NAUEAIA5rIQ4gCEGAwAByIQgMAQsg",
"BUHMAGoQZiIOQQBIDQggBSgCTCEGC0EAIQRBfyEJAn8gBi0AAEEuRwRAIAYhC0EADAELIAYtAAFB",
"KkYEQAJ/AkAgBiwAAhBiRQ0AIAYtAANBJEcNACAGLAACQQJ0IANqQcABa0EKNgIAIAZBBGohCyAG",
"LAACQQN0IAJqQYADaygCAAwBCyARDQYgBkECaiELQQAgAEUNABogASABKAIAIgdBBGo2AgAgBygC",
"AAshCSAFIAs2AkwgCUF/c0EfdgwBCyAFIAZBAWo2AkwgBUHMAGoQZiEJIAUoAkwhC0EBCyESAkAD",
"QCAEIQ8gCyITLAAAIgRB+wBrQUZJDQEgE0EBaiELIAQgD0E6bGpBnwtqLQAAIgRBAWtBCEkNAAsg",
"BSALNgJMQRwhBwJAAkAgBEEbRwRAIARFDQwgDUEATgRAIAMgDUECdGogBDYCACAFIAIgDUEDdGop",
"AwA3A0AMAgsgAEUNCSAFQUBrIAQgARBnDAILIA1BAE4NCwtBACEEIABFDQgLIAhB//97cSIGIAgg",
"CEGAwABxGyEIQQAhDUGACCEUIBAhBwJAAkACQAJ/AkACQAJAAkACfwJAAkACQAJAAkACQAJAIBMs",
"AAAiBEFfcSAEIARBD3FBA0YbIAQgDxsiBEHYAGsOIQQVFRUVFRUVFQ4VDwYODg4VBhUVFRUCBQMV",
"FQkVARUVBAALAkAgBEHBAGsOBw4VCxUODg4ACyAEQdMARg0JDBQLIAUpA0AhF0GACAwFC0EAIQQC",
"QAJAAkACQAJAAkACQCAPQf8BcQ4IAAECAwQbBQYbCyAFKAJAIAw2AgAMGgsgBSgCQCAMNgIADBkL",
"IAUoAkAgDKw3AwAMGAsgBSgCQCAMOwEADBcLIAUoAkAgDDoAAAwWCyAFKAJAIAw2AgAMFQsgBSgC",
"QCAMrDcDAAwUCyAJQQggCUEISxshCSAIQQhyIQhB+AAhBAsgECEKIARBIHEhBiAFKQNAIhdQRQRA",
"A0AgCkEBayIKIBenQQ9xQbAPai0AACAGcjoAACAXQg9WIQ8gF0IEiCEXIA8NAAsLIAhBCHFFIAUp",
"A0BQcg0DIARBBHZBgAhqIRRBAiENDAMLIBAhBCAFKQNAIhdQRQRAA0AgBEEBayIEIBenQQdxQTBy",
"OgAAIBdCB1YhCiAXQgOIIRcgCg0ACwsgBCEKIAhBCHFFDQIgCSAQIAprIgRBAWogBCAJSBshCQwC",
"CyAFKQNAIhdCAFMEQCAFQgAgF30iFzcDQEEBIQ1BgAgMAQsgCEGAEHEEQEEBIQ1BgQgMAQtBgghB",
"gAggCEEBcSINGwshFCAXIBAQaCEKCyASQQAgCUEASBsNDyAIQf//e3EgCCASGyEIIAUpA0AiF0IA",
"UiAJckUEQCAQIgohB0EAIQkMDQsgCSAXUCAQIApraiIEIAQgCUgbIQkMDAsCfyAJQf////8HIAlB",
"/////wdJGyIPIgdBAEchCAJAAkACQCAFKAJAIgRBiQogBBsiCiIEQQNxRSAHRXINAANAIAQtAABF",
"DQIgB0EBayIHQQBHIQggBEEBaiIEQQNxRQ0BIAcNAAsLIAhFDQELAkAgBC0AAEUgB0EESXJFBEAD",
"QCAEKAIAIghBf3MgCEGBgoQIa3FBgIGChHhxDQIgBEEEaiEEIAdBBGsiB0EDSw0ACwsgB0UNAQsD",
"QCAEIAQtAABFDQIaIARBAWohBCAHQQFrIgcNAAsLQQALIgQgCmsgDyAEGyIEIApqIQcgCUEATgRA",
"IAYhCCAEIQkMDAsgBiEIIAQhCSAHLQAADQ4MCwsgCQRAIAUoAkAMAgtBACEEIABBICAOQQAgCBBp",
"DAILIAVBADYCDCAFIAUpA0A+AgggBSAFQQhqIgQ2AkBBfyEJIAQLIQZBACEEAkADQCAGKAIAIgpF",
"DQEgBUEEaiAKEGwiCkEASCIHIAogCSAEa0tyRQRAIAZBBGohBiAJIAQgCmoiBEsNAQwCCwsgBw0O",
"C0E9IQcgBEEASA0MIABBICAOIAQgCBBpIARFBEBBACEEDAELQQAhByAFKAJAIQYDQCAGKAIAIgpF",
"DQEgBUEEaiAKEGwiCiAHaiIHIARLDQEgACAFQQRqIAoQZSAGQQRqIQYgBCAHSw0ACwsgAEEgIA4g",
"BCAIQYDAAHMQaSAOIAQgBCAOSBshBAwJCyASQQAgCUEASBsNCUE9IQcgACAFKwNAIA4gCSAIIARB",
"CBEMACIEQQBODQgMCgsgBSAFKQNAPAA3QQEhCSAVIQogBiEIDAULIAUgEzYCTAwDCyAELQABIQYg",
"BEEBaiEEDAALAAsgAA0HIBFFDQJBASEEA0AgAyAEQQJ0aigCACIABEAgAiAEQQN0aiAAIAEQZ0EB",
"IQwgBEEBaiIEQQpHDQEMCQsLQQEhDCAEQQpPDQcDQCADIARBAnRqKAIADQEgBEEBaiIEQQpHDQAL",
"DAcLQRwhBwwECyAJIAcgCmsiDyAJIA9KGyIJIA1B/////wdzSg0CQT0hByAOIAkgDWoiBiAGIA5I",
"GyIEIBZKDQMgAEEgIAQgBiAIEGkgACAUIA0QZSAAQTAgBCAGIAhBgIAEcxBpIABBMCAJIA9BABBp",
"IAAgCiAPEGUgAEEgIAQgBiAIQYDAAHMQaQwBCwtBACEMDAMLQT0hBwtBoNYAIAc2AgALQX8hDAsg",
"BUHQAGokACAMC74BAQN/IAAtAABBIHFFBEACQCABIQMCQCACIAAiASgCECIABH8gAAUgARBhDQEg",
"ASgCEAsgASgCFCIFa0sEQCABIAMgAiABKAIkEQcAGgwCCwJAIAEoAlBBAEgNACACIQADQCAAIgRF",
"DQEgAyAEQQFrIgBqLQAAQQpHDQALIAEgAyAEIAEoAiQRBwAgBEkNASADIARqIQMgAiAEayECIAEo",
"AhQhBQsgBSADIAIQXBogASABKAIUIAJqNgIUCwsLC2sBBH8gACgCACwAABBiRQRAQQAPCwNAIAAo",
"AgAhA0F/IQEgAkHMmbPmAE0EQEF/IAMsAABBMGsiBCACQQpsIgFqIAQgAUH/////B3NKGyEBCyAA",
"IANBAWo2AgAgASECIAMsAAEQYg0ACyACC7wCAAJAAkACQAJAAkACQAJAAkACQAJAAkAgAUEJaw4S",
"AAgJCggJAQIDBAoJCgoICQUGBwsgAiACKAIAIgFBBGo2AgAgACABKAIANgIADwsgAiACKAIAIgFB",
"BGo2AgAgACABMgEANwMADwsgAiACKAIAIgFBBGo2AgAgACABMwEANwMADwsgAiACKAIAIgFBBGo2",
"AgAgACABMAAANwMADwsgAiACKAIAIgFBBGo2AgAgACABMQAANwMADwsgAiACKAIAQQdqQXhxIgFB",
"CGo2AgAgACABKwMAOQMADwsgACACQQkRBAALDwsgAiACKAIAIgFBBGo2AgAgACABNAIANwMADwsg",
"AiACKAIAIgFBBGo2AgAgACABNQIANwMADwsgAiACKAIAQQdqQXhxIgFBCGo2AgAgACABKQMANwMA",
"C4MBAgN/AX4CQCAAQoCAgIAQVARAIAAhBQwBCwNAIAFBAWsiASAAIABCCoAiBUIKfn2nQTByOgAA",
"IABC/////58BViECIAUhACACDQALCyAFpyICBEADQCABQQFrIgEgAiACQQpuIgNBCmxrQTByOgAA",
"IAJBCUshBCADIQIgBA0ACwsgAQtsAQF/IwBBgAJrIgUkACAEQYDABHEgAiADTHJFBEAgBSABQf8B",
"cSACIANrIgNBgAIgA0GAAkkiARsQYCABRQRAA0AgACAFQYACEGUgA0GAAmsiA0H/AUsNAAsLIAAg",
"BSADEGULIAVBgAJqJAALnhgDEn8BfAJ+IwBBsARrIgskACALQQA2AiwCQCABvSIZQgBTBEBBASEQ",
"QYoIIRMgAZoiAb0hGQwBCyAEQYAQcQRAQQEhEEGNCCETDAELQZAIQYsIIARBAXEiEBshEyAQRSEV",
"CwJAIBlCgICAgICAgPj/AINCgICAgICAgPj/AFEEQCAAQSAgAiAQQQNqIgMgBEH//3txEGkgACAT",
"IBAQZSAAQaEJQcwJIAVBIHEiBRtBpQlB0AkgBRsgASABYhtBAxBlIABBICACIAMgBEGAwABzEGkg",
"AyACIAIgA0gbIQkMAQsgC0EQaiERAkACfwJAIAEgC0EsahBjIgEgAaAiAUQAAAAAAAAAAGIEQCAL",
"IAsoAiwiBkEBazYCLCAFQSByIg5B4QBHDQEMAwsgBUEgciIOQeEARg0CIAsoAiwhCkEGIAMgA0EA",
"SBsMAQsgCyAGQR1rIgo2AiwgAUQAAAAAAACwQaIhAUEGIAMgA0EASBsLIQwgC0EwakEAQaACIApB",
"AEgbaiINIQcDQCAHAn8gAUQAAAAAAADwQWMgAUQAAAAAAAAAAGZxBEAgAasMAQtBAAsiAzYCACAH",
"QQRqIQcgASADuKFEAAAAAGXNzUGiIgFEAAAAAAAAAABiDQALAkAgCkEATARAIAohAyAHIQYgDSEI",
"DAELIA0hCCAKIQMDQCADQR0gA0EdSBshAwJAIAdBBGsiBiAISQ0AIAOtIRpCACEZA0AgBiAZQv//",
"//8PgyAGNQIAIBqGfCIZIBlCgJTr3AOAIhlCgJTr3AN+fT4CACAGQQRrIgYgCE8NAAsgGaciBkUN",
"ACAIQQRrIgggBjYCAAsDQCAIIAciBkkEQCAGQQRrIgcoAgBFDQELCyALIAsoAiwgA2siAzYCLCAG",
"IQcgA0EASg0ACwsgA0EASARAIAxBGWpBCW5BAWohDyAOQeYARiESA0BBACADayIDQQkgA0EJSBsh",
"CQJAIAYgCE0EQCAIKAIAIQcMAQtBgJTr3AMgCXYhFEF/IAl0QX9zIRZBACEDIAghBwNAIAcgAyAH",
"KAIAIhcgCXZqNgIAIBYgF3EgFGwhAyAHQQRqIgcgBkkNAAsgCCgCACEHIANFDQAgBiADNgIAIAZB",
"BGohBgsgCyALKAIsIAlqIgM2AiwgDSAIIAdFQQJ0aiIIIBIbIgcgD0ECdGogBiAGIAdrQQJ1IA9K",
"GyEGIANBAEgNAAsLQQAhAwJAIAYgCE0NACANIAhrQQJ1QQlsIQNBCiEHIAgoAgAiCUEKSQ0AA0Ag",
"A0EBaiEDIAkgB0EKbCIHTw0ACwsgDEEAIAMgDkHmAEYbayAOQecARiAMQQBHcWsiByAGIA1rQQJ1",
"QQlsQQlrSARAQQRBpAIgCkEASBsgC2ogB0GAyABqIglBCW0iD0ECdGpB0B9rIQpBCiEHIAkgD0EJ",
"bGsiCUEHTARAA0AgB0EKbCEHIAlBAWoiCUEIRw0ACwsCQCAKKAIAIhIgEiAHbiIPIAdsayIJRSAK",
"QQRqIhQgBkZxDQACQCAPQQFxRQRARAAAAAAAAEBDIQEgB0GAlOvcA0cgCCAKT3INASAKQQRrLQAA",
"QQFxRQ0BC0QBAAAAAABAQyEBC0QAAAAAAADgP0QAAAAAAADwP0QAAAAAAAD4PyAGIBRGG0QAAAAA",
"AAD4PyAJIAdBAXYiFEYbIAkgFEkbIRgCQCAVDQAgEy0AAEEtRw0AIBiaIRggAZohAQsgCiASIAlr",
"Igk2AgAgASAYoCABYQ0AIAogByAJaiIDNgIAIANBgJTr3ANPBEADQCAKQQA2AgAgCCAKQQRrIgpL",
"BEAgCEEEayIIQQA2AgALIAogCigCAEEBaiIDNgIAIANB/5Pr3ANLDQALCyANIAhrQQJ1QQlsIQNB",
"CiEHIAgoAgAiCUEKSQ0AA0AgA0EBaiEDIAkgB0EKbCIHTw0ACwsgCkEEaiIHIAYgBiAHSxshBgsD",
"QCAGIgcgCE0iCUUEQCAHQQRrIgYoAgBFDQELCwJAIA5B5wBHBEAgBEEIcSEKDAELIANBf3NBfyAM",
"QQEgDBsiBiADSiADQXtKcSIKGyAGaiEMQX9BfiAKGyAFaiEFIARBCHEiCg0AQXchBgJAIAkNACAH",
"QQRrKAIAIg5FDQBBCiEJQQAhBiAOQQpwDQADQCAGIgpBAWohBiAOIAlBCmwiCXBFDQALIApBf3Mh",
"BgsgByANa0ECdUEJbCEJIAVBX3FBxgBGBEBBACEKIAwgBiAJakEJayIGQQAgBkEAShsiBiAGIAxK",
"GyEMDAELQQAhCiAMIAMgCWogBmpBCWsiBkEAIAZBAEobIgYgBiAMShshDAtBfyEJIAxB/f///wdB",
"/v///wcgCiAMciISG0oNASAMIBJBAEdqQQFqIQ4CQCAFQV9xIhVBxgBGBEAgAyAOQf////8Hc0oN",
"AyADQQAgA0EAShshBgwBCyARIAMgA0EfdSIGcyAGa60gERBoIgZrQQFMBEADQCAGQQFrIgZBMDoA",
"ACARIAZrQQJIDQALCyAGQQJrIg8gBToAACAGQQFrQS1BKyADQQBIGzoAACARIA9rIgYgDkH/////",
"B3NKDQILIAYgDmoiAyAQQf////8Hc0oNASAAQSAgAiADIBBqIgUgBBBpIAAgEyAQEGUgAEEwIAIg",
"BSAEQYCABHMQaQJAAkACQCAVQcYARgRAIAtBEGoiBkEIciEDIAZBCXIhCiANIAggCCANSxsiCSEI",
"A0AgCDUCACAKEGghBgJAIAggCUcEQCAGIAtBEGpNDQEDQCAGQQFrIgZBMDoAACAGIAtBEGpLDQAL",
"DAELIAYgCkcNACALQTA6ABggAyEGCyAAIAYgCiAGaxBlIAhBBGoiCCANTQ0ACyASBEAgAEGHCkEB",
"EGULIAxBAEwgByAITXINAQNAIAg1AgAgChBoIgYgC0EQaksEQANAIAZBAWsiBkEwOgAAIAYgC0EQ",
"aksNAAsLIAAgBiAMQQkgDEEJSBsQZSAMQQlrIQYgCEEEaiIIIAdPDQMgDEEJSiEDIAYhDCADDQAL",
"DAILAkAgDEEASA0AIAcgCEEEaiAHIAhLGyEJIAtBEGoiBkEIciEDIAZBCXIhDSAIIQcDQCANIAc1",
"AgAgDRBoIgZGBEAgC0EwOgAYIAMhBgsCQCAHIAhHBEAgBiALQRBqTQ0BA0AgBkEBayIGQTA6AAAg",
"BiALQRBqSw0ACwwBCyAAIAZBARBlIAZBAWohBiAKIAxyRQ0AIABBhwpBARBlCyAAIAYgDCANIAZr",
"IgYgBiAMShsQZSAMIAZrIQwgB0EEaiIHIAlPDQEgDEEATg0ACwsgAEEwIAxBEmpBEkEAEGkgACAP",
"IBEgD2sQZQwCCyAMIQYLIABBMCAGQQlqQQlBABBpCyAAQSAgAiAFIARBgMAAcxBpIAUgAiACIAVI",
"GyEJDAELIBMgBUEadEEfdUEJcWohDAJAIANBC0sNAEEMIANrIQZEAAAAAAAAMEAhGANAIBhEAAAA",
"AAAAMECiIRggBkEBayIGDQALIAwtAABBLUYEQCAYIAGaIBihoJohAQwBCyABIBigIBihIQELIBEg",
"CygCLCIGIAZBH3UiBnMgBmutIBEQaCIGRgRAIAtBMDoADyALQQ9qIQYLIBBBAnIhCiAFQSBxIQgg",
"CygCLCEHIAZBAmsiDSAFQQ9qOgAAIAZBAWtBLUErIAdBAEgbOgAAIARBCHEhBiALQRBqIQcDQCAH",
"IgUCfyABmUQAAAAAAADgQWMEQCABqgwBC0GAgICAeAsiB0GwD2otAAAgCHI6AAAgBiADQQBKckUg",
"ASAHt6FEAAAAAAAAMECiIgFEAAAAAAAAAABhcSAFQQFqIgcgC0EQamtBAUdyRQRAIAVBLjoAASAF",
"QQJqIQcLIAFEAAAAAAAAAABiDQALQX8hCUH9////ByAKIBEgDWsiBWoiBmsgA0gNACAAQSAgAiAG",
"An8CQCADRQ0AIAcgC0EQamsiCEECayADTg0AIANBAmoMAQsgByALQRBqayIICyIHaiIDIAQQaSAA",
"IAwgChBlIABBMCACIAMgBEGAgARzEGkgACALQRBqIAgQZSAAQTAgByAIa0EAQQAQaSAAIA0gBRBl",
"IABBICACIAMgBEGAwABzEGkgAyACIAIgA0gbIQkLIAtBsARqJAAgCQuJBQIGfgF/IAEgASgCAEEH",
"akF4cSIBQRBqNgIAIAACfCABKQMAIQQgASkDCCEFIwBBIGsiACQAAkAgBUL///////////8AgyID",
"QoCAgICAgMCAPH0gA0KAgICAgIDA/8MAfVQEQCAFQgSGIARCPIiEIQMgBEL//////////w+DIgRC",
"gYCAgICAgIAIWgRAIANCgYCAgICAgIDAAHwhAgwCCyADQoCAgICAgICAQH0hAiAEQoCAgICAgICA",
"CFINASACIANCAYN8IQIMAQsgBFAgA0KAgICAgIDA//8AVCADQoCAgICAgMD//wBRG0UEQCAFQgSG",
"IARCPIiEQv////////8Dg0KAgICAgICA/P8AhCECDAELQoCAgICAgID4/wAhAiADQv///////7//",
"wwBWDQBCACECIANCMIinIgFBkfcASQ0AIAQhAiAFQv///////z+DQoCAgICAgMAAhCIDIQYCQCAB",
"QYH3AGsiCEHAAHEEQCACIAhBQGqthiEGQgAhAgwBCyAIRQ0AIAYgCK0iB4YgAkHAACAIa62IhCEG",
"IAIgB4YhAgsgACACNwMQIAAgBjcDGAJAQYH4ACABayIBQcAAcQRAIAMgAUFAaq2IIQRCACEDDAEL",
"IAFFDQAgA0HAACABa62GIAQgAa0iAoiEIQQgAyACiCEDCyAAIAQ3AwAgACADNwMIIAApAwhCBIYg",
"ACkDACIEQjyIhCECIAApAxAgACkDGIRCAFKtIARC//////////8Pg4QiBEKBgICAgICAgAhaBEAg",
"AkIBfCECDAELIARCgICAgICAgIAIUg0AIAJCAYMgAnwhAgsgAEEgaiQAIAIgBUKAgICAgICAgIB/",
"g4S/CzkDAAuZAgAgAEUEQEEADwsCfwJAIAAEfyABQf8ATQ0BAkBBvNcAKAIAKAIARQRAIAFBgH9x",
"QYC/A0YNAwwBCyABQf8PTQRAIAAgAUE/cUGAAXI6AAEgACABQQZ2QcABcjoAAEECDAQLIAFBgEBx",
"QYDAA0cgAUGAsANPcUUEQCAAIAFBP3FBgAFyOgACIAAgAUEMdkHgAXI6AAAgACABQQZ2QT9xQYAB",
"cjoAAUEDDAQLIAFBgIAEa0H//z9NBEAgACABQT9xQYABcjoAAyAAIAFBEnZB8AFyOgAAIAAgAUEG",
"dkE/cUGAAXI6AAIgACABQQx2QT9xQYABcjoAAUEEDAQLC0Gg1gBBGTYCAEF/BUEBCwwBCyAAIAE6",
"AABBAQsLbwECf0Go1QAoAgAiASAAQQNqQXxxIgJqIQACQCACQQAgACABTRsNACAAPwBBEHRLBEAg",
"AD8AQRB0a0H//wNqQRB2QABBf0YEf0EABUEAEABBAQtFDQELQajVACAANgIAIAEPC0Gg1gBBMDYC",
"AEF/C5cuAQx/IABBASAAGyELAkADQEEAIQMjAEEQayIMJAACQAJAAkACQAJAAkACQAJAAkACQAJA",
"IAtB9AFNBEBB1NcAKAIAIgZBECALQQtqQXhxIAtBC0kbIgdBA3YiAnYiAUEDcQRAAkAgAUF/c0EB",
"cSACaiICQQN0IgBB/NcAaiIBIABBhNgAaigCACIDKAIIIgBGBEBB1NcAIAZBfiACd3E2AgAMAQsg",
"ACABNgIMIAEgADYCCAsgA0EIaiEBIAMgAkEDdCIAQQNyNgIEIAAgA2oiACAAKAIEQQFyNgIEDAwL",
"IAdB3NcAKAIAIgpNDQEgAQRAAkBBAiACdCIAQQAgAGtyIAEgAnRxIgBBACAAa3FBAWsiACAAQQx2",
"QRBxIgJ2IgFBBXZBCHEiACACciABIAB2IgFBAnZBBHEiAHIgASAAdiIBQQF2QQJxIgByIAEgAHYi",
"AUEBdkEBcSIAciABIAB2aiIDQQN0IgBB/NcAaiIBIABBhNgAaigCACIEKAIIIgBGBEBB1NcAIAZB",
"fiADd3EiBjYCAAwBCyAAIAE2AgwgASAANgIICyAEIAdBA3I2AgQgBCAHaiICIANBA3QiACAHayID",
"QQFyNgIEIAAgBGogAzYCACAKBEAgCkF4cUH81wBqIQVB6NcAKAIAIQECfyAGQQEgCkEDdnQiAHFF",
"BEBB1NcAIAAgBnI2AgAgBQwBCyAFKAIICyEAIAUgATYCCCAAIAE2AgwgASAFNgIMIAEgADYCCAsg",
"BEEIaiEBQejXACACNgIAQdzXACADNgIADAwLQdjXACgCACIJRQ0BIAlBACAJa3FBAWsiACAAQQx2",
"QRBxIgJ2IgFBBXZBCHEiACACciABIAB2IgFBAnZBBHEiAHIgASAAdiIBQQF2QQJxIgByIAEgAHYi",
"AUEBdkEBcSIAciABIAB2akECdEGE2gBqKAIAIgIoAgRBeHEgB2shBSACIQADQAJAIAAoAhAiAUUE",
"QCAAKAIUIgFFDQELIAEoAgRBeHEgB2siACAFIAAgBUkiABshBSABIAIgABshAiABIQAMAQsLIAIo",
"AhghCCACIAIoAgwiA0cEQCACKAIIIgBB5NcAKAIASRogACADNgIMIAMgADYCCAwLCyACQRRqIgAo",
"AgAiAUUEQCACKAIQIgFFDQMgAkEQaiEACwNAIAAhBCABIgNBFGoiACgCACIBDQAgA0EQaiEAIAMo",
"AhAiAQ0ACyAEQQA2AgAMCgtBfyEHIAtBv39LDQAgC0ELaiIAQXhxIQdB2NcAKAIAIglFDQBBACAH",
"ayEFAkACQAJAAn9BACAHQYACSQ0AGkEfIAdB////B0sNABogAEEIdiIAIABBgP4/akEQdkEIcSIC",
"dCIAIABBgOAfakEQdkEEcSIBdCIAIABBgIAPakEQdkECcSIAdEEPdiABIAJyIAByayIAQQF0IAcg",
"AEEVanZBAXFyQRxqCyIGQQJ0QYTaAGooAgAiAEUEQEEAIQEMAQtBACEBIAdBAEEZIAZBAXZrIAZB",
"H0YbdCECA0ACQCAAKAIEQXhxIAdrIgQgBU8NACAAIQMgBCIFDQBBACEFIAAhAQwDCyABIAAoAhQi",
"BCAEIAAgAkEddkEEcWooAhAiAEYbIAEgBBshASACQQF0IQIgAA0ACwsgASADckUEQEEAIQNBAiAG",
"dCIAQQAgAGtyIAlxIgBFDQMgAEEAIABrcUEBayIAIABBDHZBEHEiAnYiAUEFdkEIcSIAIAJyIAEg",
"AHYiAUECdkEEcSIAciABIAB2IgFBAXZBAnEiAHIgASAAdiIBQQF2QQFxIgByIAEgAHZqQQJ0QYTa",
"AGooAgAhAQsgAUUNAQsDQCABKAIEQXhxIAdrIgAgBUkhAiAAIAUgAhshBSABIAMgAhshAyABKAIQ",
"IgAEfyAABSABKAIUCyIBDQALCyADRQ0AIAVB3NcAKAIAIAdrTw0AIAMoAhghBiADIAMoAgwiAkcE",
"QCADKAIIIgBB5NcAKAIASRogACACNgIMIAIgADYCCAwJCyADQRRqIgAoAgAiAUUEQCADKAIQIgFF",
"DQMgA0EQaiEACwNAIAAhBCABIgJBFGoiACgCACIBDQAgAkEQaiEAIAIoAhAiAQ0ACyAEQQA2AgAM",
"CAsgB0Hc1wAoAgAiAk0EQEHo1wAoAgAhAwJAIAIgB2siAUEQTwRAQdzXACABNgIAQejXACADIAdq",
"IgA2AgAgACABQQFyNgIEIAIgA2ogATYCACADIAdBA3I2AgQMAQtB6NcAQQA2AgBB3NcAQQA2AgAg",
"AyACQQNyNgIEIAIgA2oiACAAKAIEQQFyNgIECyADQQhqIQEMCgsgB0Hg1wAoAgAiCEkEQEHg1wAg",
"CCAHayIBNgIAQezXAEHs1wAoAgAiAiAHaiIANgIAIAAgAUEBcjYCBCACIAdBA3I2AgQgAkEIaiEB",
"DAoLQQAhASAHQS9qIgkCf0Gs2wAoAgAEQEG02wAoAgAMAQtBuNsAQn83AgBBsNsAQoCggICAgAQ3",
"AgBBrNsAIAxBDGpBcHFB2KrVqgVzNgIAQcDbAEEANgIAQZDbAEEANgIAQYAgCyIAaiIGQQAgAGsi",
"BHEiACAHTQ0JQYzbACgCACIFBEBBhNsAKAIAIgMgAGoiAiADTSACIAVLcg0KC0GQ2wAtAABBBHEN",
"BAJAAkBB7NcAKAIAIgMEQEGU2wAhAQNAIAMgASgCACICTwRAIAIgASgCBGogA0sNAwsgASgCCCIB",
"DQALC0EAEG0iAkF/Rg0FIAAhBkGw2wAoAgAiA0EBayIBIAJxBEAgACACayABIAJqQQAgA2txaiEG",
"CyAGIAdNIAZB/v///wdLcg0FQYzbACgCACIFBEBBhNsAKAIAIgMgBmoiASADTSABIAVLcg0GCyAG",
"EG0iASACRw0BDAcLIAYgCGsgBHEiBkH+////B0sNBCAGEG0iAiABKAIAIAEoAgRqRg0DIAIhAQsg",
"AUF/RiAHQTBqIAZNckUEQEG02wAoAgAiAiAJIAZrakEAIAJrcSICQf7///8HSwRAIAEhAgwHCyAC",
"EG1Bf0cEQCACIAZqIQYgASECDAcLQQAgBmsQbRoMBAsgASICQX9HDQUMAwtBACEDDAcLQQAhAgwF",
"CyACQX9HDQILQZDbAEGQ2wAoAgBBBHI2AgALIABB/v///wdLDQEgABBtIgJBf0ZBABBtIgBBf0Zy",
"IAAgAk1yDQEgACACayIGIAdBKGpNDQELQYTbAEGE2wAoAgAgBmoiADYCAEGI2wAoAgAgAEkEQEGI",
"2wAgADYCAAsCQAJAAkBB7NcAKAIAIgQEQEGU2wAhAQNAIAIgASgCACIDIAEoAgQiAGpGDQIgASgC",
"CCIBDQALDAILQeTXACgCACIAQQAgACACTRtFBEBB5NcAIAI2AgALQQAhAUGY2wAgBjYCAEGU2wAg",
"AjYCAEH01wBBfzYCAEH41wBBrNsAKAIANgIAQaDbAEEANgIAA0AgAUEDdCIDQYTYAGogA0H81wBq",
"IgA2AgAgA0GI2ABqIAA2AgAgAUEBaiIBQSBHDQALQeDXACAGQShrIgNBeCACa0EHcUEAIAJBCGpB",
"B3EbIgBrIgE2AgBB7NcAIAAgAmoiADYCACAAIAFBAXI2AgQgAiADakEoNgIEQfDXAEG82wAoAgA2",
"AgAMAgsgAS0ADEEIcSADIARLciACIARNcg0AIAEgACAGajYCBEHs1wAgBEF4IARrQQdxQQAgBEEI",
"akEHcRsiAGoiAjYCAEHg1wBB4NcAKAIAIAZqIgEgAGsiADYCACACIABBAXI2AgQgASAEakEoNgIE",
"QfDXAEG82wAoAgA2AgAMAQtB5NcAKAIAIAJLBEBB5NcAIAI2AgALIAIgBmohAEGU2wAhAQJAAkAC",
"QAJAAkACQANAIAAgASgCAEcEQCABKAIIIgENAQwCCwsgAS0ADEEIcUUNAQtBlNsAIQEDQCAEIAEo",
"AgAiAE8EQCAAIAEoAgRqIgUgBEsNAwsgASgCCCEBDAALAAsgASACNgIAIAEgASgCBCAGajYCBCAC",
"QXggAmtBB3FBACACQQhqQQdxG2oiCSAHQQNyNgIEIABBeCAAa0EHcUEAIABBCGpBB3EbaiIGIAcg",
"CWoiCGshASAEIAZGBEBB7NcAIAg2AgBB4NcAQeDXACgCACABaiIANgIAIAggAEEBcjYCBAwDC0Ho",
"1wAoAgAgBkYEQEHo1wAgCDYCAEHc1wBB3NcAKAIAIAFqIgA2AgAgCCAAQQFyNgIEIAAgCGogADYC",
"AAwDCyAGKAIEIgVBA3FBAUYEQCAFQXhxIQQCQCAFQf8BTQRAIAYoAggiAyAFQQN2IgBBA3RB/NcA",
"akYaIAMgBigCDCICRgRAQdTXAEHU1wAoAgBBfiAAd3E2AgAMAgsgAyACNgIMIAIgAzYCCAwBCyAG",
"KAIYIQcCQCAGIAYoAgwiAkcEQCAGKAIIIgAgAjYCDCACIAA2AggMAQsCQCAGQRRqIgUoAgAiAA0A",
"IAZBEGoiBSgCACIADQBBACECDAELA0AgBSEDIAAiAkEUaiIFKAIAIgANACACQRBqIQUgAigCECIA",
"DQALIANBADYCAAsgB0UNAAJAIAYoAhwiA0ECdEGE2gBqIgAoAgAgBkYEQCAAIAI2AgAgAg0BQdjX",
"AEHY1wAoAgBBfiADd3E2AgAMAgsgB0EQQRQgBygCECAGRhtqIAI2AgAgAkUNAQsgAiAHNgIYIAYo",
"AhAiAARAIAIgADYCECAAIAI2AhgLIAYoAhQiAEUNACACIAA2AhQgACACNgIYCyAEIAZqIgYoAgQh",
"BSABIARqIQELIAYgBUF+cTYCBCAIIAFBAXI2AgQgASAIaiABNgIAIAFB/wFNBEAgAUF4cUH81wBq",
"IQMCf0HU1wAoAgAiAkEBIAFBA3Z0IgBxRQRAQdTXACAAIAJyNgIAIAMMAQsgAygCCAshACADIAg2",
"AgggACAINgIMIAggAzYCDCAIIAA2AggMAwtBHyEFIAFB////B00EQCABQQh2IgAgAEGA/j9qQRB2",
"QQhxIgN0IgAgAEGA4B9qQRB2QQRxIgJ0IgAgAEGAgA9qQRB2QQJxIgB0QQ92IAIgA3IgAHJrIgBB",
"AXQgASAAQRVqdkEBcXJBHGohBQsgCCAFNgIcIAhCADcCECAFQQJ0QYTaAGohAAJAQdjXACgCACID",
"QQEgBXQiAnFFBEBB2NcAIAIgA3I2AgAgACAINgIADAELIAFBAEEZIAVBAXZrIAVBH0YbdCEFIAAo",
"AgAhAgNAIAIiACgCBEF4cSABRg0DIAVBHXYhAiAFQQF0IQUgACACQQRxaiIDKAIQIgINAAsgAyAI",
"NgIQCyAIIAA2AhggCCAINgIMIAggCDYCCAwCC0Hg1wAgBkEoayIDQXggAmtBB3FBACACQQhqQQdx",
"GyIAayIBNgIAQezXACAAIAJqIgA2AgAgACABQQFyNgIEIAIgA2pBKDYCBEHw1wBBvNsAKAIANgIA",
"IAQgBUEnIAVrQQdxQQAgBUEna0EHcRtqQS9rIgAgACAEQRBqSRsiA0EbNgIEIANBnNsAKQIANwIQ",
"IANBlNsAKQIANwIIQZzbACADQQhqNgIAQZjbACAGNgIAQZTbACACNgIAQaDbAEEANgIAIANBGGoh",
"AQNAIAFBBzYCBCABQQhqIQAgAUEEaiEBIAAgBUkNAAsgAyAERg0DIAMgAygCBEF+cTYCBCAEIAMg",
"BGsiBUEBcjYCBCADIAU2AgAgBUH/AU0EQCAFQXhxQfzXAGohAgJ/QdTXACgCACIBQQEgBUEDdnQi",
"AHFFBEBB1NcAIAAgAXI2AgAgAgwBCyACKAIICyEAIAIgBDYCCCAAIAQ2AgwgBCACNgIMIAQgADYC",
"CAwEC0EfIQEgBUH///8HTQRAIAVBCHYiACAAQYD+P2pBEHZBCHEiAnQiACAAQYDgH2pBEHZBBHEi",
"AXQiACAAQYCAD2pBEHZBAnEiAHRBD3YgASACciAAcmsiAEEBdCAFIABBFWp2QQFxckEcaiEBCyAE",
"IAE2AhwgBEIANwIQIAFBAnRBhNoAaiEAAkBB2NcAKAIAIgNBASABdCICcUUEQEHY1wAgAiADcjYC",
"ACAAIAQ2AgAMAQsgBUEAQRkgAUEBdmsgAUEfRht0IQEgACgCACEDA0AgAyIAKAIEQXhxIAVGDQQg",
"AUEddiECIAFBAXQhASAAIAJBBHFqIgIoAhAiAw0ACyACIAQ2AhALIAQgADYCGCAEIAQ2AgwgBCAE",
"NgIIDAMLIAAoAggiASAINgIMIAAgCDYCCCAIQQA2AhggCCAANgIMIAggATYCCAsgCUEIaiEBDAUL",
"IAAoAggiASAENgIMIAAgBDYCCCAEQQA2AhggBCAANgIMIAQgATYCCAtB4NcAKAIAIgAgB00NAEHg",
"1wAgACAHayIBNgIAQezXAEHs1wAoAgAiAiAHaiIANgIAIAAgAUEBcjYCBCACIAdBA3I2AgQgAkEI",
"aiEBDAMLQaDWAEEwNgIAQQAhAQwCCwJAIAZFDQACQCADKAIcIgFBAnRBhNoAaiIAKAIAIANGBEAg",
"ACACNgIAIAINAUHY1wAgCUF+IAF3cSIJNgIADAILIAZBEEEUIAYoAhAgA0YbaiACNgIAIAJFDQEL",
"IAIgBjYCGCADKAIQIgAEQCACIAA2AhAgACACNgIYCyADKAIUIgBFDQAgAiAANgIUIAAgAjYCGAsC",
"QCAFQQ9NBEAgAyAFIAdqIgBBA3I2AgQgACADaiIAIAAoAgRBAXI2AgQMAQsgAyAHQQNyNgIEIAMg",
"B2oiBCAFQQFyNgIEIAQgBWogBTYCACAFQf8BTQRAIAVBeHFB/NcAaiECAn9B1NcAKAIAIgFBASAF",
"QQN2dCIAcUUEQEHU1wAgACABcjYCACACDAELIAIoAggLIQAgAiAENgIIIAAgBDYCDCAEIAI2Agwg",
"BCAANgIIDAELQR8hASAFQf///wdNBEAgBUEIdiIAIABBgP4/akEQdkEIcSICdCIAIABBgOAfakEQ",
"dkEEcSIBdCIAIABBgIAPakEQdkECcSIAdEEPdiABIAJyIAByayIAQQF0IAUgAEEVanZBAXFyQRxq",
"IQELIAQgATYCHCAEQgA3AhAgAUECdEGE2gBqIQACQAJAIAlBASABdCICcUUEQEHY1wAgAiAJcjYC",
"ACAAIAQ2AgAMAQsgBUEAQRkgAUEBdmsgAUEfRht0IQEgACgCACEHA0AgByIAKAIEQXhxIAVGDQIg",
"AUEddiECIAFBAXQhASAAIAJBBHFqIgIoAhAiBw0ACyACIAQ2AhALIAQgADYCGCAEIAQ2AgwgBCAE",
"NgIIDAELIAAoAggiASAENgIMIAAgBDYCCCAEQQA2AhggBCAANgIMIAQgATYCCAsgA0EIaiEBDAEL",
"AkAgCEUNAAJAIAIoAhwiAUECdEGE2gBqIgAoAgAgAkYEQCAAIAM2AgAgAw0BQdjXACAJQX4gAXdx",
"NgIADAILIAhBEEEUIAgoAhAgAkYbaiADNgIAIANFDQELIAMgCDYCGCACKAIQIgAEQCADIAA2AhAg",
"ACADNgIYCyACKAIUIgBFDQAgAyAANgIUIAAgAzYCGAsCQCAFQQ9NBEAgAiAFIAdqIgBBA3I2AgQg",
"ACACaiIAIAAoAgRBAXI2AgQMAQsgAiAHQQNyNgIEIAIgB2oiASAFQQFyNgIEIAEgBWogBTYCACAK",
"BEAgCkF4cUH81wBqIQRB6NcAKAIAIQMCf0EBIApBA3Z0IgAgBnFFBEBB1NcAIAAgBnI2AgAgBAwB",
"CyAEKAIICyEAIAQgAzYCCCAAIAM2AgwgAyAENgIMIAMgADYCCAtB6NcAIAE2AgBB3NcAIAU2AgAL",
"IAJBCGohAQsgDEEQaiQAIAEiAA0BQcTbACgCACIABEAgABEIAAwBCwsACyAAC8wMAQd/AkAgAEUN",
"ACAAQQhrIgIgAEEEaygCACIAQXhxIgRqIQUCQCAAQQFxDQAgAEEDcUUNASACIAIoAgAiAGsiAkHk",
"1wAoAgBJDQEgACAEaiEEQejXACgCACACRwRAIABB/wFNBEAgAigCCCIBIABBA3YiA0EDdEH81wBq",
"RhogASACKAIMIgBGBEBB1NcAQdTXACgCAEF+IAN3cTYCAAwDCyABIAA2AgwgACABNgIIDAILIAIo",
"AhghBgJAIAIgAigCDCIARwRAIAIoAggiASAANgIMIAAgATYCCAwBCwJAIAJBFGoiASgCACIDDQAg",
"AkEQaiIBKAIAIgMNAEEAIQAMAQsDQCABIQcgAyIAQRRqIgEoAgAiAw0AIABBEGohASAAKAIQIgMN",
"AAsgB0EANgIACyAGRQ0BAkAgAigCHCIBQQJ0QYTaAGoiAygCACACRgRAIAMgADYCACAADQFB2NcA",
"QdjXACgCAEF+IAF3cTYCAAwDCyAGQRBBFCAGKAIQIAJGG2ogADYCACAARQ0CCyAAIAY2AhggAigC",
"ECIBBEAgACABNgIQIAEgADYCGAsgAigCFCIBRQ0BIAAgATYCFCABIAA2AhgMAQsgBSgCBCIAQQNx",
"QQNHDQBB3NcAIAQ2AgAgBSAAQX5xNgIEIAIgBEEBcjYCBCACIARqIAQ2AgAMAQsgAiAFTw0AIAUo",
"AgQiAEEBcUUNAAJAIABBAnFFBEBB7NcAKAIAIAVGBEBB7NcAIAI2AgBB4NcAQeDXACgCACAEaiIA",
"NgIAIAIgAEEBcjYCBCACQejXACgCAEcNA0Hc1wBBADYCAEHo1wBBADYCAAwDC0Ho1wAoAgAgBUYE",
"QEHo1wAgAjYCAEHc1wBB3NcAKAIAIARqIgA2AgAgAiAAQQFyNgIEIAAgAmogADYCAAwDCyAAQXhx",
"IARqIQQCQCAAQf8BTQRAIAUoAggiASAAQQN2IgNBA3RB/NcAakYaIAEgBSgCDCIARgRAQdTXAEHU",
"1wAoAgBBfiADd3E2AgAMAgsgASAANgIMIAAgATYCCAwBCyAFKAIYIQYCQCAFIAUoAgwiAEcEQCAF",
"KAIIIgFB5NcAKAIASRogASAANgIMIAAgATYCCAwBCwJAIAVBFGoiASgCACIDDQAgBUEQaiIBKAIA",
"IgMNAEEAIQAMAQsDQCABIQcgAyIAQRRqIgEoAgAiAw0AIABBEGohASAAKAIQIgMNAAsgB0EANgIA",
"CyAGRQ0AAkAgBSgCHCIBQQJ0QYTaAGoiAygCACAFRgRAIAMgADYCACAADQFB2NcAQdjXACgCAEF+",
"IAF3cTYCAAwCCyAGQRBBFCAGKAIQIAVGG2ogADYCACAARQ0BCyAAIAY2AhggBSgCECIBBEAgACAB",
"NgIQIAEgADYCGAsgBSgCFCIBRQ0AIAAgATYCFCABIAA2AhgLIAIgBEEBcjYCBCACIARqIAQ2AgAg",
"AkHo1wAoAgBHDQFB3NcAIAQ2AgAMAgsgBSAAQX5xNgIEIAIgBEEBcjYCBCACIARqIAQ2AgALIARB",
"/wFNBEAgBEF4cUH81wBqIQACf0HU1wAoAgAiAUEBIARBA3Z0IgNxRQRAQdTXACABIANyNgIAIAAM",
"AQsgACgCCAshASAAIAI2AgggASACNgIMIAIgADYCDCACIAE2AggMAQtBHyEBIARB////B00EQCAE",
"QQh2IgAgAEGA/j9qQRB2QQhxIgB0IgEgAUGA4B9qQRB2QQRxIgF0IgMgA0GAgA9qQRB2QQJxIgN0",
"QQ92IAAgAXIgA3JrIgBBAXQgBCAAQRVqdkEBcXJBHGohAQsgAiABNgIcIAJCADcCECABQQJ0QYTa",
"AGohAAJAAkACQEHY1wAoAgAiA0EBIAF0IgdxRQRAQdjXACADIAdyNgIAIAAgAjYCACACIAA2AhgM",
"AQsgBEEAQRkgAUEBdmsgAUEfRht0IQEgACgCACEAA0AgACIDKAIEQXhxIARGDQIgAUEddiEAIAFB",
"AXQhASADIABBBHFqIgcoAhAiAA0ACyAHIAI2AhAgAiADNgIYCyACIAI2AgwgAiACNgIIDAELIAMo",
"AggiACACNgIMIAMgAjYCCCACQQA2AhggAiADNgIMIAIgADYCCAtB9NcAQfTXACgCAEEBayIAQX8g",
"ABs2AgALCwYAIAAQbwtxAQF/IAJFBEAgACgCBCABKAIERg8LIAAgAUYEQEEBDwsCQCAAKAIEIgIt",
"AAAiAEUgACABKAIEIgEtAAAiA0dyDQADQCABLQABIQMgAi0AASIARQ0BIAFBAWohASACQQFqIQIg",
"ACADRg0ACwsgACADRgvNAwEEfyMAQUBqIgQkAAJ/QQEgACABQQAQcQ0AGkEAIAFFDQAaIwBBQGoi",
"AyQAIAEoAgAiBUEEaygCACEGIAVBCGsoAgAhBSADQgA3AyAgA0IANwMoIANCADcDMCADQgA3ADcg",
"A0IANwMYIANBADYCFCADQeQPNgIQIAMgATYCDCADQZQQNgIIIAEgBWohAUEAIQUCQCAGQZQQQQAQ",
"cQRAIANBATYCOCAGIANBCGogASABQQFBACAGKAIAKAIUEQoAIAFBACADKAIgQQFGGyEFDAELIAYg",
"A0EIaiABQQFBACAGKAIAKAIYEQkAAkACQCADKAIsDgIAAQILIAMoAhxBACADKAIoQQFGG0EAIAMo",
"AiRBAUYbQQAgAygCMEEBRhshBQwBCyADKAIgQQFHBEAgAygCMA0BIAMoAiRBAUcNASADKAIoQQFH",
"DQELIAMoAhghBQsgA0FAayQAQQAgBSIBRQ0AGiAEQQhqIgNBBHJBAEE0EGAgBEEBNgI4IARBfzYC",
"FCAEIAA2AhAgBCABNgIIIAEgAyACKAIAQQEgASgCACgCHBEGACAEKAIgIgBBAUYEQCACIAQoAhg2",
"AgALIABBAUYLIQAgBEFAayQAIAALXQEBfyAAKAIQIgNFBEAgAEEBNgIkIAAgAjYCGCAAIAE2AhAP",
"CwJAIAEgA0YEQCAAKAIYQQJHDQEgACACNgIYDwsgAEEBOgA2IABBAjYCGCAAIAAoAiRBAWo2AiQL",
"CxgAIAAgASgCCEEAEHEEQCABIAIgAxBzCwsxACAAIAEoAghBABBxBEAgASACIAMQcw8LIAAoAggi",
"ACABIAIgAyAAKAIAKAIcEQYAC5oBACAAQQE6ADUCQCAAKAIEIAJHDQAgAEEBOgA0AkAgACgCECIC",
"RQRAIABBATYCJCAAIAM2AhggACABNgIQIANBAUcNAiAAKAIwQQFGDQEMAgsgASACRgRAIAAoAhgi",
"AkECRgRAIAAgAzYCGCADIQILIAAoAjBBAUcNAiACQQFGDQEMAgsgACAAKAIkQQFqNgIkCyAAQQE6",
"ADYLCyAAAkAgACgCBCABRw0AIAAoAhxBAUYNACAAIAI2AhwLC/IBACAAIAEoAgggBBBxBEAgASAC",
"IAMQdw8LAkAgACABKAIAIAQQcQRAAkAgAiABKAIQRwRAIAEoAhQgAkcNAQsgA0EBRw0CIAFBATYC",
"IA8LIAEgAzYCIAJAIAEoAixBBEYNACABQQA7ATQgACgCCCIAIAEgAiACQQEgBCAAKAIAKAIUEQoA",
"IAEtADUEQCABQQM2AiwgAS0ANEUNAQwDCyABQQQ2AiwLIAEgAjYCFCABIAEoAihBAWo2AiggASgC",
"JEEBRw0BIAEoAhhBAkcNASABQQE6ADYPCyAAKAIIIgAgASACIAMgBCAAKAIAKAIYEQkACwuRAQAg",
"ACABKAIIIAQQcQRAIAEgAiADEHcPCwJAIAAgASgCACAEEHFFDQACQCACIAEoAhBHBEAgASgCFCAC",
"Rw0BCyADQQFHDQEgAUEBNgIgDwsgASACNgIUIAEgAzYCICABIAEoAihBAWo2AigCQCABKAIkQQFH",
"DQAgASgCGEECRw0AIAFBAToANgsgAUEENgIsCws3ACAAIAEoAgggBRBxBEAgASACIAMgBBB2Dwsg",
"ACgCCCIAIAEgAiADIAQgBSAAKAIAKAIUEQoACxoAIAAgASgCCCAFEHEEQCABIAIgAyAEEHYLCwUA",
"QZIJCwUAQb0JCwQAIwALBgAgACQACxAAIwAgAGtBcHEiACQAIAALJAECfyMAQRBrIgEkACABQQhq",
"IAAQHigCACECIAFBEGokACACCwvPSiMAQYAIC5YDLSsgICAwWDB4AC0wWCswWCAwWC0weCsweCAw",
"eABhdGFuX2RpdgBzcXJ0AGZpbmRfaGlnaGVzdF9iaXQAdmVjdG9yAC9zcmMvbWFpbi9jb21wcmVz",
"c2lvbi9saWIvZnBtL21hdGguaHBwAC9zcmMvbWFpbi9jb21wcmVzc2lvbi9saWIvZnBtL2ZpeGVk",
"LmhwcABzdGQ6OmV4Y2VwdGlvbgBuYW4AaW5mAGZtb2QAYXRhbl9zYW5pdGl6ZWQAc3RkOjpiYWRf",
"YWxsb2MATkFOAElORgBvcGVyYXRvci89AGF0YW4yAHkubV92YWx1ZSAhPSAwAHkucmF3X3ZhbHVl",
"KCkgIT0gMAAuAChudWxsKQB4ID49IEZpeGVkKDApICYmIHggPD0gRml4ZWQoMSkAeCA+IEZpeGVk",
"KDApAHkgPj0gRml4ZWQoMCkAeCA+PSBGaXhlZCgwKQB5ICE9IEZpeGVkKDApAHggIT0gRml4ZWQo",
"MCkAQXNzZXJ0aW9uIGZhaWxlZDogJXMgKCVzOiAlczogJWQpCgBBoAsLgQEgCQAAMAsAAEANAABQ",
"DwAAYBEAAHATAACAFQAAkBcAAKAZAACwGwAAwB0AANAfAADgIQAA8CMAAAAmAAAQKAAAGQAKABkZ",
"GQAAAAAFAAAAAAAACQAAAAALAAAAAAAAAAAZABEKGRkZAwoHAAEACQsYAAAJBgsAAAsABhkAAAAZ",
"GRkAQbEMCyEOAAAAAAAAAAAZAAoNGRkZAA0AAAIACQ4AAAAJAA4AAA4AQesMCwEMAEH3DAsVEwAA",
"AAATAAAAAAkMAAAAAAAMAAAMAEGlDQsBEABBsQ0LFQ8AAAAEDwAAAAAJEAAAAAAAEAAAEABB3w0L",
"ARIAQesNCx4RAAAAABEAAAAACRIAAAAAABIAABIAABoAAAAaGhoAQaIOCw4aAAAAGhoaAAAAAAAA",
"CQBB0w4LARQAQd8OCxUXAAAAABcAAAAACRQAAAAAABQAABQAQY0PCwEWAEGZDwv9AhUAAAAAFQAA",
"AAAJFgAAAAAAFgAAFgAAMDEyMzQ1Njc4OUFCQ0RFRk4xMF9fY3h4YWJpdjExNl9fc2hpbV90eXBl",
"X2luZm9FAAAAAFAIAADABwAAEAkAAE4xMF9fY3h4YWJpdjExN19fY2xhc3NfdHlwZV9pbmZvRQAA",
"AFAIAADwBwAA5AcAAAAAAAAUCAAACwAAAAwAAAANAAAADgAAAA8AAAAQAAAAEQAAABIAAAAAAAAA",
"mAgAAAsAAAATAAAADQAAAA4AAAAPAAAAFAAAABUAAAAWAAAATjEwX19jeHhhYml2MTIwX19zaV9j",
"bGFzc190eXBlX2luZm9FAAAAAFAIAABwCAAAFAgAAAAAAAD0CAAACgAAABcAAAAYAAAAAAAAANwI",
"AAAKAAAAGQAAABoAAABTdDlleGNlcHRpb24AAAAAKAgAAMwIAABTdDliYWRfYWxsb2MAAAAAUAgA",
"AOQIAADcCAAAU3Q5dHlwZV9pbmZvAAAAACgIAAAACQBBohILggQBAAIAAwAEAAUABgAHAAgACQAK",
"AAsADAANAA4ADwAQABEAEgATABQAFQAWABcAGAAZABoAGwAcAB0AHgAfACAAIQAiACMAJAAlACYA",
"JwAoACkAKgArACwALQAuAC8AMAAxADIAMwA0ADUANgA3ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBD",
"AEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBYAFkAWgBbAFwAXQBeAF8A",
"YABhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG4AbwBwAHEAcgBzAHQAdQB2AHcAeAB5AHoAewB8",
"AH0AfgB/ALgAR3+Af4F/g3+Ef4V/hn+Hf4h/iX+Kf4t/jH+Nf45/j3+Qf5F/kn+Tf5R/lX+Wf5d/",
"mH+Zf5p/m3+cf51/nn+ff6B/oX+if6N/pH+lf6Z/p3+of6l/qn+rf6x/rX+uf69/sH+xf7J/s3+0",
"f7V/tn+3f7h/uX+6f7t/vH+9f75/v3/Af8F/wn/Df8R/xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/",
"0X/Sf9N/1H/Vf9Z/13/Yf9l/2n/bf9x/3X/ef99/4H/hf+J/43/kf+V/5n/nf+h/6X/qf+t/7H/t",
"f+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1//n//fwCAAEGyFguCBAEAAgADAAQABQAG",
"AAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIA",
"IwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/",
"AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsA",
"XABdAF4AXwBgAGEAYgBjAGQAZQBmAGcAaABpAGoAawBsAG0AbgBvAHAAcQByAHMAdAB1AHYAdwB4",
"AHkAegB7AHwAfQB+AH8AqQFWfoB/gX+Cf4N/hX+Gf4d/iH+Jf4p/i3+Mf41/jn+Pf5B/kX+Sf5N/",
"lH+Vf5Z/l3+Yf5l/mn+bf5x/nX+ef59/oH+hf6J/o3+kf6V/pn+nf6h/qX+qf6t/rH+tf65/r3+w",
"f7F/sn+zf7R/tX+2f7d/uH+5f7p/u3+8f71/vn+/f8B/wX/Cf8N/xH/Ff8Z/x3/If8l/yn/Lf8x/",
"zX/Of89/0H/Rf9J/03/Uf9V/1n/Xf9h/2X/af9t/3H/df95/33/gf+F/4n/jf+R/5X/mf+d/6H/p",
"f+p/63/sf+1/7n/vf/B/8X/yf/N/9H/1f/Z/93/4f/l/+n/7f/x//X/+f/9/AIAAQcIaC4IEAQAC",
"AAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAXABgAGQAaABsAHAAdAB4A",
"HwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAvADAAMQAyADMANAA1ADYANwA4ADkAOgA7",
"ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQAFEAUgBTAFQAVQBWAFcA",
"WABZAFoAWwBcAF0AXgBfAGAAYQBiAGMAZABlAGYAZwBoAGkAagBrAGwAbQBuAG8AcABxAHIAcwB0",
"AHUAdgB3AHgAeQB6AHsAfAB9AH4AggBABL97fX+Bf4J/g3+Ef4Z/h3+If4l/in+Lf4x/jX+Of49/",
"kH+Rf5J/k3+Uf5V/ln+Xf5h/mX+af5t/nH+df55/n3+gf6F/on+jf6R/pX+mf6d/qH+pf6p/q3+s",
"f61/rn+vf7B/sX+yf7N/tH+1f7Z/t3+4f7l/un+7f7x/vX++f79/wH/Bf8J/w3/Ef8V/xn/Hf8h/",
"yX/Kf8t/zH/Nf85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Zf9p/23/cf91/3n/ff+B/4X/if+N/5H/l",
"f+Z/53/of+l/6n/rf+x/7X/uf+9/8H/xf/J/83/0f/V/9n/3f/h/+X/6f/t//H/9f/5//38AgABB",
"0h4LggQBAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAQABEAEgATABQAFQAWABcAGAAZABoA",
"GwAcAB0AHgAfACAAIQAiACMAJAAlACYAJwAoACkAKgArACwALQAuAC8AMAAxADIAMwA0ADUANgA3",
"ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBDAEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMA",
"VABVAFYAVwBYAFkAWgBbAFwAXQBeAF8AYABhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG4AbwBw",
"AHEAcgBzAHQAdQB2AHcAeAB5AHoAewB8AH0AfgCnABcJ6HZYf4F/gn+Df4R/hX+Gf4d/iX+Kf4t/",
"jH+Nf45/j3+Qf5F/kn+Tf5R/lX+Wf5d/mH+Zf5p/m3+cf51/nn+ff6B/oX+if6N/pH+lf6Z/p3+o",
"f6l/qn+rf6x/rX+uf69/sH+xf7J/s3+0f7V/tn+3f7h/uX+6f7t/vH+9f75/v3/Af8F/wn/Df8R/",
"xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/0X/Sf9N/1H/Vf9Z/13/Yf9l/2n/bf9x/3X/ef99/4H/h",
"f+J/43/kf+V/5n/nf+h/6X/qf+t/7H/tf+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1/",
"/n//fwCAAEHiIguCBAEAAgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYA",
"FwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAz",
"ADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8A",
"UABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAYgBjAGQAZQBmAGcAaABpAGoAawBs",
"AG0AbgBvAHAAcQByAHMAdAB1AHYAdwB4AHkAegB7AHwAfQCLAGgB7w8QcJd+dH+Cf4N/hH+Ff4Z/",
"h3+If4l/in+Lf41/jn+Pf5B/kX+Sf5N/lH+Vf5Z/l3+Yf5l/mn+bf5x/nX+ef59/oH+hf6J/o3+k",
"f6V/pn+nf6h/qX+qf6t/rH+tf65/r3+wf7F/sn+zf7R/tX+2f7d/uH+5f7p/u3+8f71/vn+/f8B/",
"wX/Cf8N/xH/Ff8Z/x3/If8l/yn/Lf8x/zX/Of89/0H/Rf9J/03/Uf9V/1n/Xf9h/2X/af9t/3H/d",
"f95/33/gf+F/4n/jf+R/5X/mf+d/6H/pf+p/63/sf+1/7n/vf/B/8X/yf/N/9H/1f/Z/93/4f/l/",
"+n/7f/x//X/+f/9/AIAAQfImC4IEAQACAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIA",
"EwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAv",
"ADAAMQAyADMANAA1ADYANwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsA",
"TABNAE4ATwBQAFEAUgBTAFQAVQBWAFcAWABZAFoAWwBcAF0AXgBfAGAAYQBiAGMAZABlAGYAZwBo",
"AGkAagBrAGwAbQBuAG8AcABxAHIAcwB0AHUAdgB3AHgAeQB6AHsAfgCLAOsAqAPcFyNoV3wUf3R/",
"gX+Ef4V/hn+Hf4h/iX+Kf4t/jH+Nf45/j3+Qf5J/k3+Uf5V/ln+Xf5h/mX+af5t/nH+df55/n3+g",
"f6F/on+jf6R/pX+mf6d/qH+pf6p/q3+sf61/rn+vf7B/sX+yf7N/tH+1f7Z/t3+4f7l/un+7f7x/",
"vX++f79/wH/Bf8J/w3/Ef8V/xn/Hf8h/yX/Kf8t/zH/Nf85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Z",
"f9p/23/cf91/3n/ff+B/4X/if+N/5H/lf+Z/53/of+l/6n/rf+x/7X/uf+9/8H/xf/J/83/0f/V/",
"9n/3f/h/+X/6f/t//H/9f/5//38AgABBgisLggQBAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4A",
"DwAQABEAEgATABQAFQAWABcAGAAZABoAGwAcAB0AHgAfACAAIQAiACMAJAAlACYAJwAoACkAKgAr",
"ACwALQAuAC8AMAAxADIAMwA0ADUANgA3ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBDAEQARQBGAEcA",
"SABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBYAFkAWgBbAFwAXQBeAF8AYABhAGIAYwBk",
"AGUAZgBnAGgAaQBqAGsAbABtAG4AbwBwAHEAcgBzAHQAdQB2AHcAeAB5AHsAgQCYAPAAVwIbCM8f",
"MGDkd6h9D39nf35/hH+Gf4d/iH+Jf4p/i3+Mf41/jn+Pf5B/kX+Sf5N/lH+Vf5Z/l3+Yf5p/m3+c",
"f51/nn+ff6B/oX+if6N/pH+lf6Z/p3+of6l/qn+rf6x/rX+uf69/sH+xf7J/s3+0f7V/tn+3f7h/",
"uX+6f7t/vH+9f75/v3/Af8F/wn/Df8R/xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/0X/Sf9N/1H/V",
"f9Z/13/Yf9l/2n/bf9x/3X/ef99/4H/hf+J/43/kf+V/5n/nf+h/6X/qf+t/7H/tf+5/73/wf/F/",
"8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1//n//fwCAAEGSLwuCBAEAAgADAAQABQAGAAcACAAJAAoA",
"CwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAn",
"ACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMA",
"RABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBg",
"AGEAYgBjAGQAZQBmAGcAaABpAGoAawBsAG0AbgBvAHAAcQByAHMAdAB1AHYAeAB7AIEAkgC9ADAB",
"ZwK0BaoOAyf8WFVxS3qYfc9+Qn9tf35/hH+Hf4l/in+Lf4x/jX+Of49/kH+Rf5J/k3+Uf5V/ln+X",
"f5h/mX+af5t/nH+df55/n3+gf6F/on+jf6V/pn+nf6h/qX+qf6t/rH+tf65/r3+wf7F/sn+zf7R/",
"tX+2f7d/uH+5f7p/u3+8f71/vn+/f8B/wX/Cf8N/xH/Ff8Z/x3/If8l/yn/Lf8x/zX/Of89/0H/R",
"f9J/03/Uf9V/1n/Xf9h/2X/af9t/3H/df95/33/gf+F/4n/jf+R/5X/mf+d/6H/pf+p/63/sf+1/",
"7n/vf/B/8X/yf/N/9H/1f/Z/93/4f/l/+n/7f/x//X/+f/9/AIAAQaIzC4IEAQACAAMABAAFAAYA",
"BwAIAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAj",
"ACQAJQAmACcAKAApACoAKwAsAC0ALgAvADAAMQAyADMANAA1ADYANwA4ADkAOgA7ADwAPQA+AD8A",
"QABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQAFEAUgBTAFQAVQBWAFcAWABZAFoAWwBc",
"AF0AXgBfAGAAYQBiAGMAZABlAGYAZwBoAGkAagBrAGwAbQBuAG8AcABxAHIAdAB2AHkAfwCKAJ8A",
"yQAeAccBHgPVBVULexYWLelShGmqdCp64Xw4fuF+Nn9gf3V/gH+Gf4l/i3+Nf45/j3+Qf5F/kn+T",
"f5R/lX+Wf5d/mH+Zf5p/m3+cf51/nn+ff6B/oX+if6N/pH+lf6Z/p3+of6l/qn+rf6x/rX+uf69/",
"sH+xf7J/tH+1f7Z/t3+4f7l/un+7f7x/vX++f79/wH/Bf8J/w3/Ef8V/xn/Hf8h/yX/Kf8t/zH/N",
"f85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Zf9p/23/cf91/3n/ff+B/4X/if+N/5H/lf+Z/53/of+l/",
"6n/rf+x/7X/uf+9/8H/xf/J/83/0f/V/9n/3f/h/+X/6f/t//H/9f/5//38AgABBsjcLggQBAAIA",
"AwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAQABEAEgATABQAFQAWABcAGAAZABoAGwAcAB0AHgAf",
"ACAAIQAiACMAJAAlACYAJwAoACkAKgArACwALQAuAC8AMAAxADIAMwA0ADUANgA3ADgAOQA6ADsA",
"PAA9AD4APwBAAEEAQgBDAEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBY",
"AFkAWgBbAFwAXQBeAF8AYABhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG8AcQB0AHgAfQCGAJMA",
"qADLAAMBXwH3AfACigQtB4ULrxJ9HvMxDE6CYVBtenTSeHV7D30IfqB+/H40f1d/bH95f4J/h3+L",
"f45/kH+Sf5N/lH+Vf5Z/l3+Yf5l/mn+bf5x/nX+ef59/oH+hf6J/o3+kf6V/pn+nf6h/qX+qf6t/",
"rH+tf65/r3+wf7F/sn+zf7R/tX+2f7d/uH+5f7p/u3+8f71/vn+/f8B/wX/Cf8N/xH/Ff8Z/x3/J",
"f8p/y3/Mf81/zn/Pf9B/0X/Sf9N/1H/Vf9Z/13/Yf9l/2n/bf9x/3X/ef99/4H/hf+J/43/kf+V/",
"5n/nf+h/6X/qf+t/7H/tf+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1//n//fwCAAEHC",
"OwuCBAEAAgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAb",
"ABwAHQAeAB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcA",
"OAA5ADoAOwA8AD0APgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBU",
"AFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAYgBjAGQAZQBnAGgAagBtAG8AcwB3AH0AhQCQAJ8A",
"tADSAPwANwGLAQICrAKdA/ME2gaQCWsN6RK6GtsltTVKSiRaRWUWbZRyb3YleQx7YnxTff19dH7I",
"fgN/LX9Lf2B/b396f4J/iH+Mf5B/kn+Vf5d/mH+af5t/nH+df55/n3+gf6F/on+jf6R/pX+mf6d/",
"qH+pf6p/q3+sf61/rn+vf7B/sX+yf7N/tH+1f7Z/t3+4f7l/un+7f7x/vX++f79/wH/Bf8J/w3/E",
"f8V/xn/Hf8h/yX/Kf8t/zH/Nf85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Zf9p/23/cf91/3n/ff+B/",
"4X/if+N/5H/lf+Z/6H/pf+p/63/sf+1/7n/vf/B/8X/yf/N/9H/1f/Z/93/4f/l/+n/7f/x//X/+",
"f/9/AIAAQdI/C4IEAQACAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAX",
"ABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAvADAAMQAyADMA",
"NAA1ADYANwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQ",
"AFEAUgBTAFQAVQBWAFcAWABZAFsAXABdAF8AYABiAGQAZwBpAG0AcQB1AHsAggCLAJYApAC2AMwA",
"6QANATsBdgHCASMCnwI+AwoEDwVeBg0INQr6DIkQGRX1GnoiIyyJOHZH3FOFXQpl5mp2bwVzynXy",
"d6F58Hr1e8F8YH3cfT1+iX7EfvJ+Fn8zf0l/W39pf3R/fX+Ef4p/jn+Sf5Z/mH+bf51/n3+gf6J/",
"o3+kf6Z/p3+of6l/qn+rf6x/rX+uf69/sH+xf7J/s3+0f7V/tn+3f7h/uX+6f7t/vH+9f75/v3/A",
"f8F/wn/Df8R/xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/0X/Sf9N/1H/Vf9Z/13/Yf9l/2n/bf9x/",
"3X/ef99/4H/hf+J/43/kf+V/5n/nf+h/6X/qf+t/7H/tf+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5",
"f/p/+3/8f/1//n8AgABB4sMAC4IEAQACAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIA",
"EwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAv",
"ADAAMQAyADMANAA1ADYANwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBLAEwA",
"TQBOAFAAUQBTAFQAVgBYAFoAXABeAGEAZABoAGsAcAB1AHsAggCKAJMAnwCsALsAzQDiAPwAGgE9",
"AWgBmgHWAR0CcgLXAlAD3wOKBFYFSQZrB8UIYgpODJkOVhGZFH8YJR2wIk4pNDGgOl9Fy06xVk9d",
"2mKAZ2ZrqW5mcbFznXU6d5R4tnmpenV7IHyvfCh9jX3ifSl+ZX6XfsJ+5X4Dfx1/Mn9Ef1N/YH9s",
"f3V/fX+Ef4p/j3+Uf5d/m3+ef6F/o3+lf6d/qX+rf6x/rn+vf7F/sn+zf7R/tn+3f7h/uX+6f7t/",
"vH+9f75/v3/Af8F/wn/Df8R/xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/0X/Sf9N/1H/Vf9Z/13/Y",
"f9l/2n/bf9x/3X/ef99/4H/hf+J/43/kf+V/5n/nf+h/6X/qf+t/7H/tf+5/73/wf/F/8n/zf/R/",
"9X/2f/d/+H/5f/p/+3/8f/1//n8AgABB8scAC4IEAQACAAMABAAFAAYABwAIAAkACgALAAwADQAO",
"AA8AEAARABIAEwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoA",
"KwAsAC0ALgAvADAAMQAyADQANQA2ADcAOAA5ADsAPAA9AD8AQABBAEMARQBGAEgASgBMAE4AUABT",
"AFUAWABbAF8AYgBnAGsAcAB1AHsAggCKAJIAmwCmALEAvgDNAN4A8AAFAR0BNwFVAXcBnQHJAfkB",
"MQJvArYCBQNgA8YDOgS9BFEF+QW3Bo4HggiWCc8KMQzDDYoPjRHUE2kWVhmnHGggqiR8KfIuIzUm",
"PNlD3EoNUYNWVVuXX1hjqWaWaStscm51cDxyznMwdWl2fXdxeEh5BnquekJ7xXs5fJ98+nxJfZB9",
"zn0GfjZ+Yn6Ifqp+yH7ifvp+D38hfzJ/QX9Of1l/ZH9tf3V/fX+Ef4p/j3+Uf5h/nX+gf6R/p3+q",
"f6x/r3+xf7N/tX+3f7l/un+8f75/v3/Af8J/w3/Ef8Z/x3/If8l/yn/Lf81/zn/Pf9B/0X/Sf9N/",
"1H/Vf9Z/13/Yf9l/2n/bf9x/3X/ef99/4H/hf+J/43/kf+V/5n/nf+h/6X/qf+t/7H/tf+5/73/w",
"f/F/8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1//n8AgABBgswAC4IEAQACAAMABAAFAAYABwAIAAkA",
"CgALAAwADQAOAA8AEAARABIAFAAVABYAFwAYABkAGgAbAB0AHgAfACAAIQAjACQAJQAnACgAKQAr",
"ACwALgAwADEAMwA1ADcAOQA7AD0APwBBAEQARgBJAEwATwBSAFYAWQBdAGIAZgBrAHAAdgB8AIIA",
"iQCRAJkAogCrALYAwQDNANoA6AD4AAkBGwEvAUUBXAF2AZIBsAHRAfUBHQJIAnYCqQLhAh4DYAOo",
"A/cDTQSrBBEFgQX7BYAGEQewB10IGgnpCcsKwQvODPQNNQ+TEBIStBN8FW8XkBniG2weMiE5JIgn",
"JCsXL2YzHDhAPb9C40eZTOhQ21R3WMZbzV6TYR1kb2aQaINqS2ztbWxvynALcjFzPnQ0dRZ25Xai",
"d0947nh/eQR6fnruelR7snsIfFd8n3zhfB59Vn2Jfbd94n0Kfi5+T35tfol+o366ftB+5H72fgd/",
"F38lfzJ/Pn9Jf1R/XX9mf25/dn99f4N/iX+Pf5R/mX+df6J/pn+pf61/sH+zf7Z/uX+7f75/wH/C",
"f8R/xn/If8p/zH/Of89/0X/Tf9R/1n/Xf9h/2n/bf9x/3n/ff+B/4X/if+R/5X/mf+d/6H/pf+p/",
"63/tf+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1//n8AgABBktAAC4cEBgAHAAkACgAM",
"AA0ADwAQABIAEwAVABcAGAAaABwAHgAgACIAJAAmACgAKgAtAC8AMgA0ADcAOgA9AEAAQwBHAEoA",
"TgBSAFYAWgBeAGMAaABtAHIAeAB+AIUAiwCSAJoAogCqALMAvADGANAA2wDnAPMAAAEOARwBLAE8",
"AU4BYAF0AYgBnwG2Ac8B6QEFAiMCQwJlAogCrgLXAgIDLwNgA5QDygMFBEMEhQTLBBUFZQW5BRMG",
"cgbYBkQHtwcyCLQIPgnSCW4KFQvHC4QMTQ0jDgcP+Q/7EA0SMhNpFLMVFBeKGBkawhuGHWcfZyGI",
"I8wlNSjGKoEtajCCM842TzoLPvRBsEUxSX1MlU9+UjlVylczWndcmF6YYHliPWTmZXVn62hMapZr",
"zWzybQRvBnD4cNxxsnJ7czh06nSRdS12wXZLd813SHi7eCd5jXnseUZ6mnrqejR7enu8e/p7NXxr",
"fJ980Hz9fCh9UX13fZp9vH3cffp9Fn4wfkl+YH53fot+n36xfsN+037jfvF+/34Mfxh/JH8vfzl/",
"Q39Mf1V/XX9lf21/dH96f4F/h3+Nf5J/l3+cf6F/pX+pf61/sX+1f7h/vH+/f8J/xX/If8t/zX/Q",
"f9J/1X/Xf9l/23/df99/4X/jf+V/53/of+p/7H/tf+9/8H/yf/N/9X/2f/h/+X8AgAAAAAAFAEGk",
"1AALAQUAQbzUAAsKBgAAAAcAAAAsKwBB1NQACwECAEHk1AALCP//////////AEGo1QALAtBt",
].join("");

    function decode(inst) {
        inst.exports._initialize();
        return function (in_buf) {
            var input_offset =  inst.exports.allocate_input(in_buf.byteLength);
            var input_mem = new Uint8Array(inst.exports.memory.buffer, input_offset, in_buf.byteLength);
            input_mem.set(new Uint8Array(in_buf));


            var output = [
                "GYROFLOW IMU LOG",
                "version,1.1",
                "id,esplog",
                "orientation,)--";

const char js_wasm_decoder_1[] = R"--("tscale,0.00180",
                "gscale,0.00053263221",
                "ascale,0.00048828125",
                "t,gx,gy,gz,ax,ay,az"
            ];
            
            while(true) {
                inst.exports.decode();
                var output_mem = new Int32Array(inst.exports.memory.buffer, inst.exports.get_output_ptr(), inst.exports.get_output_size());
                if (output_mem.length == 0) { break; }
                for (let i = 0; i < output_mem.length; i += 7) {
                    output.push(output_mem.slice(i, i + 7).join(","));
                }
            }
            var output_text = output.join("\n");
            return Promise.resolve(output_text);
        };
    }

    function downloadText(text, name) {
        var link = document.createElement("a");
        link.download = name;
        link.href = URL.createObjectURL(new Blob([text], {type: 'text/plain'}));
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        delete link;
    }

    function download_and_decode_log(log_url, log_name) {
        let mem = new WebAssembly.Memory({initial:1, maximum: 16000});
        fetch('data:application/octet-stream;base64,' + wasm)
            .then(response => response.arrayBuffer())
            .then(bytes => WebAssembly.instantiate(bytes, {env: {memory: mem, emscripten_notify_memory_growth:()=>{}}}))
            .then(({ instance }) => {
                return decode(instance);
            })
            .then(decoder => {
                fetch(log_url)
                    .then(response => response.arrayBuffer())
                    .then(decoder)
                    .then(text => downloadText(text, log_name));
            });
    }
</script>)--";

const char html_calibration[] = R"--(
<!doctype html>
<html lang=en>
<head>
    <meta charset=utf-8>
    <title>EspLog Calibration</title>
</head>
<body>
    <h1>Accelerometer calibration</h1>
    <div class="scene_container">
        <div class="scene">
            <div id="point_container">
            </div>
            <div class="big_circle object3d"></div>
            <div class="hor_bar object3d"></div>
            <div class="ver_bar object3d"></div>
        </div>
    </div>
    <div style="padding:0.5rem;" id="calc_result">---</div>
    <br>
    <div class="button" onclick="add_point();">Add point</div>
    <div class="button" onclick="remove_last_point();">Remove last</div>
    <div class="button" onclick="clear_points();">Clear points</div>
    <br>
    <div class="button" onclick="sphere_fit(points);">Calculate offsets</div>
    <div class="button" id="save_button" onclick="save_offsets(offsets);">Save to flash</div>
</body>
<style>
    .button {
        display: inline-block;
        border: 0.1rem solid black;
        cursor: default;
        margin: 0.2rem;
        padding: 0.3rem;
        user-select: none;
    }

    .button:hover {
        background-color: lightgray;
    }

    .button:active {
        background-color: gray;
    }

    .scene_container {
        width: 22rem;
        height: 22rem;
        position: relative;
    }

    .scene {
        width: 100%;
        height: 100%;
    }

    .object3d {
        position: absolute;
        top: 0rem;
        left: 0rem;
    }

    .big_circle {
        border-radius: 11rem;
        border: 0.1rem solid blue;

        width: 20rem;
        height: 20rem;
        top: 1rem;
        left: 1rem;
    }

    .hor_bar {
        background-color: red;

        width: 22.2rem;
        height: 0.1rem;
        transform: translate(0, 11rem) translate(0, -0.05rem);
    }

    .ver_bar {
        background-color: green;

        height: 22.2rem;
        width: 0.1rem;
        transform: translate(11rem, 0) translate(-0.05rem, 0);
    }

    .calib_point {
        background-color: red;
        border-radius: 1rem;

        width: 0.7rem;
        height: 0.7rem;
    }
</style>
<script type="text/javascript">

    function draw_points(points) {
        let scene_mult = 10;
        let scene_ofs = 1;
        let container = document.getElementById("point_container");

        container.innerHTML = '';

        for (let i = 0; i < points.length; ++i) {
            let x = scene_mult * (points[i][0] + 1) + scene_ofs;
            let y = scene_mult * (points[i][1] + 1) + scene_ofs;
            let z = scene_mult * (points[i][2]);
            let elem = document.createElement("div");
            elem.classList = "calib_point object3d";
            elem.style.transform = `translate3d(${x}rem,${y}rem, ${z}rem) translate3d(-0.35rem, -0.35rem, 0)`;

            container.appendChild(elem);
        }
    }

    let points = [];
    let offsets = [0,0,0];

    function add_point() {
        let xhr = new XMLHttpRequest();
        xhr.responseType = 'json';
        xhr.open('POST', '/calibration');
        xhr.send("get_acceleration");
        xhr.timeout = 2000;
        xhr.onload = function () {
            points.push(xhr.response.acceleration);
            draw_points(points);
            console.log(points);
        };
    }

    function save_offsets(xyz) {
        let btn = document.getElementById("save_button");
        btn.style.color = "red";
        let xhr = new XMLHttpRequest();
        xhr.responseType = 'json';
        xhr.open('POST', '/calibration');
        xhr.send(`set_offsets_ug/${-Math.round(xyz[0] * 1e6)}/${-Math.round(xyz[1] * 1e6)}/${-Math.round(xyz[2] * 1e6)}`);
        xhr.timeout = 2000;
        xhr.onload = function () {
            btn.style.color = "black";
        };
    }

    function clear_points() {
        points = [];
        draw_points(points);
    }

    function remove_last_point() {
        points.pop();
        draw_points(points);
    }

    function sphere_fit(points) {
        const lr = 1e-3;
        const x = new Array(4).fill(0);
        const f = new Array(points.length).fill(0);
        for (let i = 0; i < points.length; ++i) {
            for (let j = 0; j < 3; ++j) {
                f[i] += points[i][j] * points[i][j];
            }
        }

        console.log(f);

        for (let t = 0; t < 1000000; ++t) {
            for (let i = 0; i < points.length; ++i) {
                let aa = -f[i];
                for (let k = 0; k < 3; ++k) {
                    aa += points[i][k] * x[k];
                }
                aa += x[3];
                for (let k = 0; k < 3; ++k) {
                    x[k] -= lr * 2 * aa * points[i][k];
                }
                x[3] -= lr * 2 * aa;
            }
        }

        rad = Math.sqrt(x[0] * x[0] / 4 + x[1] * x[1] / 4 + x[2] * x[2] / 4 + x[3]);
        cx = x[0] / 2;
        cy = x[1] / 2;
        cz = x[2] / 2;

        let result_text = `X = ${cx.toFixed(4)}g, Y = ${cy.toFixed(4)}g, Z = ${cz.toFixed(4)}g, radius = ${rad.toFixed(4)}`;
        document.getElementById("calc_result").innerText = result_text;

        offsets = [cx, cy, cz];

        return offsets;
    }
</script>
</html>
)--";

}  // namespace