// SPDX-License-Identifier: LGPL-2.1-or-later

namespace {
const char html_prefix[] = R"--(
<!doctype html>
<html lang=en>

<head>
    <meta charset=utf-8>
    <title>EspLog</title>
</head>
)--";

constexpr char html_suffix[] = "</html>";

const char html_body[] = R"--(
    <body>
    <h1>EspLog</h1>
    <div class="container">
    <div class="column ">
        <div class="center button_cloumn" style="max-width: 33rem;">
            <svg class="rec_btn command_btn" viewBox="0 0 24 24" onclick="post_command('command=record')" x="0px"
                y="0px" width="24" height="24">
                <circle cx="12" cy="12" r="4" fill="#ff0000" />
            </svg>
            <svg class="stop_btn command_btn" viewBox="0 0 24 24" onclick="post_command('command=stop')" x="0px" y="0px"
                width="24" height="24">
                <path d="M 8 8 L 16 8 L 16 16 L 8 16 L 8 8" fill="#000000" />
            </svg>
            <svg class="calibrate_btn command_btn" viewBox="0 0 24 24" onclick="post_command('command=calibrate')"
                x="0px" y="0px" width="24" height="24">
                <circle cx="12" cy="12" r="4" stroke="#42ab05" stroke-width="1" fill="#00000000" />
            </svg>
        </div>
    </div>
    <div class="column">
        <div class="center status_column" style="max-width: 33rem;">
            <div id="network_activity"></div>
            <div id="status_table">
                Loading...
            </div>
        </div>
    </div>
    <div class="column">
        <div class="center download_column" style="max-width: 33rem;min-height:1rem;">
             <div id="files_table">
                Loading...
            </div>
        </div>
    </div>
    </div>
</body>)--";

const char html_stylesheet[] = R"--(
<style>
    .rec_btn {
        background-color: #ff99c4;
    }

    .stop_btn {
        background-color: #ffe499;
    }

    .calibrate_btn {
        background-color: #a7d6fc;
    }

    .command_btn {
        height: auto;
        float: left;
        width: 33.33%;
        padding: 0;
        margin: 0;
    }

    .command_btn:active {
        background-color: #505050;
    }

    .cmd_btns:after {
        content: "";
        display: table;
        clear: both;
    }
    .container {
        display: flex;
        flex-wrap: wrap;
    }

    .button_cloumn {
        background-color: aliceblue;
    }

    .center {
        margin-left: auto;
    margin-right: auto;
    }

    .status_column {
        background-color:bisque;
    }

    .download_column {
        background-color: cornsilk;
    }
    .column {
        flex-grow: 1;
        flex-basis: 33%;
        padding-left: .1rem;
        padding-right: .1rem;
    }

    @media screen and (max-width: 67rem) {
        .column {
            flex-basis: 100%;
        }
    }

    .status_table {
        font-size: 1.2rem;
        font-style: bold;
    }

    .status_table_name_cell {
        width: 18rem;
    }

    .status_value_table_cell {
        padding-left: 2rem;
    }

    .download_table {
        font-size: 2rem;
    }

    .download_table_name_cell {
        width: 8rem;
    }

    .delete_btn {
        border: none;
        padding: 0 0 0 0;
    }

    .delete_btn:active {
        background-color: #505050;
    }

    .download_table_mid_cell {
        padding-left: 1rem;
        padding-right: 1rem;
    }

    #network_activity {
        width: 100%;
        height: 0.5rem;
    }
</style>
)--";

const char settings_style[] = R"--(
    <style>
    .setting_name {
        font-weight: bold;
    }

    .apply_btn {
        background-color: lightgreen;
        font-weight: bold;
    }

    .apply_btn:active {
        background-color: gray;
    }

    .cell {
        padding-left: 0.5em;
        padding-right: 0.5em;
    }
    </style>
)--";

const char js_settings[] = R"--(
    <script type="text/javascript">
    function apply_setting(s) {
        let elem = document.getElementById(s);
        let btn_elem = document.getElementById(s + "__btn");
        btn_elem.style.color="red";
        let xhr = new XMLHttpRequest();
        xhr.open('POST', '/settings');
        xhr.onload = function() {
            btn_elem.style.color="black";
        };
        xhr.send(s + "=" + elem.value);
        xhr.timeout = 10000;
    }
    </script>
)--";

const char js_xhr_status_updater[] = R"--(
<script type="text/javascript">
    var ind_state = false;
    var indicate = function() {
        var elem = document.getElementById("network_activity");
        ind_state = !ind_state;
        if (ind_state) {
            elem.style.backgroundColor ="orange";
        } else {
            elem.style.backgroundColor ="black";
        }
    };
    var update = function(path, element, interval, timeout, indicate) {
        let controller = new AbortController();
        let restarted = false;
        function restart(t) {
            if (!restarted) {
                restarted = true;
                setTimeout(()=>{update(path, element, interval, timeout, indicate);}, t);
            }
        }
        let to = setTimeout(()=>{ controller.abort(); }, timeout);
        fetch(path, {signal: controller.signal}).then((resp)=>{
            resp.text().then((text)=>{ 
                clearTimeout(to); 
                document.getElementById(element).innerHTML = text; 
                indicate(); 
                restart(interval); 
            }, (error) => { clearTimeout(to); restart(1000); });
        }, (error) => { clearTimeout(to); restart(1000); });
    };
    function make_updater(path, element, interval, timeout, indicate) {
        
        var xhr = new XMLHttpRequest();
        var do_request = function() {
            xhr.open('GET', path);
            xhr.timeout = timeout;
            xhr.send();
        }
        xhr.onload = function() {
            setTimeout(do_request, interval);
            indicate();
            document.getElementById(element).innerHTML = xhr.responseText;
        };
        xhr.onerror = function() {
            setTimeout(do_request, 1000);
        };
        xhr.ontimeout = xhr.onerror;
        do_request();
    }
    var status_last_update = (new Date()).getTime();
    var files_last_update = (new Date()).getTime();
    update( '/status', 'status_table', 500, 1000, ()=>{
        indicate();
        status_last_update = (new Date()).getTime();});
    update( '/files', 'files_table', 1000, 1000,  ()=>{
        indicate();
        files_last_update = (new Date()).getTime();});

    setInterval(()=>{ 
        let activity_div = document.getElementById("network_activity");
        if ((new Date()).getTime() - status_last_update > 2000) {
            activity_div.style.backgroundColor = "red";
        }
        if ((new Date()).getTime() - files_last_update > 2000) {
            activity_div.style.backgroundColor = "red";
        }
    }, 1000);

    function post_command(command) {
        let xhr = new XMLHttpRequest();
        xhr.open('POST', '/');
        xhr.send(command);
        xhr.timeout = 10000;
    }
</script>)--";

const char html_update_uploader[] = R"--(
    <div>
        <p style="font-weight:bold; color:red; font-size:1.2em;">WARNING: make sure you select the correct firmware,
            there is NO verification and NO integrity checking!</p>
        <p style="font-weight:bold">Update firmware</p>
        <input id="file_input" type="file">
        <button id="upload_button" type="button" onclick="upload()">Upload</button>
        <div id="upload_log"></div>
    </div>
)--";

const char js_update_uploader[] = R"--(
    <script>
    function upload() {
        let fileInput = document.getElementById("file_input").files;
        let file = fileInput[0];
        let xhttp = new XMLHttpRequest();
        let log_elem = document.getElementById("upload_log");
        log_elem.innerHTML = "";
        let line = document.createElement("p");
        line.innerText = "Starting upload!";
        line.style.color = "green";
        log_elem.appendChild(line);
        
        xhttp.timeout = 40000;
        xhttp.onreadystatechange = function () {
            if (xhttp.readyState == 4) {
                if (xhttp.status == 200) {
                    let line = document.createElement("p");
                    line.innerText = "Upload done, update should start automatically. This will take some time. Please, wait for more than 30 seconds and then power-cycle the device";
                    line.style.color = "green";
                    log_elem.appendChild(line);
                } else {
                    let line = document.createElement("p");
                    line.innerText = "Update failed. Wait around 30 seconds, reboot the device and try again.";
                    line.style.color = "red";
                    log_elem.appendChild(line);
                }
            }
        };
        xhttp.open("POST", "/update", true);
        xhttp.send(file);
    }
</script>
)--";

const char js_wasm_decoder_0[] = R"--(<script type="text/javascript">
var wasm = [
   "AGFzbQEAAAABehNgAX8Bf2ACf38Bf2ABfwBgAn9/AGAAAX9gA39/fwF/YAN/f38AYAR/f39/AGAA",
"AGAFf39/f38AYAZ/f39/f38AYAR/f39/AX9gBn98f39/fwF/YAV/f39/fwF/YAJ/fAF/YAF/AXxg",
"A39+fwF+YAJ8fwF8YAJ+fwF/AicBA2Vudh9lbXNjcmlwdGVuX25vdGlmeV9tZW1vcnlfZ3Jvd3Ro",
"AAIDgwGBAQgAAgICAgIAAAIICAQBDQACAgAAAAQEBAQDBg4LDwICAQABAgABAAEBAQAAAQEBAgIC",
"AAUDAwAACwMCAQEAAgABAwEABwMDAQEBAQEEBAEEBQMCAQEBAQADBggFBwQQBgAAEQsGAAYSCQwD",
"AQAAAgIFBQYHBwcGCQkKCgAABAIAAAQFAXABGxsFBQEBAYAgBggBfwFBoNsBCwetAQsGbWVtb3J5",
"AgAOYWxsb2NhdGVfaW5wdXQAEw9nZXRfb3V0cHV0X3NpemUAFg5nZXRfb3V0cHV0X3B0cgAYBmRl",
"Y29kZQAZGV9faW5kaXJlY3RfZnVuY3Rpb25fdGFibGUBAAtfaW5pdGlhbGl6ZQBbEF9fZXJybm9f",
"bG9jYXRpb24AXglzdGFja1NhdmUAfgxzdGFja1Jlc3RvcmUAfwpzdGFja0FsbG9jAIABCSABAEEB",
"CxoDChEBMzRfamsVFXAEBHJ7eXRwenh1cH1wfAqm0AGBAVYBAX9BjNUAEAIaQZjVABACGiMAQRBr",
"IgAkAEGo1QAgAEEIakEBEA4oAgBBAEEAQQAQDxogAEEQaiQAQbjVABAQGkGU1wBBpNYANgIAQczW",
"AEEqNgIACywBAX8jAEEQayIBJAAgAEIANwIAIAFBADYCDCAAQQhqEEAaIAFBEGokACAACwgAQYzV",
"ABAFCwMAAQspAQF/IAAQBiAAKAIABEAgABAHIAAQCBogACgCACEBIAAQCRogARBvCwspACAAKAIA",
"GiAAKAIAIAAQCWoaIAAoAgAgABAUahogACgCACAAEAlqGgsLACAAIAAoAgAQNgsHACAAQQhqCw8A",
"IAAQCCgCACAAKAIAawsnABALQZjVACgCAARAEAxBmNUAEAgaQZjVACgCACEAEA0aIAAQbwsLNABB",
"mNUAKAIAGkGY1QAoAgAQDUECdGoaQZjVACgCABAXQQJ0ahpBmNUAKAIAEA1BAnRqGgs6AQJ/QZjV",
"ACgCACEBQZzVACgCACEAA0AgACABRwRAQZjVABAIGiAAQQRrIQAMAQsLQZzVACABNgIACxYAQZjV",
"ABAIKAIAQZjVACgCAGtBAnULDgAgACABQRt0NgIAIAALIAAgACAENgIMIAAgAzYCCCAAIAI2AgQg",
"ACABNgIAIAALbwEBfyAAQQEQDiIAQQRqQQAQDhogAEEIakEAEA4aIABBDGpBABAOGiAAQRBqQQAQ",
"DiIBQQRqQQAQDhogAUEIakEAEA4aIABBFjoAHCAAQYACNgIgIABBJGpBfxAOGiAAQQA2AiggAEEs",
"ahACGiAACwgAQbjVABASCwkAIABBLGoQBQujCAEIfyMAQUBqIgUkAAJAIABBjNUAEBQiAUsEQCMA",
"QSBrIgckAAJAIAAgAWsiBkGM1QAQCCgCAEGQ1QAoAgBrTQRAIwBBEGsiACQAIABBjNUANgIAIABB",
"kNUAKAIAIgE2AgQgACABIAZqNgIIIAAiASgCBCEAIAEoAgghAgNAIAAgAkYEQCABEFMgAUEQaiQA",
"BUGM1QAQCCAAEFkgASAAQQFqIgA2AgQMAQsLDAELQYzVABAIIQggB0EIaiECAn9BjNUAEBQgBmoh",
"BCMAQRBrIgEkACABIAQ2AgwjAEEQayIDJABBjNUAEAgaIANBfzYCDCADQf////8HNgIIIANBDGog",
"A0EIahBBKAIAIQAgA0EQaiQAIAAgBE8EQEGM1QAQCSIDIABBAXZJBEAgASADQQF0NgIIIAFBCGog",
"AUEMahBUKAIAIQALIAFBEGokACAADAELAAshAUGM1QAQFCEEQQAhACMAQRBrIgMkACADQQA2Agwg",
"AkEMaiAIEEIgAQRAIAIoAhAaIAEQbiEACyACIAA2AgAgAiAAIARqIgQ2AgggAiAENgIEIAIQRCAA",
"IAFqNgIAIANBEGokACMAQRBrIgEkACABIAIoAgg2AgAgAigCCCEAIAEgAkEIajYCCCABIAAgBmo2",
"AgQgASgCACEAA0AgASgCBCAARwRAIAIoAhAgASgCABBZIAEgASgCAEEBaiIANgIADAELCyABKAII",
"IAEoAgA2AgAgAUEQaiQAQYzVABAGQYzVABAIQYzVACgCAEGQ1QAoAgAgAkEEaiIAEEVBjNUAIAAQ",
"RkGQ1QAgAkEIahBGQYzVABAIIAIQRBBGIAIgAigCBDYCAEGM1QAQFBpBjNUAKAIAGkGM1QAoAgBB",
"jNUAEAlqGkGM1QAoAgBBjNUAEAlqGkGM1QAoAgAaIAIoAgQhAANAIAAgAigCCEcEQCACKAIQGiAC",
"IAIoAghBAWs2AggMAQsLIAIoAgAEQCACKAIQGiACKAIAIQAgAhBEKAIAIAIoAgBrGiAAEG8LCyAH",
"QSBqJAAMAQsgACABSQRAQYzVACgCACAAaiEAQYzVABAUIQFBjNUAIAAQNkGM1QAgARA1CwtB9NUA",
"QQA2AgBB8NUAQQA2AgBBqNUAIAUgBUE4akEBEA4oAgBBAEEAQQAQDyIAKQIANwIAQbDVACAAKQII",
"NwIAQbjVACAFEBAiAkEsEFxBLGoiASIAKAIABEAgABAUIQMgABAHIAAgAxA1IAAQCBogACgCACED",
"IAAQCRogAxBvIAAQCEEANgIAIABCADcCAAsgAkEsaiIAEAgaIAEQCBogASAAKAIANgIAIAEgACgC",
"BDYCBCAAEAgoAgAhAyABEAggAzYCACAAEAhBADYCACAAQgA3AgAgAhASQYzVACgCACEAIAVBQGsk",
"ACAACw0AIAAoAgQgACgCAGsLBAAgAAsEABAXCxQAQZzVACgCAEGY1QAoAgBrQQJ1CwkAQZjVACgC",
"AAvbFwIWfwF8IwBB8ABrIgQkABAXGhAMQZjVACgCABpBmNUAKAIAEA1BAnRqGkGY1QAoAgAaQZjV",
"ACgCABAXQQJ0ahogBEEgaiENIARBGGpBBHIhDiAEQUBrIQ8gBEE4akEEciEQAkACQANAQfTVACgC",
"AEGM1QAQFE8NAhAXQYAISw0CIARB2ABqIQlBjNUAKAIAQfTVACgCAGohCEGM1QAQFEH01QAoAgBr",
"IQFBACELIwBB4ABrIgIkACACIAgtAAAiETYCXAJAIAFBBU0EQCAJECAMAQsgCC0AASIAQQV2IRIg",
"AkHYAGogAEEfcRAhIQogAiAIQQJqNgJQIAIoAlAiACgAACEDIAIgAEEEajYCUCACIAM2AlQgAkFA",
"axACIgYhAEHY1QAoAgAhAyMAQSBrIgUkAAJAAkAgABA3IANJBEAgABA4IANJDQEgABAIIQcgACAF",
"QQhqIAMgABAiIAcQOSIAEDogABA7CyAFQSBqJAAMAQsACyABIAhqIRMgAUEATCEUAkADQCAGECJB",
"2NUAKAIASQRAQQAhBSACQQA6ADogAkEAOwE4A0AgBUEDRwRAAkAgFA0AIBMgAigCUGtBA0oNACAJ",
"ECAMBQsgAkE4aiAFagJ/IAIoAlRB//8BcSEHQf9+IQNBgQEhAQNAIAEgASADQQFqRg0BGiAKIAEg",
"A2pBAm0iABAjIAdKBEAgACEBDAELIAogACIDQQFqECMgB0wNAAsgAwsiAToAACAKIAEQIyEAIAog",
"AUEBahAjIABrIQMgAigCVCIHQf//AXEgAGsgB0EPdiADbGoiA0H///8DTQRAIAIoAlAhAANAIAAt",
"AAAhByAAQQFqIQAgByADQQh0ciIDQYCAgARJDQALIAIgADYCUAsgAiADNgJUIAVBAWohBSABIAtq",
"IQsMAQsLIAIgAi0AOjoABiACIAIvATg7AQQgAkEoaiIAIAIsAAQgEUEYdEEYdSIBdBAlIAIsAAUg",
"AXQQJSACLAAGIAF0ECUQHRpByNUAIAAQPBpBzNUAIABBBGoQPBpB0NUAIABBCGoQPBpBASEAAkAg",
"Ai0AOCIBIAFBGHRBH3UiAXMgAWtB/wFxQf8ARg0AIAItADkiASABQRh0QR91IgFzIAFrQf8BcUH/",
"AEYNACACLQA6IgAgAEEYdEEfdSIAcyAAa0H/AXFB/wBGIQALIAANASMAQUBqIgAkACACQQhqIgNC",
"ADcCACADQgA3AgggAEHI1QBByNUAECg2AjAgAEHM1QBBzNUAECg2AiggACAAQTBqIABBKGoQKTYC",
"ECAAQdDVAEHQ1QAQKDYCICAAIABBEGoiASAAQSBqECk2AjgCQCAAQThqIAFBABAOED0EQCAAIAAo",
"AjgQLDYCMCAAIABBMGoiBSAAQRBqIgFEAAAAAAAA4D8QHBAoIgcQPjYCECAAIAEgBRAvNgIoIAMg",
"AQJ/IwBBEGsiASQAIAEgBzYCCCABEE42AgAgASABQQhqECkQPiEFIAFBEGokACAFC0HI1QAgAEEo",
"aiIBEChBzNUAIAEQKEHQ1QAgARAoEA8iASkCADcCAAwBCyAAQYCAgCA2AjAgAEEIakQAAAAAAADw",
"PxAcIQVByNUAIABBMGoiARAoIQdBzNUAIAEQKCEMQdDVACABECghASADIABBEGogBSgCACAHIAwg",
"ARAPIgEpAgA3AgALIAMgASkCCDcCCCAAQUBrJAAgAkEYaiIBQbjVACADEBsjAEEQayIDJAAjAEEw",
"ayIAJAAgACABIAEQKDYCGCAAIAFBBGoiBSAFECg2AhAgACAAQRhqIABBEGoQKTYCICAAIAFBCGoi",
"ByAHECg2AgggACAAQSBqIABBCGoQKTYCKCAAIAFBDGoiDCAMECg2AgAgAEEoaiAAECkQLCEVIABB",
"MGokACADIBU2AgggAkEoaiABIANBCGoiABAvIAUgABAvIAcgABAvIAwgABAvEA8aIANBEGokAEHA",
"1QAgAikDMDcCAEG41QAgAikDKDcCAAJAIAYoAgQgBhAIKAIARwRAIwBBEGsiASQAIAEgBkEBEFEh",
"ACAGEAggACgCBBBSIAAgACgCBEEQajYCBCAAEFMgAUEQaiQADAELIwBBIGsiAyQAIAYQCCIHIANB",
"CGoCfyAGECJBAWohBSMAQRBrIgAkACAAIAU2AgwgBSAGEDgiAU0EQCAGEDciBSABQQF2SQRAIAAg",
"BUEBdDYCCCAAQQhqIABBDGoQVCgCACEBCyAAQRBqJAAgAQwBCwALIAYQIiAHEDkiACgCCBBSIAAg",
"ACgCCEEQajYCCCAGIAAQOiAAEDsgA0EgaiQACwwBCwsgC0EHcSASRwRAIAkQIAwBCyACIAIoAlAg",
"CGs2AiggCSACQShqEFUiBUEEaiEAIwBBEGsiAyQAIABCADcCACADQQA2AgwgBhAIGiAAQQhqEEAa",
"IAYQIiIBBEAgABA4IAFJBEAACyAAIAAQCCABEEMiCDYCACAAIAg2AgQgABAIIAggAUEEdGo2AgAg",
"AEEAEEcgBigCACEIIAYoAgQhCyMAQRBrIgokACAKIAAgARBRIQEgABAIGiALIAhrIgBBAEoEQCAB",
"KAIEIAggABBcGiABIAEoAgQgAGo2AgQLIAEQUyAKQRBqJAALIANBEGokACAFQRBqIAJB3ABqEFUa",
"CyAGECQLIAJB4ABqJABBpNUALQAARQRAIAkoAgAiAEUNAkH01QBB9NUAKAIAIABqNgIAIAQgCSgC",
"BBAlNgJQIAQgCSgCCBAlNgJIA0AgBEHQAGogBEHIAGoQJkEBcwRAIARBGGoiCCAEKAJQIgMQGiAE",
"QShqIgEgCEGo1QAQGyAEQThqIQojAEEwayIAJAAgACABQQRqIgIgAhAoNgIYIAAgAUEIaiIGIAYQ",
"KDYCECAAIABBGGogAEEQahApNgIgIAAgAUEMaiIJIAkQKDYCCCAAIABBIGoiBSAAQQhqECk2AigC",
"QCAAQShqIAVEAAAAAAAAAAAQHBAqBEAgCiACECsgBhArIAkQKxAdGgwBCyAAIAAoAigQLCIFNgIg",
"IABBEGpBAhAOIQsgAAJ/IAEgAEEAEA4QLQRAIABBIGoQJyABECcQLgwBCyAFIAEoAgAQLgs2Aggg",
"ACALIABBCGoQKDYCGCAAIABBGGogAEEgahAvNgIQIAogAiAAQRBqIgIQKCAGIAIQKCAJIAIQKBAd",
"GgsgAEEwaiQAIAEgAxAaIARBCGpBAEEAIAREAAAAAAAA8L8QHCgCABAdIQIjAEHQAGsiACQAIABB",
"MGoiBiABIABBIGogAEEYakEAEA4oAgAgAigCACACKAIEIAIoAggQDxAbIABBCGoiAiABEBogAEFA",
"ayAGIAIQGyAIIAAoAkQgACgCSCAAKAJMEB0aIABB0ABqJABBqNUAIAMpAgA3AgBBsNUAIAMpAgg3",
"AgBB8NUAQfDVACgCAAR/AkBBnNUAKAIAQZjVABAIKAIARwRAQfDVABAwDAELQfDVABAxCyAEAn8g",
"BEE4ahAeRM2/lLO71C9BoiIWmUQAAAAAAADgQWMEQCAWqgwBC0GAgICAeAs2AiggBEEoahAfIAQC",
"fyAQEB5Ezb+Us7vUL0GiIhaZRAAAAAAAAOBBYwRAIBaqDAELQYCAgIB4CzYCKCAEQShqEB8gBAJ/",
"IA8QHkTNv5Szu9QvQaIiFplEAAAAAAAA4EFjBEAgFqoMAQtBgICAgHgLNgIoIARBKGoQHyAEAn8g",
"BEEYahAeRAAAAAAAiMNAoiIWmUQAAAAAAADgQWMEQCAWqgwBC0GAgICAeAs2AiggBEEoahAfIAQC",
"fyAOEB5EAAAAAACIw0CiIhaZRAAAAAAAAOBBYwRAIBaqDAELQYCAgIB4CzYCKCAEQShqEB8gBAJ/",
"IA0QHkQAAAAAAIjDQKIiFplEAAAAAAAA4EFjBEAgFqoMAQtBgICAgHgLNgIoIARBKGoQH0Hw1QAo",
"AgAFQQALQQFqNgIAIAQgBCgCUEEQajYCUAwBBSAEQdgAahAyDAMLAAsACwsgBEHYAGoQMgwBCyAE",
"QdgAahAyCyAEQfAAaiQAQQALIQAgACABKAIAIAFBBGoQJyABQQhqECcgAUEMahAnEA8aC+wDAQl/",
"IAAgASkCADcCACAAIAEpAgg3AggjAEHQAWsiASQAIAEgACACECg2AqgBIAEgAEEEaiIEIAJBBGoi",
"BRAoNgKgASABIAFBqAFqIAFBoAFqEEs2ArABIAEgAEEIaiIDIAJBCGoiBhAoNgKYASABIAFBsAFq",
"IAFBmAFqEEs2ArgBIAEgAEEMaiIHIAJBDGoiCBAoNgKQASABQbgBaiABQZABahBLIQkgASAAIAUQ",
"KDYCeCABIAQgAhAoNgJwIAEgAUH4AGogAUHwAGoQKTYCgAEgASADIAgQKDYCaCABIAFBgAFqIAFB",
"6ABqECk2AogBIAEgByAGECg2AmAgAUGIAWogAUHgAGoQSyEKIAEgACAGECg2AkggASAEIAgQKDYC",
"QCABIAFByABqIAFBQGsQSzYCUCABIAMgAhAoNgI4IAEgAUHQAGogAUE4ahApNgJYIAEgByAFECg2",
"AjAgAUHYAGogAUEwahApIQsgASAAIAgQKDYCGCABIAQgBhAoNgIQIAEgAUEYaiABQRBqECk2AiAg",
"ASADIAUQKDYCCCABIAFBIGogAUEIahBLNgIoIAEgByACECg2AgAgACABQcABaiAJIAogCyABQShq",
"IAEQKRAPIgApAgA3AgAgAyAAKQIINwIAIAFB0AFqJAALUwAgAAJ/IAFEAAAAAAAAoEGiRAAAAAAA",
"AOA/RAAAAAAAAOC/IAFEAAAAAAAAAABmG6AiAZlEAAAAAAAA4EFjBEAgAaoMAQtBgICAgHgLNgIA",
"IAALGQAgACADNgIIIAAgAjYCBCAAIAE2AgAgAAsSACAAKAIAt0QAAAAAAABAPqILHwBBnNUAKAIA",
"QZjVABAIKAIASQRAIAAQMA8LIAAQMQsWACAAEEAiAEEEahACGiAAQRBqEEAaCwsAIAAgATYCACAA",
"CxAAIAAoAgQgACgCAGtBBHULKQEBfyABQYF/TgR/IAAoAgBBAnRBgAtqKAIAIAFBAXRqLwGAAgVB",
"AAsLUwECfyAAED8gACgCAARAIAAoAgAhAiAAKAIEIQEDQCABIAJHBEAgABAIGiABQRBrIQEMAQsL",
"IAAgAjYCBCAAEAgaIAAoAgAhASAAEDcaIAEQbwsLJAEBfyMAQRBrIgEkACABQQhqIAAQISgCACEA",
"IAFBEGokACAACw0AIAAoAgAgASgCAEYLDABBACAAKAIAaxAlC1MCAX8BfiMAQRBrIgIkACACIAAo",
"AgA2AgggAkEIaiIAIAE0AgAgADQCAH4iA0KAgIAgf0ICgSADQoCAgMAAf3w+AgAgACgCACEAIAJB",
"EGokACAACy4BAX8jAEEQayICJAAgAiAAKAIANgIIIAJBCGogARA8KAIAIQAgAkEQaiQAIAALDQAg",
"ACgCACABKAIATAsuAQF/IwBBEGsiASQAIAEgACgCADYCCCABQQhqQQIQTygCACEAIAFBEGokACAA",
"C90BAgF/BH4jAEEgayIBJAAgASAANgIYAkAgAUEYaiABQRBqQQAQDhBJBEAgAUEYaiABQQhqQQAQ",
"DhAmBEAgASgCGCEADAILIAE0AhgiAkIbhiEDIAJQBEBBywlBwwhBF0GrCBBdAAtCASACeadBP3NB",
"G2pBfnGthiECA0AgAlAEQCAEIAMgBFWtfKcQJSEADAMFIARCAYdCACACIAMgAiAEfCIFUyIAG3wh",
"BCADQgAgBSAAG30hAyACQgKHIQIMAQsACwALQawKQcMIQdEDQaYIEF0ACyABQSBqJAAgAAsNACAA",
"KAIAIAEoAgBIC/YBAQF/IwBBMGsiAiQAIAIgATYCICACIAA2AigCQAJAIAJBIGogAkEYakEAEA4Q",
"JgRAIAJBKGogAkEYakEAEA4QVkUNAiACQShqIAJBGGpBABAOED0hARBOIQAgAQ0BIAIgADYCECAC",
"QRBqECchAAwBCyACIAAgAigCIBBXIgA2AhggAkEgaiACQRBqQQAQDhAtRQ0AIAJBKGogAkEQakEA",
"EA4QSSEBEFAhACABBEAgAiAANgIIIAJBGGogAkEIahApIQAMAQsgAiAANgIIIAJBGGogAkEIahBL",
"IQALIAJBMGokACAADwtBugpBwwhBmAVBwQkQXQALawIBfwJ+IwBBEGsiAiQAIAIgACgCADYCCCAC",
"QQhqIQAgASgCACIBRQRAQccJQdsIQakBQbYJEF0ACyAAIAA0AgBCHIYgAax/IgNCAn8iBCADIARC",
"AYZ9fD4CACAAKAIAIQAgAkEQaiQAIAALWQECfyMAQRBrIgIkACACQZjVADYCACACQZzVACgCACIB",
"NgIEIAIgAUEEajYCCCACIQFBmNUAEAggASgCBCAAEFogASABKAIEQQRqNgIEIAEQUyACQRBqJAAL",
"jwQBB38jAEEgayIGJABBmNUAEAgiBwJ/IAZBCGohAQJ/EBdBAWohBSMAQRBrIgIkACACIAU2Agwj",
"AEEQayIDJABBmNUAEAgaIANB/////wM2AgwgA0H/////BzYCCCADQQxqIANBCGoQQSgCACEEIANB",
"EGokACAEIAVPBEAQDSIDIARBAXZJBEAgAiADQQF0NgIIIAJBCGogAkEMahBUKAIAIQQLIAJBEGok",
"ACAEDAELAAshAhAXIQVBACEEIwBBEGsiAyQAIANBADYCDCABQQxqIAcQQiACBEAgASgCEBogAkH/",
"////A0sEQAALIAJBAnQQbiEECyABIAQ2AgAgASAEIAVBAnRqIgU2AgggASAFNgIEIAEQRCAEIAJB",
"AnRqNgIAIANBEGokACABKAIICyAAEFogASABKAIIQQRqNgIIEAtBmNUAEAhBmNUAKAIAQZzVACgC",
"ACABQQRqIgAQRUGY1QAgABBGQZzVACABQQhqEEZBmNUAEAggARBEEEYgASABKAIENgIAEBcaQZjV",
"ACgCABpBmNUAKAIAEA1BAnRqGkGY1QAoAgAQDUECdGoaQZjVACgCABogASgCBCEAA0AgACABKAII",
"RwRAIAEoAhAaIAEgASgCCEEEazYCCAwBCwsgASgCAARAIAEoAhAaIAEoAgAhACABEEQoAgAgASgC",
"AGsaIAAQbwsgBkEgaiQACwkAIABBBGoQJAsEAEEACwQAQQALJAAgACgCABogACgCACAAEAlqGiAA",
"KAIAGiAAKAIAIAAQFGoaCysBAX8gACgCBCECA0AgASACRwRAIAAQCBogAkEBayECDAELCyAAIAE2",
"AgQLEgAgABAIKAIAIAAoAgBrQQR1C0IBAX8jAEEQayIBJAAgABAIGiABQf////8ANgIMIAFB////",
"/wc2AgggAUEMaiABQQhqEEEoAgAhACABQRBqJAAgAAtiAQJ/IwBBEGsiBSQAIAVBADYCDCAAQQxq",
"IAMQQiABBEAgACgCECABEEMhBAsgACAENgIAIAAgBCACQQR0aiICNgIIIAAgAjYCBCAAEEQgBCAB",
"QQR0ajYCACAFQRBqJAAgAAtNAQF/IAAQPyAAEAggACgCACAAKAIEIAFBBGoiAhBFIAAgAhBGIABB",
"BGogAUEIahBGIAAQCCABEEQQRiABIAEoAgQ2AgAgACAAECIQRwtVAQF/IAAoAgQhAQNAIAEgACgC",
"CEcEQCAAKAIQGiAAIAAoAghBEGs2AggMAQsLIAAoAgAEQCAAKAIQGiAAKAIAIQEgABBEKAIAIAAo",
"AgBrGiABEG8LCxQAIAAgACgCACABKAIAajYCACAACw0AIAAoAgAgASgCAEoL/QMBA38jAEHwAGsi",
"ASQAEE0hAyMAQRBrIgIkACACIAM2AgAgAiAANgIIIAIoAgBFBEBB1glBwwhBvgFBiwkQXQALIAIo",
"AgggAigCAG8QJSEAIAJBEGokACABIAA2AmggARBONgJgIAEgAUHoAGoiACABQeAAaiICEC82Amgg",
"ACACQQAQDhAtBEAgAUHoAGogAUHgAGpBBBAOEDwaC0EBIQAgAUHoAGogAUHgAGpBAhAOED0EQCAB",
"QegAaiABQeAAakECEA4QShpBfyEACyABQegAaiABQeAAakEBEA4QPQRAIAEgAUHgAGpBAhAOIAFB",
"6ABqEEs2AmgLIAEgAUHoAGoiAyADECg2AmAjAEEQayICJAAgAiADKAIANgIIIAJBCGogABBPKAIA",
"IQAgAkEQaiQAIAEgADYCUCABEFA2AkAgARBNNgIgIAEgAUEgakEFEEw2AiggARBQNgIIIAEgAUEI",
"akEDEEw2AhAgASABQeAAaiIAIAFBEGoQKDYCGCABIAFBKGogAUEYahBLNgIwIAEgACABQTBqECg2",
"AjggASABQUBrIAFBOGoQSzYCSCABIAFB0ABqIAFByABqECg2AlgjAEEQayIAJAAgACABKAJYNgII",
"IABBCGoiAiACKAIAQQJtNgIAIAIoAgAhAiAAQRBqJAAgAUHwAGokACACCzIAIAAoAgAaIAAoAgAg",
"ABA3QQR0ahogACgCACAAECJBBHRqGiAAKAIAIAAQN0EEdGoaCwsAIABBADYCACAACyMBAn8jAEEQ",
"ayICJAAgASAAEEghAyACQRBqJAAgASAAIAMbCw4AIAAQQEEEaiABECEaCxYAIAFB/////wBLBEAA",
"CyABQQR0EG4LBwAgAEEMagsnACADIAMoAgAgAiABayIAayICNgIAIABBAEoEQCACIAEgABBcGgsL",
"HAEBfyAAKAIAIQIgACABKAIANgIAIAEgAjYCAAsqACAAKAIAGiAAKAIAIAAQN0EEdGoaIAAoAgAg",
"ABA3QQR0ahogACgCABoLDQAgACgCACABKAIASQsNACAAKAIAIAEoAgBOCxQAIAAgACgCACABKAIA",
"azYCACAACy4BAX8jAEEQayICJAAgAiAAKAIANgIIIAJBCGogARBKKAIAIQAgAkEQaiQAIAALPAEB",
"fyMAQRBrIgIkACACIAAoAgA2AgggAkEIaiIAIAAoAgAgAUEbdGs2AgAgACgCACEAIAJBEGokACAA",
"CwsAQantj5IDEIEBCwsAQar7w+QAEIEBCxEAIAAgACgCACABbDYCACAACwsAQdT2h8kBEIEBCyQA",
"IAAgATYCACAAIAEoAgQiATYCBCAAIAEgAkEEdGo2AgggAAsaACABQbjVACkCADcCACABQcDVACkC",
"ADcCCAsPACAAKAIAIAAoAgQ2AgQLIwECfyMAQRBrIgIkACAAIAEQSCEDIAJBEGokACABIAAgAxsL",
"DgAgACABKAIANgIAIAALDQAgACgCACABKAIARwvbAgEBfyMAQSBrIgIkACACIAE2AhAgAiAANgIY",
"AkACQCACQRBqIAJBCGpBABAOEFYEQAJ/IAJBGGogAkEIakEAEA4QLQRAIAJBEGogAkEIakEAEA4Q",
"LQRAIAJBGGoQJyACQRBqECcQVwwCCyACIAJBGGoQJyACKAIQEFc2AgggAkEIahAnDAELIAJBEGog",
"AkEIakEAEA4QLQRAIAIgAigCGCACQRBqECcQVzYCCCACQQhqECcMAQsgAkEYaiACQQhqQQAQDhBJ",
"RQ0CIAJBEGogAkEIakEAEA4QPUUNAyACQRhqIAJBEGoQPQRAIAIQTjYCCCACIAJBEGogAkEYahAv",
"EFg2AgAgAkEIaiACEEsMAQsgAkEYaiACQRBqEC8QWAshACACQSBqJAAgAA8LQcgKQcMIQcwEQZ0I",
"EF0AC0GeCkHDCEHaBEGdCBBdAAtBkQpBwwhB2wRBnQgQXQAL1QEBAn8jAEHQAGsiASQAIAEgADYC",
"SAJAIAFByABqIAFBQGtBABAOEEkEQCABQcgAaiABQThqQQEQDhAqDQELQfIJQcMIQbgEQZAJEF0A",
"CyABQfeO/AQ2AkAgAUGOq81tNgI4IAFB0MPYPzYCMCABIAFByABqIgAgABAoNgIoIAEgAUFAayAB",
"QShqIgIQKDYCCCABIAFBCGogAUE4ahApNgIQIAEgAUEQaiACECg2AhggASABQRhqIAFBMGoQKTYC",
"ICABQSBqIAAQKCEAIAFB0ABqJAAgAAsJACABQQA6AAALDAAgASACKAIANgIACwQAEAELMwEBfyAC",
"BEAgACEDA0AgAyABLQAAOgAAIANBAWohAyABQQFqIQEgAkEBayICDQALCyAAC5YDAQJ/IwBBEGsi",
"BCQAIAQgAjYCDCAEIAM2AgggBCABNgIEIAQgADYCACMAQRBrIgIkACACIAQ2AgxBACEBIwBB0AFr",
"IgAkACAAIAQ2AswBIABBoAFqIgNBAEEoEGAgACAAKALMATYCyAECQEEAIABByAFqIABB0ABqIAMQ",
"ZEEASA0AQcTUACgCAEEATiEEQfjTACgCACEDQcDUACgCAEEATARAQfjTACADQV9xNgIACwJ/AkAC",
"QEGo1AAoAgBFBEBBqNQAQdAANgIAQZTUAEEANgIAQYjUAEIANwMAQaTUACgCACEBQaTUACAANgIA",
"DAELQYjUACgCAA0BC0F/QfjTABBhDQEaC0H40wAgAEHIAWogAEHQAGogAEGgAWoQZAshBSABBH9B",
"+NMAQQBBAEGc1AAoAgARBQAaQajUAEEANgIAQaTUACABNgIAQZTUAEEANgIAQYzUACgCABpBiNQA",
"QgA3AwBBAAUgBQsaQfjTAEH40wAoAgAgA0EgcXI2AgAgBEUNAAsgAEHQAWokACACQRBqJAAACwYA",
"QfjVAAsKACAAKAI8GkIACyEAIAIEQANAIAAgAToAACAAQQFqIQAgAkEBayICDQALCwtZAQF/IAAg",
"ACgCSCIBQQFrIAFyNgJIIAAoAgAiAUEIcQRAIAAgAUEgcjYCAEF/DwsgAEIANwIEIAAgACgCLCIB",
"NgIcIAAgATYCFCAAIAEgACgCMGo2AhBBAAsKACAAQTBrQQpJC34CAX8BfiAAvSIDQjSIp0H/D3Ei",
"AkH/D0cEfCACRQRAIAEgAEQAAAAAAAAAAGEEf0EABSAARAAAAAAAAPBDoiABEGMhACABKAIAQUBq",
"CzYCACAADwsgASACQf4HazYCACADQv////////+HgH+DQoCAgICAgIDwP4S/BSAACwuTFAITfwF+",
"QdYKIQsjAEHQAGsiBSQAIAVB1go2AkwgBUE3aiEVIAVBOGohEAJAAkACQAJAA0AgCyEKIARB////",
"/wcgDGtKDQEgBCAMaiEMAkACQAJAIAoiBC0AACIGBEADQAJAAkAgBkH/AXEiC0UEQCAEIQsMAQsg",
"C0ElRw0BIAQhBgNAIAYtAAFBJUcEQCAGIQsMAgsgBEEBaiEEIAYtAAIhByAGQQJqIgshBiAHQSVG",
"DQALCyAEIAprIgRB/////wcgDGsiFkoNByAABEAgACAKIAQQZQsgBA0GIAUgCzYCTCALQQFqIQRB",
"fyENAkAgCywAARBiRQ0AIAstAAJBJEcNACALQQNqIQQgCywAAUEwayENQQEhEQsgBSAENgJMQQAh",
"CAJAIAQsAAAiBkEgayILQR9LBEAgBCEHDAELIAQhB0EBIAt0IgtBidEEcUUNAANAIAUgBEEBaiIH",
"NgJMIAggC3IhCCAELAABIgZBIGsiC0EgTw0BIAchBEEBIAt0IgtBidEEcQ0ACwsCQCAGQSpGBEAC",
"fwJAIAcsAAEQYkUNACAHLQACQSRHDQAgBywAAUECdCADakHAAWtBCjYCACAHQQNqIQZBASERIAcs",
"AAFBA3QgAmpBgANrKAIADAELIBENBiAHQQFqIQYgAEUEQCAFIAY2AkxBACERQQAhDgwDCyABIAEo",
"AgAiBEEEajYCAEEAIREgBCgCAAshDiAFIAY2AkwgDkEATg0BQQAgDmshDiAIQYDAAHIhCAwBCyAF",
"QcwAahBmIg5BAEgNCCAFKAJMIQYLQQAhBEF/IQkCfyAGLQAAQS5HBEAgBiELQQAMAQsgBi0AAUEq",
"RgRAAn8CQCAGLAACEGJFDQAgBi0AA0EkRw0AIAYsAAJBAnQgA2pBwAFrQQo2AgAgBkEEaiELIAYs",
"AAJBA3QgAmpBgANrKAIADAELIBENBiAGQQJqIQtBACAARQ0AGiABIAEoAgAiB0EEajYCACAHKAIA",
"CyEJIAUgCzYCTCAJQX9zQR92DAELIAUgBkEBajYCTCAFQcwAahBmIQkgBSgCTCELQQELIRICQANA",
"IAQhDyALIhMsAAAiBEH7AGtBRkkNASATQQFqIQsgBCAPQTpsakH/CmotAAAiBEEBa0EISQ0ACyAF",
"IAs2AkxBHCEHAkACQCAEQRtHBEAgBEUNDCANQQBOBEAgAyANQQJ0aiAENgIAIAUgAiANQQN0aikD",
"ADcDQAwCCyAARQ0JIAVBQGsgBCABEGcMAgsgDUEATg0LC0EAIQQgAEUNCAsgCEH//3txIgYgCCAI",
"QYDAAHEbIQhBACENQYAIIRQgECEHAkACQAJAAn8CQAJAAkACQAJ/AkACQAJAAkACQAJAAkAgEywA",
"ACIEQV9xIAQgBEEPcUEDRhsgBCAPGyIEQdgAaw4hBBUVFRUVFRUVDhUPBg4ODhUGFRUVFQIFAxUV",
"CRUBFRUEAAsCQCAEQcEAaw4HDhULFQ4ODgALIARB0wBGDQkMFAsgBSkDQCEXQYAIDAULQQAhBAJA",
"AkACQAJAAkACQAJAIA9B/wFxDggAAQIDBBsFBhsLIAUoAkAgDDYCAAwaCyAFKAJAIAw2AgAMGQsg",
"BSgCQCAMrDcDAAwYCyAFKAJAIAw7AQAMFwsgBSgCQCAMOgAADBYLIAUoAkAgDDYCAAwVCyAFKAJA",
"IAysNwMADBQLIAlBCCAJQQhLGyEJIAhBCHIhCEH4ACEECyAQIQogBEEgcSEGIAUpA0AiF1BFBEAD",
"QCAKQQFrIgogF6dBD3FBkA9qLQAAIAZyOgAAIBdCD1YhDyAXQgSIIRcgDw0ACwsgCEEIcUUgBSkD",
"QFByDQMgBEEEdkGACGohFEECIQ0MAwsgECEEIAUpA0AiF1BFBEADQCAEQQFrIgQgF6dBB3FBMHI6",
"AAAgF0IHViEKIBdCA4ghFyAKDQALCyAEIQogCEEIcUUNAiAJIBAgCmsiBEEBaiAEIAlIGyEJDAIL",
"IAUpA0AiF0IAUwRAIAVCACAXfSIXNwNAQQEhDUGACAwBCyAIQYAQcQRAQQEhDUGBCAwBC0GCCEGA",
"CCAIQQFxIg0bCyEUIBcgEBBoIQoLIBJBACAJQQBIGw0PIAhB//97cSAIIBIbIQggBSkDQCIXQgBS",
"IAlyRQRAIBAiCiEHQQAhCQwNCyAJIBdQIBAgCmtqIgQgBCAJSBshCQwMCwJ/IAlB/////wcgCUH/",
"////B0kbIg8iB0EARyEIAkACQAJAIAUoAkAiBEHrCSAEGyIKIgRBA3FFIAdFcg0AA0AgBC0AAEUN",
"AiAHQQFrIgdBAEchCCAEQQFqIgRBA3FFDQEgBw0ACwsgCEUNAQsCQCAELQAARSAHQQRJckUEQANA",
"IAQoAgAiCEF/cyAIQYGChAhrcUGAgYKEeHENAiAEQQRqIQQgB0EEayIHQQNLDQALCyAHRQ0BCwNA",
"IAQgBC0AAEUNAhogBEEBaiEEIAdBAWsiBw0ACwtBAAsiBCAKayAPIAQbIgQgCmohByAJQQBOBEAg",
"BiEIIAQhCQwMCyAGIQggBCEJIActAAANDgwLCyAJBEAgBSgCQAwCC0EAIQQgAEEgIA5BACAIEGkM",
"AgsgBUEANgIMIAUgBSkDQD4CCCAFIAVBCGoiBDYCQEF/IQkgBAshBkEAIQQCQANAIAYoAgAiCkUN",
"ASAFQQRqIAoQbCIKQQBIIgcgCiAJIARrS3JFBEAgBkEEaiEGIAkgBCAKaiIESw0BDAILCyAHDQ4L",
"QT0hByAEQQBIDQwgAEEgIA4gBCAIEGkgBEUEQEEAIQQMAQtBACEHIAUoAkAhBgNAIAYoAgAiCkUN",
"ASAFQQRqIAoQbCIKIAdqIgcgBEsNASAAIAVBBGogChBlIAZBBGohBiAEIAdLDQALCyAAQSAgDiAE",
"IAhBgMAAcxBpIA4gBCAEIA5IGyEEDAkLIBJBACAJQQBIGw0JQT0hByAAIAUrA0AgDiAJIAggBEEI",
"EQwAIgRBAE4NCAwKCyAFIAUpA0A8ADdBASEJIBUhCiAGIQgMBQsgBSATNgJMDAMLIAQtAAEhBiAE",
"QQFqIQQMAAsACyAADQcgEUUNAkEBIQQDQCADIARBAnRqKAIAIgAEQCACIARBA3RqIAAgARBnQQEh",
"DCAEQQFqIgRBCkcNAQwJCwtBASEMIARBCk8NBwNAIAMgBEECdGooAgANASAEQQFqIgRBCkcNAAsM",
"BwtBHCEHDAQLIAkgByAKayIPIAkgD0obIglB/////wcgDWtKDQJBPSEHIA4gCSANaiIGIAYgDkgb",
"IgQgFkoNAyAAQSAgBCAGIAgQaSAAIBQgDRBlIABBMCAEIAYgCEGAgARzEGkgAEEwIAkgD0EAEGkg",
"ACAKIA8QZSAAQSAgBCAGIAhBgMAAcxBpDAELC0EAIQwMAwtBPSEHC0H41QAgBzYCAAtBfyEMCyAF",
"QdAAaiQAIAwLvgEBA38gAC0AAEEgcUUEQAJAIAEhAwJAIAIgACIBKAIQIgAEfyAABSABEGENASAB",
"KAIQCyABKAIUIgVrSwRAIAEgAyACIAEoAiQRBQAaDAILAkAgASgCUEEASA0AIAIhAANAIAAiBEUN",
"ASADIARBAWsiAGotAABBCkcNAAsgASADIAQgASgCJBEFACAESQ0BIAMgBGohAyACIARrIQIgASgC",
"FCEFCyAFIAMgAhBcGiABIAEoAhQgAmo2AhQLCwsLawEEfyAAKAIALAAAEGJFBEBBAA8LA0AgACgC",
"ACEDQX8hASACQcyZs+YATQRAQX8gAywAAEEwayIEIAJBCmwiAWogBEH/////ByABa0obIQELIAAg",
"A0EBajYCACABIQIgAywAARBiDQALIAILvAIAAkACQAJAAkACQAJAAkACQAJAAkACQCABQQlrDhIA",
"CAkKCAkBAgMECgkKCggJBQYHCyACIAIoAgAiAUEEajYCACAAIAEoAgA2AgAPCyACIAIoAgAiAUEE",
"ajYCACAAIAEyAQA3AwAPCyACIAIoAgAiAUEEajYCACAAIAEzAQA3AwAPCyACIAIoAgAiAUEEajYC",
"ACAAIAEwAAA3AwAPCyACIAIoAgAiAUEEajYCACAAIAExAAA3AwAPCyACIAIoAgBBB2pBeHEiAUEI",
"ajYCACAAIAErAwA5AwAPCyAAIAJBCREDAAsPCyACIAIoAgAiAUEEajYCACAAIAE0AgA3AwAPCyAC",
"IAIoAgAiAUEEajYCACAAIAE1AgA3AwAPCyACIAIoAgBBB2pBeHEiAUEIajYCACAAIAEpAwA3AwAL",
"gwECA38BfgJAIABCgICAgBBUBEAgACEFDAELA0AgAUEBayIBIAAgAEIKgCIFQgp+fadBMHI6AAAg",
"AEL/////nwFWIQIgBSEAIAINAAsLIAWnIgIEQANAIAFBAWsiASACIAJBCm4iA0EKbGtBMHI6AAAg",
"AkEJSyEEIAMhAiAEDQALCyABC2wBAX8jAEGAAmsiBSQAIARBgMAEcSACIANMckUEQCAFIAFB/wFx",
"IAIgA2siA0GAAiADQYACSSIBGxBgIAFFBEADQCAAIAVBgAIQZSADQYACayIDQf8BSw0ACwsgACAF",
"IAMQZQsgBUGAAmokAAueGAMSfwF8An4jAEGwBGsiCyQAIAtBADYCLAJAIAG9IhlCAFMEQEEBIRBB",
"igghEyABmiIBvSEZDAELIARBgBBxBEBBASEQQY0IIRMMAQtBkAhBiwggBEEBcSIQGyETIBBFIRUL",
"AkAgGUKAgICAgICA+P8Ag0KAgICAgICA+P8AUQRAIABBICACIBBBA2oiAyAEQf//e3EQaSAAIBMg",
"EBBlIABBgwlBrgkgBUEgcSIFG0GHCUGyCSAFGyABIAFiG0EDEGUgAEEgIAIgAyAEQYDAAHMQaSAD",
"IAIgAiADSBshCQwBCyALQRBqIRECQAJ/AkAgASALQSxqEGMiASABoCIBRAAAAAAAAAAAYgRAIAsg",
"CygCLCIGQQFrNgIsIAVBIHIiDkHhAEcNAQwDCyAFQSByIg5B4QBGDQIgCygCLCEKQQYgAyADQQBI",
"GwwBCyALIAZBHWsiCjYCLCABRAAAAAAAALBBoiEBQQYgAyADQQBIGwshDCALQTBqQQBBoAIgCkEA",
"SBtqIg0hBwNAIAcCfyABRAAAAAAAAPBBYyABRAAAAAAAAAAAZnEEQCABqwwBC0EACyIDNgIAIAdB",
"BGohByABIAO4oUQAAAAAZc3NQaIiAUQAAAAAAAAAAGINAAsCQCAKQQBMBEAgCiEDIAchBiANIQgM",
"AQsgDSEIIAohAwNAIANBHSADQR1IGyEDAkAgB0EEayIGIAhJDQAgA60hGkIAIRkDQCAGIBlC////",
"/w+DIAY1AgAgGoZ8IhkgGUKAlOvcA4AiGUKAlOvcA359PgIAIAZBBGsiBiAITw0ACyAZpyIGRQ0A",
"IAhBBGsiCCAGNgIACwNAIAggByIGSQRAIAZBBGsiBygCAEUNAQsLIAsgCygCLCADayIDNgIsIAYh",
"ByADQQBKDQALCyADQQBIBEAgDEEZakEJbkEBaiEPIA5B5gBGIRIDQEEAIANrIgNBCSADQQlIGyEJ",
"AkAgBiAITQRAIAgoAgAhBwwBC0GAlOvcAyAJdiEUQX8gCXRBf3MhFkEAIQMgCCEHA0AgByADIAco",
"AgAiFyAJdmo2AgAgFiAXcSAUbCEDIAdBBGoiByAGSQ0ACyAIKAIAIQcgA0UNACAGIAM2AgAgBkEE",
"aiEGCyALIAsoAiwgCWoiAzYCLCANIAggB0VBAnRqIgggEhsiByAPQQJ0aiAGIAYgB2tBAnUgD0ob",
"IQYgA0EASA0ACwtBACEDAkAgBiAITQ0AIA0gCGtBAnVBCWwhA0EKIQcgCCgCACIJQQpJDQADQCAD",
"QQFqIQMgCSAHQQpsIgdPDQALCyAMQQAgAyAOQeYARhtrIA5B5wBGIAxBAEdxayIHIAYgDWtBAnVB",
"CWxBCWtIBEBBBEGkAiAKQQBIGyALaiAHQYDIAGoiCUEJbSIPQQJ0akHQH2shCkEKIQcgCSAPQQls",
"ayIJQQdMBEADQCAHQQpsIQcgCUEBaiIJQQhHDQALCwJAIAooAgAiEiASIAduIg8gB2xrIglFIApB",
"BGoiFCAGRnENAAJAIA9BAXFFBEBEAAAAAAAAQEMhASAHQYCU69wDRyAIIApPcg0BIApBBGstAABB",
"AXFFDQELRAEAAAAAAEBDIQELRAAAAAAAAOA/RAAAAAAAAPA/RAAAAAAAAPg/IAYgFEYbRAAAAAAA",
"APg/IAkgB0EBdiIURhsgCSAUSRshGAJAIBUNACATLQAAQS1HDQAgGJohGCABmiEBCyAKIBIgCWsi",
"CTYCACABIBigIAFhDQAgCiAHIAlqIgM2AgAgA0GAlOvcA08EQANAIApBADYCACAIIApBBGsiCksE",
"QCAIQQRrIghBADYCAAsgCiAKKAIAQQFqIgM2AgAgA0H/k+vcA0sNAAsLIA0gCGtBAnVBCWwhA0EK",
"IQcgCCgCACIJQQpJDQADQCADQQFqIQMgCSAHQQpsIgdPDQALCyAKQQRqIgcgBiAGIAdLGyEGCwNA",
"IAYiByAITSIJRQRAIAdBBGsiBigCAEUNAQsLAkAgDkHnAEcEQCAEQQhxIQoMAQsgA0F/c0F/IAxB",
"ASAMGyIGIANKIANBe0pxIgobIAZqIQxBf0F+IAobIAVqIQUgBEEIcSIKDQBBdyEGAkAgCQ0AIAdB",
"BGsoAgAiDkUNAEEKIQlBACEGIA5BCnANAANAIAYiCkEBaiEGIA4gCUEKbCIJcEUNAAsgCkF/cyEG",
"CyAHIA1rQQJ1QQlsIQkgBUFfcUHGAEYEQEEAIQogDCAGIAlqQQlrIgZBACAGQQBKGyIGIAYgDEob",
"IQwMAQtBACEKIAwgAyAJaiAGakEJayIGQQAgBkEAShsiBiAGIAxKGyEMC0F/IQkgDEH9////B0H+",
"////ByAKIAxyIhIbSg0BIAwgEkEAR2pBAWohDgJAIAVBX3EiFUHGAEYEQCADQf////8HIA5rSg0D",
"IANBACADQQBKGyEGDAELIBEgAyADQR91IgZzIAZrrSAREGgiBmtBAUwEQANAIAZBAWsiBkEwOgAA",
"IBEgBmtBAkgNAAsLIAZBAmsiDyAFOgAAIAZBAWtBLUErIANBAEgbOgAAIBEgD2siBkH/////ByAO",
"a0oNAgsgBiAOaiIDIBBB/////wdzSg0BIABBICACIAMgEGoiBSAEEGkgACATIBAQZSAAQTAgAiAF",
"IARBgIAEcxBpAkACQAJAIBVBxgBGBEAgC0EQaiIGQQhyIQMgBkEJciEKIA0gCCAIIA1LGyIJIQgD",
"QCAINQIAIAoQaCEGAkAgCCAJRwRAIAYgC0EQak0NAQNAIAZBAWsiBkEwOgAAIAYgC0EQaksNAAsM",
"AQsgBiAKRw0AIAtBMDoAGCADIQYLIAAgBiAKIAZrEGUgCEEEaiIIIA1NDQALIBIEQCAAQekJQQEQ",
"ZQsgDEEATCAHIAhNcg0BA0AgCDUCACAKEGgiBiALQRBqSwRAA0AgBkEBayIGQTA6AAAgBiALQRBq",
"Sw0ACwsgACAGIAxBCSAMQQlIGxBlIAxBCWshBiAIQQRqIgggB08NAyAMQQlKIQMgBiEMIAMNAAsM",
"AgsCQCAMQQBIDQAgByAIQQRqIAcgCEsbIQkgC0EQaiIGQQhyIQMgBkEJciENIAghBwNAIA0gBzUC",
"ACANEGgiBkYEQCALQTA6ABggAyEGCwJAIAcgCEcEQCAGIAtBEGpNDQEDQCAGQQFrIgZBMDoAACAG",
"IAtBEGpLDQALDAELIAAgBkEBEGUgBkEBaiEGIAogDHJFDQAgAEHpCUEBEGULIAAgBiAMIA0gBmsi",
"BiAGIAxKGxBlIAwgBmshDCAHQQRqIgcgCU8NASAMQQBODQALCyAAQTAgDEESakESQQAQaSAAIA8g",
"ESAPaxBlDAILIAwhBgsgAEEwIAZBCWpBCUEAEGkLIABBICACIAUgBEGAwABzEGkgBSACIAIgBUgb",
"IQkMAQsgEyAFQRp0QR91QQlxaiEMAkAgA0ELSw0AQQwgA2shBkQAAAAAAAAwQCEYA0AgGEQAAAAA",
"AAAwQKIhGCAGQQFrIgYNAAsgDC0AAEEtRgRAIBggAZogGKGgmiEBDAELIAEgGKAgGKEhAQsgESAL",
"KAIsIgYgBkEfdSIGcyAGa60gERBoIgZGBEAgC0EwOgAPIAtBD2ohBgsgEEECciEKIAVBIHEhCCAL",
"KAIsIQcgBkECayINIAVBD2o6AAAgBkEBa0EtQSsgB0EASBs6AAAgBEEIcSEGIAtBEGohBwNAIAci",
"BQJ/IAGZRAAAAAAAAOBBYwRAIAGqDAELQYCAgIB4CyIHQZAPai0AACAIcjoAACAGIANBAEpyRSAB",
"IAe3oUQAAAAAAAAwQKIiAUQAAAAAAAAAAGFxIAVBAWoiByALQRBqa0EBR3JFBEAgBUEuOgABIAVB",
"AmohBwsgAUQAAAAAAAAAAGINAAtBfyEJQf3///8HIAogESANayIFaiIGayADSA0AIABBICACIAYC",
"fwJAIANFDQAgByALQRBqayIIQQJrIANODQAgA0ECagwBCyAHIAtBEGprIggLIgdqIgMgBBBpIAAg",
"DCAKEGUgAEEwIAIgAyAEQYCABHMQaSAAIAtBEGogCBBlIABBMCAHIAhrQQBBABBpIAAgDSAFEGUg",
"AEEgIAIgAyAEQYDAAHMQaSADIAIgAiADSBshCQsgC0GwBGokACAJC4kFAgZ+AX8gASABKAIAQQdq",
"QXhxIgFBEGo2AgAgAAJ8IAEpAwAhBCABKQMIIQUjAEEgayIAJAACQCAFQv///////////wCDIgNC",
"gICAgICAwIA8fSADQoCAgICAgMD/wwB9VARAIAVCBIYgBEI8iIQhAyAEQv//////////D4MiBEKB",
"gICAgICAgAhaBEAgA0KBgICAgICAgMAAfCECDAILIANCgICAgICAgIBAfSECIARCgICAgICAgIAI",
"Ug0BIAIgA0IBg3whAgwBCyAEUCADQoCAgICAgMD//wBUIANCgICAgICAwP//AFEbRQRAIAVCBIYg",
"BEI8iIRC/////////wODQoCAgICAgID8/wCEIQIMAQtCgICAgICAgPj/ACECIANC////////v//D",
"AFYNAEIAIQIgA0IwiKciAUGR9wBJDQAgBCECIAVC////////P4NCgICAgICAwACEIgMhBgJAIAFB",
"gfcAayIIQcAAcQRAIAIgCEFAaq2GIQZCACECDAELIAhFDQAgBiAIrSIHhiACQcAAIAhrrYiEIQYg",
"AiAHhiECCyAAIAI3AxAgACAGNwMYAkBBgfgAIAFrIgFBwABxBEAgAyABQUBqrYghBEIAIQMMAQsg",
"AUUNACADQcAAIAFrrYYgBCABrSICiIQhBCADIAKIIQMLIAAgBDcDACAAIAM3AwggACkDCEIEhiAA",
"KQMAIgRCPIiEIQIgACkDECAAKQMYhEIAUq0gBEL//////////w+DhCIEQoGAgICAgICACFoEQCAC",
"QgF8IQIMAQsgBEKAgICAgICAgAhSDQAgAkIBgyACfCECCyAAQSBqJAAgAiAFQoCAgICAgICAgH+D",
"hL8LOQMAC5kCACAARQRAQQAPCwJ/AkAgAAR/IAFB/wBNDQECQEGU1wAoAgAoAgBFBEAgAUGAf3FB",
"gL8DRg0DDAELIAFB/w9NBEAgACABQT9xQYABcjoAASAAIAFBBnZBwAFyOgAAQQIMBAsgAUGAQHFB",
"gMADRyABQYCwA09xRQRAIAAgAUE/cUGAAXI6AAIgACABQQx2QeABcjoAACAAIAFBBnZBP3FBgAFy",
"OgABQQMMBAsgAUGAgARrQf//P00EQCAAIAFBP3FBgAFyOgADIAAgAUESdkHwAXI6AAAgACABQQZ2",
"QT9xQYABcjoAAiAAIAFBDHZBP3FBgAFyOgABQQQMBAsLQfjVAEEZNgIAQX8FQQELDAELIAAgAToA",
"AEEBCwtvAQJ/QYjVACgCACIBIABBA2pBfHEiAmohAAJAIAJBACAAIAFNGw0AIAA/AEEQdEsEQCAA",
"PwBBEHRrQf//A2pBEHZAAEF/RgR/QQAFQQAQAEEBC0UNAQtBiNUAIAA2AgAgAQ8LQfjVAEEwNgIA",
"QX8Lly4BDH8gAEEBIAAbIQsCQANAQQAhAyMAQRBrIgwkAAJAAkACQAJAAkACQAJAAkACQAJAAkAg",
"C0H0AU0EQEGs1wAoAgAiBkEQIAtBC2pBeHEgC0ELSRsiB0EDdiICdiIBQQNxBEACQCABQX9zQQFx",
"IAJqIgJBA3QiAEHU1wBqIgEgAEHc1wBqKAIAIgMoAggiAEYEQEGs1wAgBkF+IAJ3cTYCAAwBCyAA",
"IAE2AgwgASAANgIICyADQQhqIQEgAyACQQN0IgBBA3I2AgQgACADaiIAIAAoAgRBAXI2AgQMDAsg",
"B0G01wAoAgAiCk0NASABBEACQEECIAJ0IgBBACAAa3IgASACdHEiAEEAIABrcUEBayIAIABBDHZB",
"EHEiAnYiAUEFdkEIcSIAIAJyIAEgAHYiAUECdkEEcSIAciABIAB2IgFBAXZBAnEiAHIgASAAdiIB",
"QQF2QQFxIgByIAEgAHZqIgNBA3QiAEHU1wBqIgEgAEHc1wBqKAIAIgQoAggiAEYEQEGs1wAgBkF+",
"IAN3cSIGNgIADAELIAAgATYCDCABIAA2AggLIAQgB0EDcjYCBCAEIAdqIgIgA0EDdCIAIAdrIgNB",
"AXI2AgQgACAEaiADNgIAIAoEQCAKQXhxQdTXAGohBUHA1wAoAgAhAQJ/IAZBASAKQQN2dCIAcUUE",
"QEGs1wAgACAGcjYCACAFDAELIAUoAggLIQAgBSABNgIIIAAgATYCDCABIAU2AgwgASAANgIICyAE",
"QQhqIQFBwNcAIAI2AgBBtNcAIAM2AgAMDAtBsNcAKAIAIglFDQEgCUEAIAlrcUEBayIAIABBDHZB",
"EHEiAnYiAUEFdkEIcSIAIAJyIAEgAHYiAUECdkEEcSIAciABIAB2IgFBAXZBAnEiAHIgASAAdiIB",
"QQF2QQFxIgByIAEgAHZqQQJ0QdzZAGooAgAiAigCBEF4cSAHayEFIAIhAANAAkAgACgCECIBRQRA",
"IAAoAhQiAUUNAQsgASgCBEF4cSAHayIAIAUgACAFSSIAGyEFIAEgAiAAGyECIAEhAAwBCwsgAigC",
"GCEIIAIgAigCDCIDRwRAIAIoAggiAEG81wAoAgBJGiAAIAM2AgwgAyAANgIIDAsLIAJBFGoiACgC",
"ACIBRQRAIAIoAhAiAUUNAyACQRBqIQALA0AgACEEIAEiA0EUaiIAKAIAIgENACADQRBqIQAgAygC",
"ECIBDQALIARBADYCAAwKC0F/IQcgC0G/f0sNACALQQtqIgBBeHEhB0Gw1wAoAgAiCUUNAEEAIAdr",
"IQUCQAJAAkACf0EAIAdBgAJJDQAaQR8gB0H///8HSw0AGiAAQQh2IgAgAEGA/j9qQRB2QQhxIgJ0",
"IgAgAEGA4B9qQRB2QQRxIgF0IgAgAEGAgA9qQRB2QQJxIgB0QQ92IAEgAnIgAHJrIgBBAXQgByAA",
"QRVqdkEBcXJBHGoLIgZBAnRB3NkAaigCACIARQRAQQAhAQwBC0EAIQEgB0EAQRkgBkEBdmsgBkEf",
"Rht0IQIDQAJAIAAoAgRBeHEgB2siBCAFTw0AIAAhAyAEIgUNAEEAIQUgACEBDAMLIAEgACgCFCIE",
"IAQgACACQR12QQRxaigCECIARhsgASAEGyEBIAJBAXQhAiAADQALCyABIANyRQRAQQAhA0ECIAZ0",
"IgBBACAAa3IgCXEiAEUNAyAAQQAgAGtxQQFrIgAgAEEMdkEQcSICdiIBQQV2QQhxIgAgAnIgASAA",
"diIBQQJ2QQRxIgByIAEgAHYiAUEBdkECcSIAciABIAB2IgFBAXZBAXEiAHIgASAAdmpBAnRB3NkA",
"aigCACEBCyABRQ0BCwNAIAEoAgRBeHEgB2siACAFSSECIAAgBSACGyEFIAEgAyACGyEDIAEoAhAi",
"AAR/IAAFIAEoAhQLIgENAAsLIANFDQAgBUG01wAoAgAgB2tPDQAgAygCGCEGIAMgAygCDCICRwRA",
"IAMoAggiAEG81wAoAgBJGiAAIAI2AgwgAiAANgIIDAkLIANBFGoiACgCACIBRQRAIAMoAhAiAUUN",
"AyADQRBqIQALA0AgACEEIAEiAkEUaiIAKAIAIgENACACQRBqIQAgAigCECIBDQALIARBADYCAAwI",
"CyAHQbTXACgCACICTQRAQcDXACgCACEDAkAgAiAHayIBQRBPBEBBtNcAIAE2AgBBwNcAIAMgB2oi",
"ADYCACAAIAFBAXI2AgQgAiADaiABNgIAIAMgB0EDcjYCBAwBC0HA1wBBADYCAEG01wBBADYCACAD",
"IAJBA3I2AgQgAiADaiIAIAAoAgRBAXI2AgQLIANBCGohAQwKCyAHQbjXACgCACIISQRAQbjXACAI",
"IAdrIgE2AgBBxNcAQcTXACgCACICIAdqIgA2AgAgACABQQFyNgIEIAIgB0EDcjYCBCACQQhqIQEM",
"CgtBACEBIAdBL2oiCQJ/QYTbACgCAARAQYzbACgCAAwBC0GQ2wBCfzcCAEGI2wBCgKCAgICABDcC",
"AEGE2wAgDEEMakFwcUHYqtWqBXM2AgBBmNsAQQA2AgBB6NoAQQA2AgBBgCALIgBqIgZBACAAayIE",
"cSIAIAdNDQlB5NoAKAIAIgUEQEHc2gAoAgAiAyAAaiICIANNIAIgBUtyDQoLQejaAC0AAEEEcQ0E",
"AkACQEHE1wAoAgAiAwRAQezaACEBA0AgAyABKAIAIgJPBEAgAiABKAIEaiADSw0DCyABKAIIIgEN",
"AAsLQQAQbSICQX9GDQUgACEGQYjbACgCACIDQQFrIgEgAnEEQCAAIAJrIAEgAmpBACADa3FqIQYL",
"IAYgB00gBkH+////B0tyDQVB5NoAKAIAIgUEQEHc2gAoAgAiAyAGaiIBIANNIAEgBUtyDQYLIAYQ",
"bSIBIAJHDQEMBwsgBiAIayAEcSIGQf7///8HSw0EIAYQbSICIAEoAgAgASgCBGpGDQMgAiEBCyAB",
"QX9GIAdBMGogBk1yRQRAQYzbACgCACICIAkgBmtqQQAgAmtxIgJB/v///wdLBEAgASECDAcLIAIQ",
"bUF/RwRAIAIgBmohBiABIQIMBwtBACAGaxBtGgwECyABIgJBf0cNBQwDC0EAIQMMBwtBACECDAUL",
"IAJBf0cNAgtB6NoAQejaACgCAEEEcjYCAAsgAEH+////B0sNASAAEG0iAkF/RkEAEG0iAEF/RnIg",
"ACACTXINASAAIAJrIgYgB0Eoak0NAQtB3NoAQdzaACgCACAGaiIANgIAQeDaACgCACAASQRAQeDa",
"ACAANgIACwJAAkACQEHE1wAoAgAiBARAQezaACEBA0AgAiABKAIAIgMgASgCBCIAakYNAiABKAII",
"IgENAAsMAgtBvNcAKAIAIgBBACAAIAJNG0UEQEG81wAgAjYCAAtBACEBQfDaACAGNgIAQezaACAC",
"NgIAQczXAEF/NgIAQdDXAEGE2wAoAgA2AgBB+NoAQQA2AgADQCABQQN0IgNB3NcAaiADQdTXAGoi",
"ADYCACADQeDXAGogADYCACABQQFqIgFBIEcNAAtBuNcAIAZBKGsiA0F4IAJrQQdxQQAgAkEIakEH",
"cRsiAGsiATYCAEHE1wAgACACaiIANgIAIAAgAUEBcjYCBCACIANqQSg2AgRByNcAQZTbACgCADYC",
"AAwCCyABLQAMQQhxIAMgBEtyIAIgBE1yDQAgASAAIAZqNgIEQcTXACAEQXggBGtBB3FBACAEQQhq",
"QQdxGyIAaiICNgIAQbjXAEG41wAoAgAgBmoiASAAayIANgIAIAIgAEEBcjYCBCABIARqQSg2AgRB",
"yNcAQZTbACgCADYCAAwBC0G81wAoAgAgAksEQEG81wAgAjYCAAsgAiAGaiEAQezaACEBAkACQAJA",
"AkACQAJAA0AgACABKAIARwRAIAEoAggiAQ0BDAILCyABLQAMQQhxRQ0BC0Hs2gAhAQNAIAQgASgC",
"ACIATwRAIAAgASgCBGoiBSAESw0DCyABKAIIIQEMAAsACyABIAI2AgAgASABKAIEIAZqNgIEIAJB",
"eCACa0EHcUEAIAJBCGpBB3EbaiIJIAdBA3I2AgQgAEF4IABrQQdxQQAgAEEIakEHcRtqIgYgByAJ",
"aiIIayEBIAQgBkYEQEHE1wAgCDYCAEG41wBBuNcAKAIAIAFqIgA2AgAgCCAAQQFyNgIEDAMLQcDX",
"ACgCACAGRgRAQcDXACAINgIAQbTXAEG01wAoAgAgAWoiADYCACAIIABBAXI2AgQgACAIaiAANgIA",
"DAMLIAYoAgQiBUEDcUEBRgRAIAVBeHEhBAJAIAVB/wFNBEAgBigCCCIDIAVBA3YiAEEDdEHU1wBq",
"RhogAyAGKAIMIgJGBEBBrNcAQazXACgCAEF+IAB3cTYCAAwCCyADIAI2AgwgAiADNgIIDAELIAYo",
"AhghBwJAIAYgBigCDCICRwRAIAYoAggiACACNgIMIAIgADYCCAwBCwJAIAZBFGoiBSgCACIADQAg",
"BkEQaiIFKAIAIgANAEEAIQIMAQsDQCAFIQMgACICQRRqIgUoAgAiAA0AIAJBEGohBSACKAIQIgAN",
"AAsgA0EANgIACyAHRQ0AAkAgBigCHCIDQQJ0QdzZAGoiACgCACAGRgRAIAAgAjYCACACDQFBsNcA",
"QbDXACgCAEF+IAN3cTYCAAwCCyAHQRBBFCAHKAIQIAZGG2ogAjYCACACRQ0BCyACIAc2AhggBigC",
"ECIABEAgAiAANgIQIAAgAjYCGAsgBigCFCIARQ0AIAIgADYCFCAAIAI2AhgLIAQgBmoiBigCBCEF",
"IAEgBGohAQsgBiAFQX5xNgIEIAggAUEBcjYCBCABIAhqIAE2AgAgAUH/AU0EQCABQXhxQdTXAGoh",
"AwJ/QazXACgCACICQQEgAUEDdnQiAHFFBEBBrNcAIAAgAnI2AgAgAwwBCyADKAIICyEAIAMgCDYC",
"CCAAIAg2AgwgCCADNgIMIAggADYCCAwDC0EfIQUgAUH///8HTQRAIAFBCHYiACAAQYD+P2pBEHZB",
"CHEiA3QiACAAQYDgH2pBEHZBBHEiAnQiACAAQYCAD2pBEHZBAnEiAHRBD3YgAiADciAAcmsiAEEB",
"dCABIABBFWp2QQFxckEcaiEFCyAIIAU2AhwgCEIANwIQIAVBAnRB3NkAaiEAAkBBsNcAKAIAIgNB",
"ASAFdCICcUUEQEGw1wAgAiADcjYCACAAIAg2AgAMAQsgAUEAQRkgBUEBdmsgBUEfRht0IQUgACgC",
"ACECA0AgAiIAKAIEQXhxIAFGDQMgBUEddiECIAVBAXQhBSAAIAJBBHFqIgMoAhAiAg0ACyADIAg2",
"AhALIAggADYCGCAIIAg2AgwgCCAINgIIDAILQbjXACAGQShrIgNBeCACa0EHcUEAIAJBCGpBB3Eb",
"IgBrIgE2AgBBxNcAIAAgAmoiADYCACAAIAFBAXI2AgQgAiADakEoNgIEQcjXAEGU2wAoAgA2AgAg",
"BCAFQScgBWtBB3FBACAFQSdrQQdxG2pBL2siACAAIARBEGpJGyIDQRs2AgQgA0H02gApAgA3AhAg",
"A0Hs2gApAgA3AghB9NoAIANBCGo2AgBB8NoAIAY2AgBB7NoAIAI2AgBB+NoAQQA2AgAgA0EYaiEB",
"A0AgAUEHNgIEIAFBCGohACABQQRqIQEgACAFSQ0ACyADIARGDQMgAyADKAIEQX5xNgIEIAQgAyAE",
"ayIFQQFyNgIEIAMgBTYCACAFQf8BTQRAIAVBeHFB1NcAaiECAn9BrNcAKAIAIgFBASAFQQN2dCIA",
"cUUEQEGs1wAgACABcjYCACACDAELIAIoAggLIQAgAiAENgIIIAAgBDYCDCAEIAI2AgwgBCAANgII",
"DAQLQR8hASAFQf///wdNBEAgBUEIdiIAIABBgP4/akEQdkEIcSICdCIAIABBgOAfakEQdkEEcSIB",
"dCIAIABBgIAPakEQdkECcSIAdEEPdiABIAJyIAByayIAQQF0IAUgAEEVanZBAXFyQRxqIQELIAQg",
"ATYCHCAEQgA3AhAgAUECdEHc2QBqIQACQEGw1wAoAgAiA0EBIAF0IgJxRQRAQbDXACACIANyNgIA",
"IAAgBDYCAAwBCyAFQQBBGSABQQF2ayABQR9GG3QhASAAKAIAIQMDQCADIgAoAgRBeHEgBUYNBCAB",
"QR12IQIgAUEBdCEBIAAgAkEEcWoiAigCECIDDQALIAIgBDYCEAsgBCAANgIYIAQgBDYCDCAEIAQ2",
"AggMAwsgACgCCCIBIAg2AgwgACAINgIIIAhBADYCGCAIIAA2AgwgCCABNgIICyAJQQhqIQEMBQsg",
"ACgCCCIBIAQ2AgwgACAENgIIIARBADYCGCAEIAA2AgwgBCABNgIIC0G41wAoAgAiACAHTQ0AQbjX",
"ACAAIAdrIgE2AgBBxNcAQcTXACgCACICIAdqIgA2AgAgACABQQFyNgIEIAIgB0EDcjYCBCACQQhq",
"IQEMAwtB+NUAQTA2AgBBACEBDAILAkAgBkUNAAJAIAMoAhwiAUECdEHc2QBqIgAoAgAgA0YEQCAA",
"IAI2AgAgAg0BQbDXACAJQX4gAXdxIgk2AgAMAgsgBkEQQRQgBigCECADRhtqIAI2AgAgAkUNAQsg",
"AiAGNgIYIAMoAhAiAARAIAIgADYCECAAIAI2AhgLIAMoAhQiAEUNACACIAA2AhQgACACNgIYCwJA",
"IAVBD00EQCADIAUgB2oiAEEDcjYCBCAAIANqIgAgACgCBEEBcjYCBAwBCyADIAdBA3I2AgQgAyAH",
"aiIEIAVBAXI2AgQgBCAFaiAFNgIAIAVB/wFNBEAgBUF4cUHU1wBqIQICf0Gs1wAoAgAiAUEBIAVB",
"A3Z0IgBxRQRAQazXACAAIAFyNgIAIAIMAQsgAigCCAshACACIAQ2AgggACAENgIMIAQgAjYCDCAE",
"IAA2AggMAQtBHyEBIAVB////B00EQCAFQQh2IgAgAEGA/j9qQRB2QQhxIgJ0IgAgAEGA4B9qQRB2",
"QQRxIgF0IgAgAEGAgA9qQRB2QQJxIgB0QQ92IAEgAnIgAHJrIgBBAXQgBSAAQRVqdkEBcXJBHGoh",
"AQsgBCABNgIcIARCADcCECABQQJ0QdzZAGohAAJAAkAgCUEBIAF0IgJxRQRAQbDXACACIAlyNgIA",
"IAAgBDYCAAwBCyAFQQBBGSABQQF2ayABQR9GG3QhASAAKAIAIQcDQCAHIgAoAgRBeHEgBUYNAiAB",
"QR12IQIgAUEBdCEBIAAgAkEEcWoiAigCECIHDQALIAIgBDYCEAsgBCAANgIYIAQgBDYCDCAEIAQ2",
"AggMAQsgACgCCCIBIAQ2AgwgACAENgIIIARBADYCGCAEIAA2AgwgBCABNgIICyADQQhqIQEMAQsC",
"QCAIRQ0AAkAgAigCHCIBQQJ0QdzZAGoiACgCACACRgRAIAAgAzYCACADDQFBsNcAIAlBfiABd3E2",
"AgAMAgsgCEEQQRQgCCgCECACRhtqIAM2AgAgA0UNAQsgAyAINgIYIAIoAhAiAARAIAMgADYCECAA",
"IAM2AhgLIAIoAhQiAEUNACADIAA2AhQgACADNgIYCwJAIAVBD00EQCACIAUgB2oiAEEDcjYCBCAA",
"IAJqIgAgACgCBEEBcjYCBAwBCyACIAdBA3I2AgQgAiAHaiIBIAVBAXI2AgQgASAFaiAFNgIAIAoE",
"QCAKQXhxQdTXAGohBEHA1wAoAgAhAwJ/QQEgCkEDdnQiACAGcUUEQEGs1wAgACAGcjYCACAEDAEL",
"IAQoAggLIQAgBCADNgIIIAAgAzYCDCADIAQ2AgwgAyAANgIIC0HA1wAgATYCAEG01wAgBTYCAAsg",
"AkEIaiEBCyAMQRBqJAAgASIADQFBnNsAKAIAIgAEQCAAEQgADAELCwALIAALzAwBB38CQCAARQ0A",
"IABBCGsiAiAAQQRrKAIAIgBBeHEiBGohBQJAIABBAXENACAAQQNxRQ0BIAIgAigCACIAayICQbzX",
"ACgCAEkNASAAIARqIQRBwNcAKAIAIAJHBEAgAEH/AU0EQCACKAIIIgEgAEEDdiIDQQN0QdTXAGpG",
"GiABIAIoAgwiAEYEQEGs1wBBrNcAKAIAQX4gA3dxNgIADAMLIAEgADYCDCAAIAE2AggMAgsgAigC",
"GCEGAkAgAiACKAIMIgBHBEAgAigCCCIBIAA2AgwgACABNgIIDAELAkAgAkEUaiIBKAIAIgMNACAC",
"QRBqIgEoAgAiAw0AQQAhAAwBCwNAIAEhByADIgBBFGoiASgCACIDDQAgAEEQaiEBIAAoAhAiAw0A",
"CyAHQQA2AgALIAZFDQECQCACKAIcIgFBAnRB3NkAaiIDKAIAIAJGBEAgAyAANgIAIAANAUGw1wBB",
"sNcAKAIAQX4gAXdxNgIADAMLIAZBEEEUIAYoAhAgAkYbaiAANgIAIABFDQILIAAgBjYCGCACKAIQ",
"IgEEQCAAIAE2AhAgASAANgIYCyACKAIUIgFFDQEgACABNgIUIAEgADYCGAwBCyAFKAIEIgBBA3FB",
"A0cNAEG01wAgBDYCACAFIABBfnE2AgQgAiAEQQFyNgIEIAIgBGogBDYCAAwBCyACIAVPDQAgBSgC",
"BCIAQQFxRQ0AAkAgAEECcUUEQEHE1wAoAgAgBUYEQEHE1wAgAjYCAEG41wBBuNcAKAIAIARqIgA2",
"AgAgAiAAQQFyNgIEIAJBwNcAKAIARw0DQbTXAEEANgIAQcDXAEEANgIADAMLQcDXACgCACAFRgRA",
"QcDXACACNgIAQbTXAEG01wAoAgAgBGoiADYCACACIABBAXI2AgQgACACaiAANgIADAMLIABBeHEg",
"BGohBAJAIABB/wFNBEAgBSgCCCIBIABBA3YiA0EDdEHU1wBqRhogASAFKAIMIgBGBEBBrNcAQazX",
"ACgCAEF+IAN3cTYCAAwCCyABIAA2AgwgACABNgIIDAELIAUoAhghBgJAIAUgBSgCDCIARwRAIAUo",
"AggiAUG81wAoAgBJGiABIAA2AgwgACABNgIIDAELAkAgBUEUaiIBKAIAIgMNACAFQRBqIgEoAgAi",
"Aw0AQQAhAAwBCwNAIAEhByADIgBBFGoiASgCACIDDQAgAEEQaiEBIAAoAhAiAw0ACyAHQQA2AgAL",
"IAZFDQACQCAFKAIcIgFBAnRB3NkAaiIDKAIAIAVGBEAgAyAANgIAIAANAUGw1wBBsNcAKAIAQX4g",
"AXdxNgIADAILIAZBEEEUIAYoAhAgBUYbaiAANgIAIABFDQELIAAgBjYCGCAFKAIQIgEEQCAAIAE2",
"AhAgASAANgIYCyAFKAIUIgFFDQAgACABNgIUIAEgADYCGAsgAiAEQQFyNgIEIAIgBGogBDYCACAC",
"QcDXACgCAEcNAUG01wAgBDYCAAwCCyAFIABBfnE2AgQgAiAEQQFyNgIEIAIgBGogBDYCAAsgBEH/",
"AU0EQCAEQXhxQdTXAGohAAJ/QazXACgCACIBQQEgBEEDdnQiA3FFBEBBrNcAIAEgA3I2AgAgAAwB",
"CyAAKAIICyEBIAAgAjYCCCABIAI2AgwgAiAANgIMIAIgATYCCAwBC0EfIQEgBEH///8HTQRAIARB",
"CHYiACAAQYD+P2pBEHZBCHEiAHQiASABQYDgH2pBEHZBBHEiAXQiAyADQYCAD2pBEHZBAnEiA3RB",
"D3YgACABciADcmsiAEEBdCAEIABBFWp2QQFxckEcaiEBCyACIAE2AhwgAkIANwIQIAFBAnRB3NkA",
"aiEAAkACQAJAQbDXACgCACIDQQEgAXQiB3FFBEBBsNcAIAMgB3I2AgAgACACNgIAIAIgADYCGAwB",
"CyAEQQBBGSABQQF2ayABQR9GG3QhASAAKAIAIQADQCAAIgMoAgRBeHEgBEYNAiABQR12IQAgAUEB",
"dCEBIAMgAEEEcWoiBygCECIADQALIAcgAjYCECACIAM2AhgLIAIgAjYCDCACIAI2AggMAQsgAygC",
"CCIAIAI2AgwgAyACNgIIIAJBADYCGCACIAM2AgwgAiAANgIIC0HM1wBBzNcAKAIAQQFrIgBBfyAA",
"GzYCAAsLBgAgABBvC3EBAX8gAkUEQCAAKAIEIAEoAgRGDwsgACABRgRAQQEPCwJAIAAoAgQiAi0A",
"ACIARSAAIAEoAgQiAS0AACIDR3INAANAIAEtAAEhAyACLQABIgBFDQEgAUEBaiEBIAJBAWohAiAA",
"IANGDQALCyAAIANGC80DAQR/IwBBQGoiBCQAAn9BASAAIAFBABBxDQAaQQAgAUUNABojAEFAaiID",
"JAAgASgCACIFQQRrKAIAIQYgBUEIaygCACEFIANCADcDICADQgA3AyggA0IANwMwIANCADcANyAD",
"QgA3AxggA0EANgIUIANBxA82AhAgAyABNgIMIANB9A82AgggASAFaiEBQQAhBQJAIAZB9A9BABBx",
"BEAgA0EBNgI4IAYgA0EIaiABIAFBAUEAIAYoAgAoAhQRCgAgAUEAIAMoAiBBAUYbIQUMAQsgBiAD",
"QQhqIAFBAUEAIAYoAgAoAhgRCQACQAJAIAMoAiwOAgABAgsgAygCHEEAIAMoAihBAUYbQQAgAygC",
"JEEBRhtBACADKAIwQQFGGyEFDAELIAMoAiBBAUcEQCADKAIwDQEgAygCJEEBRw0BIAMoAihBAUcN",
"AQsgAygCGCEFCyADQUBrJABBACAFIgFFDQAaIARBCGoiA0EEckEAQTQQYCAEQQE2AjggBEF/NgIU",
"IAQgADYCECAEIAE2AgggASADIAIoAgBBASABKAIAKAIcEQcAIAQoAiAiAEEBRgRAIAIgBCgCGDYC",
"AAsgAEEBRgshACAEQUBrJAAgAAtdAQF/IAAoAhAiA0UEQCAAQQE2AiQgACACNgIYIAAgATYCEA8L",
"AkAgASADRgRAIAAoAhhBAkcNASAAIAI2AhgPCyAAQQE6ADYgAEECNgIYIAAgACgCJEEBajYCJAsL",
"GAAgACABKAIIQQAQcQRAIAEgAiADEHMLCzEAIAAgASgCCEEAEHEEQCABIAIgAxBzDwsgACgCCCIA",
"IAEgAiADIAAoAgAoAhwRBwALmgEAIABBAToANQJAIAAoAgQgAkcNACAAQQE6ADQCQCAAKAIQIgJF",
"BEAgAEEBNgIkIAAgAzYCGCAAIAE2AhAgA0EBRw0CIAAoAjBBAUYNAQwCCyABIAJGBEAgACgCGCIC",
"QQJGBEAgACADNgIYIAMhAgsgACgCMEEBRw0CIAJBAUYNAQwCCyAAIAAoAiRBAWo2AiQLIABBAToA",
"NgsLIAACQCAAKAIEIAFHDQAgACgCHEEBRg0AIAAgAjYCHAsL8gEAIAAgASgCCCAEEHEEQCABIAIg",
"AxB3DwsCQCAAIAEoAgAgBBBxBEACQCACIAEoAhBHBEAgASgCFCACRw0BCyADQQFHDQIgAUEBNgIg",
"DwsgASADNgIgAkAgASgCLEEERg0AIAFBADsBNCAAKAIIIgAgASACIAJBASAEIAAoAgAoAhQRCgAg",
"AS0ANQRAIAFBAzYCLCABLQA0RQ0BDAMLIAFBBDYCLAsgASACNgIUIAEgASgCKEEBajYCKCABKAIk",
"QQFHDQEgASgCGEECRw0BIAFBAToANg8LIAAoAggiACABIAIgAyAEIAAoAgAoAhgRCQALC5EBACAA",
"IAEoAgggBBBxBEAgASACIAMQdw8LAkAgACABKAIAIAQQcUUNAAJAIAIgASgCEEcEQCABKAIUIAJH",
"DQELIANBAUcNASABQQE2AiAPCyABIAI2AhQgASADNgIgIAEgASgCKEEBajYCKAJAIAEoAiRBAUcN",
"ACABKAIYQQJHDQAgAUEBOgA2CyABQQQ2AiwLCzcAIAAgASgCCCAFEHEEQCABIAIgAyAEEHYPCyAA",
"KAIIIgAgASACIAMgBCAFIAAoAgAoAhQRCgALGgAgACABKAIIIAUQcQRAIAEgAiADIAQQdgsLBQBB",
"9AgLBQBBnwkLBAAjAAsGACAAJAALEAAjACAAa0FwcSIAJAAgAAskAQJ/IwBBEGsiASQAIAFBCGog",
"ABAhKAIAIQIgAUEQaiQAIAILC7BKIwBBgAgL+AItKyAgIDBYMHgALTBYKzBYIDBYLTB4KzB4IDB4",
"AGF0YW5fZGl2AHNxcnQAZmluZF9oaWdoZXN0X2JpdAB2ZWN0b3IALi4vc3JjL2xpYi9mcG0vbWF0",
"aC5ocHAALi4vc3JjL2xpYi9mcG0vZml4ZWQuaHBwAHN0ZDo6ZXhjZXB0aW9uAG5hbgBpbmYAZm1v",
"ZABhdGFuX3Nhbml0aXplZABzdGQ6OmJhZF9hbGxvYwBOQU4ASU5GAG9wZXJhdG9yLz0AYXRhbjIA",
"eS5tX3ZhbHVlICE9IDAAeS5yYXdfdmFsdWUoKSAhPSAwAC4AKG51bGwpAHggPj0gRml4ZWQoMCkg",
"JiYgeCA8PSBGaXhlZCgxKQB4ID4gRml4ZWQoMCkAeSA+PSBGaXhlZCgwKQB4ID49IEZpeGVkKDAp",
"AHkgIT0gRml4ZWQoMCkAeCAhPSBGaXhlZCgwKQBBc3NlcnRpb24gZmFpbGVkOiAlcyAoJXM6ICVz",
"OiAlZCkKAEGBCwuAAQkAABALAAAgDQAAMA8AAEARAABQEwAAYBUAAHAXAACAGQAAkBsAAKAdAACw",
"HwAAwCEAANAjAADgJQAA8CcAABkACgAZGRkAAAAABQAAAAAAAAkAAAAACwAAAAAAAAAAGQARChkZ",
"GQMKBwABAAkLGAAACQYLAAALAAYZAAAAGRkZAEGRDAshDgAAAAAAAAAAGQAKDRkZGQANAAACAAkO",
"AAAACQAOAAAOAEHLDAsBDABB1wwLFRMAAAAAEwAAAAAJDAAAAAAADAAADABBhQ0LARAAQZENCxUP",
"AAAABA8AAAAACRAAAAAAABAAABAAQb8NCwESAEHLDQseEQAAAAARAAAAAAkSAAAAAAASAAASAAAa",
"AAAAGhoaAEGCDgsOGgAAABoaGgAAAAAAAAkAQbMOCwEUAEG/DgsVFwAAAAAXAAAAAAkUAAAAAAAU",
"AAAUAEHtDgsBFgBB+Q4L/QIVAAAAABUAAAAACRYAAAAAABYAABYAADAxMjM0NTY3ODlBQkNERUZO",
"MTBfX2N4eGFiaXYxMTZfX3NoaW1fdHlwZV9pbmZvRQAAAAAwCAAAoAcAAPAIAABOMTBfX2N4eGFi",
"aXYxMTdfX2NsYXNzX3R5cGVfaW5mb0UAAAAwCAAA0AcAAMQHAAAAAAAA9AcAAAsAAAAMAAAADQAA",
"AA4AAAAPAAAAEAAAABEAAAASAAAAAAAAAHgIAAALAAAAEwAAAA0AAAAOAAAADwAAABQAAAAVAAAA",
"FgAAAE4xMF9fY3h4YWJpdjEyMF9fc2lfY2xhc3NfdHlwZV9pbmZvRQAAAAAwCAAAUAgAAPQHAAAA",
"AAAA1AgAAAoAAAAXAAAAGAAAAAAAAAC8CAAACgAAABkAAAAaAAAAU3Q5ZXhjZXB0aW9uAAAAAAgI",
"AACsCAAAU3Q5YmFkX2FsbG9jAAAAADAIAADECAAAvAgAAFN0OXR5cGVfaW5mbwAAAAAICAAA4AgA",
"QYISC4IEAQACAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAXABgAGQAa",
"ABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAvADAAMQAyADMANAA1ADYA",
"NwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQAFEAUgBT",
"AFQAVQBWAFcAWABZAFoAWwBcAF0AXgBfAGAAYQBiAGMAZABlAGYAZwBoAGkAagBrAGwAbQBuAG8A",
"cABxAHIAcwB0AHUAdgB3AHgAeQB6AHsAfAB9AH4AfwC4AEd/gH+Bf4N/hH+Ff4Z/h3+If4l/in+L",
"f4x/jX+Of49/kH+Rf5J/k3+Uf5V/ln+Xf5h/mX+af5t/nH+df55/n3+gf6F/on+jf6R/pX+mf6d/",
"qH+pf6p/q3+sf61/rn+vf7B/sX+yf7N/tH+1f7Z/t3+4f7l/un+7f7x/vX++f79/wH/Bf8J/w3/E",
"f8V/xn/Hf8h/yX/Kf8t/zH/Nf85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Zf9p/23/cf91/3n/ff+B/",
"4X/if+N/5H/lf+Z/53/of+l/6n/rf+x/7X/uf+9/8H/xf/J/83/0f/V/9n/3f/h/+X/6f/t//H/9",
"f/5//38AgABBkhYLggQBAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAQABEAEgATABQAFQAW",
"ABcAGAAZABoAGwAcAB0AHgAfACAAIQAiACMAJAAlACYAJwAoACkAKgArACwALQAuAC8AMAAxADIA",
"MwA0ADUANgA3ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBDAEQARQBGAEcASABJAEoASwBMAE0ATgBP",
"AFAAUQBSAFMAVABVAFYAVwBYAFkAWgBbAFwAXQBeAF8AYABhAGIAYwBkAGUAZgBnAGgAaQBqAGsA",
"bABtAG4AbwBwAHEAcgBzAHQAdQB2AHcAeAB5AHoAewB8AH0AfgB/AKkBVn6Af4F/gn+Df4V/hn+H",
"f4h/iX+Kf4t/jH+Nf45/j3+Qf5F/kn+Tf5R/lX+Wf5d/mH+Zf5p/m3+cf51/nn+ff6B/oX+if6N/",
"pH+lf6Z/p3+of6l/qn+rf6x/rX+uf69/sH+xf7J/s3+0f7V/tn+3f7h/uX+6f7t/vH+9f75/v3/A",
"f8F/wn/Df8R/xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/0X/Sf9N/1H/Vf9Z/13/Yf9l/2n/bf9x/",
"3X/ef99/4H/hf+J/43/kf+V/5n/nf+h/6X/qf+t/7H/tf+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5",
"f/p/+3/8f/1//n//fwCAAEGiGguCBAEAAgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQAS",
"ABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4A",
"LwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBL",
"AEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAYgBjAGQAZQBmAGcA",
"aABpAGoAawBsAG0AbgBvAHAAcQByAHMAdAB1AHYAdwB4AHkAegB7AHwAfQB+AIIAQAS/e31/gX+C",
"f4N/hH+Gf4d/iH+Jf4p/i3+Mf41/jn+Pf5B/kX+Sf5N/lH+Vf5Z/l3+Yf5l/mn+bf5x/nX+ef59/",
"oH+hf6J/o3+kf6V/pn+nf6h/qX+qf6t/rH+tf65/r3+wf7F/sn+zf7R/tX+2f7d/uH+5f7p/u3+8",
"f71/vn+/f8B/wX/Cf8N/xH/Ff8Z/x3/If8l/yn/Lf8x/zX/Of89/0H/Rf9J/03/Uf9V/1n/Xf9h/",
"2X/af9t/3H/df95/33/gf+F/4n/jf+R/5X/mf+d/6H/pf+p/63/sf+1/7n/vf/B/8X/yf/N/9H/1",
"f/Z/93/4f/l/+n/7f/x//X/+f/9/AIAAQbIeC4IEAQACAAMABAAFAAYABwAIAAkACgALAAwADQAO",
"AA8AEAARABIAEwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoA",
"KwAsAC0ALgAvADAAMQAyADMANAA1ADYANwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBH",
"AEgASQBKAEsATABNAE4ATwBQAFEAUgBTAFQAVQBWAFcAWABZAFoAWwBcAF0AXgBfAGAAYQBiAGMA",
"ZABlAGYAZwBoAGkAagBrAGwAbQBuAG8AcABxAHIAcwB0AHUAdgB3AHgAeQB6AHsAfAB9AH4ApwAX",
"Ceh2WH+Bf4J/g3+Ef4V/hn+Hf4l/in+Lf4x/jX+Of49/kH+Rf5J/k3+Uf5V/ln+Xf5h/mX+af5t/",
"nH+df55/n3+gf6F/on+jf6R/pX+mf6d/qH+pf6p/q3+sf61/rn+vf7B/sX+yf7N/tH+1f7Z/t3+4",
"f7l/un+7f7x/vX++f79/wH/Bf8J/w3/Ef8V/xn/Hf8h/yX/Kf8t/zH/Nf85/z3/Qf9F/0n/Tf9R/",
"1X/Wf9d/2H/Zf9p/23/cf91/3n/ff+B/4X/if+N/5H/lf+Z/53/of+l/6n/rf+x/7X/uf+9/8H/x",
"f/J/83/0f/V/9n/3f/h/+X/6f/t//H/9f/5//38AgABBwiILggQBAAIAAwAEAAUABgAHAAgACQAK",
"AAsADAANAA4ADwAQABEAEgATABQAFQAWABcAGAAZABoAGwAcAB0AHgAfACAAIQAiACMAJAAlACYA",
"JwAoACkAKgArACwALQAuAC8AMAAxADIAMwA0ADUANgA3ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBD",
"AEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBYAFkAWgBbAFwAXQBeAF8A",
"YABhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG4AbwBwAHEAcgBzAHQAdQB2AHcAeAB5AHoAewB8",
"AH0AiwBoAe8PEHCXfnR/gn+Df4R/hX+Gf4d/iH+Jf4p/i3+Nf45/j3+Qf5F/kn+Tf5R/lX+Wf5d/",
"mH+Zf5p/m3+cf51/nn+ff6B/oX+if6N/pH+lf6Z/p3+of6l/qn+rf6x/rX+uf69/sH+xf7J/s3+0",
"f7V/tn+3f7h/uX+6f7t/vH+9f75/v3/Af8F/wn/Df8R/xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/",
"0X/Sf9N/1H/Vf9Z/13/Yf9l/2n/bf9x/3X/ef99/4H/hf+J/43/kf+V/5n/nf+h/6X/qf+t/7H/t",
"f+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1//n//fwCAAEHSJguCBAEAAgADAAQABQAG",
"AAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIA",
"IwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/",
"AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsA",
"XABdAF4AXwBgAGEAYgBjAGQAZQBmAGcAaABpAGoAawBsAG0AbgBvAHAAcQByAHMAdAB1AHYAdwB4",
"AHkAegB7AH4AiwDrAKgD3BcjaFd8FH90f4F/hH+Ff4Z/h3+If4l/in+Lf4x/jX+Of49/kH+Sf5N/",
"lH+Vf5Z/l3+Yf5l/mn+bf5x/nX+ef59/oH+hf6J/o3+kf6V/pn+nf6h/qX+qf6t/rH+tf65/r3+w",
"f7F/sn+zf7R/tX+2f7d/uH+5f7p/u3+8f71/vn+/f8B/wX/Cf8N/xH/Ff8Z/x3/If8l/yn/Lf8x/",
"zX/Of89/0H/Rf9J/03/Uf9V/1n/Xf9h/2X/af9t/3H/df95/33/gf+F/4n/jf+R/5X/mf+d/6H/p",
"f+p/63/sf+1/7n/vf/B/8X/yf/N/9H/1f/Z/93/4f/l/+n/7f/x//X/+f/9/AIAAQeIqC4IEAQAC",
"AAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAXABgAGQAaABsAHAAdAB4A",
"HwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAvADAAMQAyADMANAA1ADYANwA4ADkAOgA7",
"ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQAFEAUgBTAFQAVQBWAFcA",
"WABZAFoAWwBcAF0AXgBfAGAAYQBiAGMAZABlAGYAZwBoAGkAagBrAGwAbQBuAG8AcABxAHIAcwB0",
"AHUAdgB3AHgAeQB7AIEAmADwAFcCGwjPHzBg5HeofQ9/Z39+f4R/hn+Hf4h/iX+Kf4t/jH+Nf45/",
"j3+Qf5F/kn+Tf5R/lX+Wf5d/mH+af5t/nH+df55/n3+gf6F/on+jf6R/pX+mf6d/qH+pf6p/q3+s",
"f61/rn+vf7B/sX+yf7N/tH+1f7Z/t3+4f7l/un+7f7x/vX++f79/wH/Bf8J/w3/Ef8V/xn/Hf8h/",
"yX/Kf8t/zH/Nf85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Zf9p/23/cf91/3n/ff+B/4X/if+N/5H/l",
"f+Z/53/of+l/6n/rf+x/7X/uf+9/8H/xf/J/83/0f/V/9n/3f/h/+X/6f/t//H/9f/5//38AgABB",
"8i4LggQBAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAQABEAEgATABQAFQAWABcAGAAZABoA",
"GwAcAB0AHgAfACAAIQAiACMAJAAlACYAJwAoACkAKgArACwALQAuAC8AMAAxADIAMwA0ADUANgA3",
"ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBDAEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMA",
"VABVAFYAVwBYAFkAWgBbAFwAXQBeAF8AYABhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG4AbwBw",
"AHEAcgBzAHQAdQB2AHgAewCBAJIAvQAwAWcCtAWqDgMn/FhVcUt6mH3PfkJ/bX9+f4R/h3+Jf4p/",
"i3+Mf41/jn+Pf5B/kX+Sf5N/lH+Vf5Z/l3+Yf5l/mn+bf5x/nX+ef59/oH+hf6J/o3+lf6Z/p3+o",
"f6l/qn+rf6x/rX+uf69/sH+xf7J/s3+0f7V/tn+3f7h/uX+6f7t/vH+9f75/v3/Af8F/wn/Df8R/",
"xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/0X/Sf9N/1H/Vf9Z/13/Yf9l/2n/bf9x/3X/ef99/4H/h",
"f+J/43/kf+V/5n/nf+h/6X/qf+t/7H/tf+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1/",
"/n//fwCAAEGCMwuCBAEAAgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYA",
"FwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAz",
"ADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8A",
"UABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAYgBjAGQAZQBmAGcAaABpAGoAawBs",
"AG0AbgBvAHAAcQByAHQAdgB5AH8AigCfAMkAHgHHAR4D1QVVC3sWFi3pUoRpqnQqeuF8OH7hfjZ/",
"YH91f4B/hn+Jf4t/jX+Of49/kH+Rf5J/k3+Uf5V/ln+Xf5h/mX+af5t/nH+df55/n3+gf6F/on+j",
"f6R/pX+mf6d/qH+pf6p/q3+sf61/rn+vf7B/sX+yf7R/tX+2f7d/uH+5f7p/u3+8f71/vn+/f8B/",
"wX/Cf8N/xH/Ff8Z/x3/If8l/yn/Lf8x/zX/Of89/0H/Rf9J/03/Uf9V/1n/Xf9h/2X/af9t/3H/d",
"f95/33/gf+F/4n/jf+R/5X/mf+d/6H/pf+p/63/sf+1/7n/vf/B/8X/yf/N/9H/1f/Z/93/4f/l/",
"+n/7f/x//X/+f/9/AIAAQZI3C4IEAQACAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIA",
"EwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAv",
"ADAAMQAyADMANAA1ADYANwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsA",
"TABNAE4ATwBQAFEAUgBTAFQAVQBWAFcAWABZAFoAWwBcAF0AXgBfAGAAYQBiAGMAZABlAGYAZwBo",
"AGkAagBrAGwAbQBvAHEAdAB4AH0AhgCTAKgAywADAV8B9wHwAooELQeFC68SfR7zMQxOgmFQbXp0",
"0nh1ew99CH6gfvx+NH9Xf2x/eX+Cf4d/i3+Of5B/kn+Tf5R/lX+Wf5d/mH+Zf5p/m3+cf51/nn+f",
"f6B/oX+if6N/pH+lf6Z/p3+of6l/qn+rf6x/rX+uf69/sH+xf7J/s3+0f7V/tn+3f7h/uX+6f7t/",
"vH+9f75/v3/Af8F/wn/Df8R/xX/Gf8d/yX/Kf8t/zH/Nf85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Z",
"f9p/23/cf91/3n/ff+B/4X/if+N/5H/lf+Z/53/of+l/6n/rf+x/7X/uf+9/8H/xf/J/83/0f/V/",
"9n/3f/h/+X/6f/t//H/9f/5//38AgABBojsLggQBAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4A",
"DwAQABEAEgATABQAFQAWABcAGAAZABoAGwAcAB0AHgAfACAAIQAiACMAJAAlACYAJwAoACkAKgAr",
"ACwALQAuAC8AMAAxADIAMwA0ADUANgA3ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBDAEQARQBGAEcA",
"SABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBYAFkAWgBbAFwAXQBeAF8AYABhAGIAYwBk",
"AGUAZwBoAGoAbQBvAHMAdwB9AIUAkACfALQA0gD8ADcBiwECAqwCnQPzBNoGkAlrDekSuhrbJbU1",
"SkokWkVlFm2Ucm92JXkMe2J8U339fXR+yH4Dfy1/S39gf29/en+Cf4h/jH+Qf5J/lX+Xf5h/mn+b",
"f5x/nX+ef59/oH+hf6J/o3+kf6V/pn+nf6h/qX+qf6t/rH+tf65/r3+wf7F/sn+zf7R/tX+2f7d/",
"uH+5f7p/u3+8f71/vn+/f8B/wX/Cf8N/xH/Ff8Z/x3/If8l/yn/Lf8x/zX/Of89/0H/Rf9J/03/U",
"f9V/1n/Xf9h/2X/af9t/3H/df95/33/gf+F/4n/jf+R/5X/mf+h/6X/qf+t/7H/tf+5/73/wf/F/",
"8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1//n//fwCAAEGyPwuCBAEAAgADAAQABQAGAAcACAAJAAoA",
"CwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAn",
"ACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMA",
"RABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBbAFwAXQBfAGAAYgBk",
"AGcAaQBtAHEAdQB7AIIAiwCWAKQAtgDMAOkADQE7AXYBwgEjAp8CPgMKBA8FXgYNCDUK+gyJEBkV",
"9Rp6IiMsiTh2R9xThV0KZeZqdm8Fc8p18nehefB69XvBfGB93H09fol+xH7yfhZ/M39Jf1t/aX90",
"f31/hH+Kf45/kn+Wf5h/m3+df59/oH+if6N/pH+mf6d/qH+pf6p/q3+sf61/rn+vf7B/sX+yf7N/",
"tH+1f7Z/t3+4f7l/un+7f7x/vX++f79/wH/Bf8J/w3/Ef8V/xn/Hf8h/yX/Kf8t/zH/Nf85/z3/Q",
"f9F/0n/Tf9R/1X/Wf9d/2H/Zf9p/23/cf91/3n/ff+B/4X/if+N/5H/lf+Z/53/of+l/6n/rf+x/",
"7X/uf+9/8H/xf/J/83/0f/V/9n/3f/h/+X/6f/t//H/9f/5/AIAAQcLDAAuCBAEAAgADAAQABQAG",
"AAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIA",
"IwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/",
"AEAAQQBCAEMARABFAEYARwBIAEkASwBMAE0ATgBQAFEAUwBUAFYAWABaAFwAXgBhAGQAaABrAHAA",
"dQB7AIIAigCTAJ8ArAC7AM0A4gD8ABoBPQFoAZoB1gEdAnIC1wJQA98DigRWBUkGawfFCGIKTgyZ",
"DlYRmRR/GCUdsCJOKTQxoDpfRctOsVZPXdpigGdma6luZnGxc511OneUeLZ5qXp1eyB8r3wofY19",
"4n0pfmV+l37CfuV+A38dfzJ/RH9Tf2B/bH91f31/hH+Kf49/lH+Xf5t/nn+hf6N/pX+nf6l/q3+s",
"f65/r3+xf7J/s3+0f7Z/t3+4f7l/un+7f7x/vX++f79/wH/Bf8J/w3/Ef8V/xn/Hf8h/yX/Kf8t/",
"zH/Nf85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Zf9p/23/cf91/3n/ff+B/4X/if+N/5H/lf+Z/53/o",
"f+l/6n/rf+x/7X/uf+9/8H/xf/J/83/0f/V/9n/3f/h/+X/6f/t//H/9f/5/AIAAQdLHAAuCBAEA",
"AgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAe",
"AB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgA0ADUANgA3ADgAOQA7ADwA",
"PQA/AEAAQQBDAEUARgBIAEoATABOAFAAUwBVAFgAWwBfAGIAZwBrAHAAdQB7AIIAigCSAJsApgCx",
"AL4AzQDeAPAABQEdATcBVQF3AZ0ByQH5ATECbwK2AgUDYAPGAzoEvQRRBfkFtwaOB4IIlgnPCjEM",
"ww2KD40R1BNpFlYZpxxoIKokfCnyLiM1JjzZQ9xKDVGDVlVbl19YY6lmlmkrbHJudXA8cs5zMHVp",
"dn13cXhIeQZ6rnpCe8V7OXyffPp8SX2Qfc59Bn42fmJ+iH6qfsh+4n76fg9/IX8yf0F/Tn9Zf2R/",
"bX91f31/hH+Kf49/lH+Yf51/oH+kf6d/qn+sf69/sX+zf7V/t3+5f7p/vH++f79/wH/Cf8N/xH/G",
"f8d/yH/Jf8p/y3/Nf85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Zf9p/23/cf91/3n/ff+B/4X/if+N/",
"5H/lf+Z/53/of+l/6n/rf+x/7X/uf+9/8H/xf/J/83/0f/V/9n/3f/h/+X/6f/t//H/9f/5/AIAA",
"QeLLAAuCBAEAAgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABQAFQAWABcAGAAZABoA",
"GwAdAB4AHwAgACEAIwAkACUAJwAoACkAKwAsAC4AMAAxADMANQA3ADkAOwA9AD8AQQBEAEYASQBM",
"AE8AUgBWAFkAXQBiAGYAawBwAHYAfACCAIkAkQCZAKIAqwC2AMEAzQDaAOgA+AAJARsBLwFFAVwB",
"dgGSAbAB0QH1AR0CSAJ2AqkC4QIeA2ADqAP3A00EqwQRBYEF+wWABhEHsAddCBoJ6QnLCsELzgz0",
"DTUPkxASErQTfBVvF5AZ4htsHjIhOSSIJyQrFy9mMxw4QD2/QuNHmUzoUNtUd1jGW81ek2EdZG9m",
"kGiDakts7W1sb8pwC3Ixcz50NHUWduV2ondPeO54f3kEen567npUe7J7CHxXfJ984XwefVZ9iX23",
"feJ9Cn4ufk9+bX6JfqN+un7QfuR+9n4Hfxd/JX8yfz5/SX9Uf11/Zn9uf3Z/fX+Df4l/j3+Uf5l/",
"nX+if6Z/qX+tf7B/s3+2f7l/u3++f8B/wn/Ef8Z/yH/Kf8x/zn/Pf9F/03/Uf9Z/13/Yf9p/23/c",
"f95/33/gf+F/4n/kf+V/5n/nf+h/6X/qf+t/7X/uf+9/8H/xf/J/83/0f/V/9n/3f/h/+X/6f/t/",
"/H/9f/5/AIAAQfLPAAuHBAYABwAJAAoADAANAA8AEAASABMAFQAXABgAGgAcAB4AIAAiACQAJgAo",
"ACoALQAvADIANAA3ADoAPQBAAEMARwBKAE4AUgBWAFoAXgBjAGgAbQByAHgAfgCFAIsAkgCaAKIA",
"qgCzALwAxgDQANsA5wDzAAABDgEcASwBPAFOAWABdAGIAZ8BtgHPAekBBQIjAkMCZQKIAq4C1wIC",
"Ay8DYAOUA8oDBQRDBIUEywQVBWUFuQUTBnIG2AZEB7cHMgi0CD4J0gluChULxwuEDE0NIw4HD/kP",
"+xANEjITaRSzFRQXihgZGsIbhh1nH2chiCPMJTUoxiqBLWowgjPONk86Cz70QbBFMUl9TJVPflI5",
"VcpXM1p3XJhemGB5Yj1k5mV1Z+toTGqWa81s8m0EbwZw+HDccbJye3M4dOp0kXUtdsF2S3fNd0h4",
"u3gneY157HlGepp66no0e3p7vHv6ezV8a3yffNB8/XwofVF9d32afbx93H36fRZ+MH5JfmB+d36L",
"fp9+sX7DftN+437xfv9+DH8YfyR/L385f0N/TH9Vf11/ZX9tf3R/en+Bf4d/jX+Sf5d/nH+hf6V/",
"qX+tf7F/tX+4f7x/v3/Cf8V/yH/Lf81/0H/Sf9V/13/Zf9t/3X/ff+F/43/lf+d/6H/qf+x/7X/v",
"f/B/8n/zf/V/9n/4f/l/AIAAAAAABQBBhNQACwEFAEGc1AALCgYAAAAHAAAABCsAQbTUAAsBAgBB",
"xNQACwj//////////wBBiNUACwKgbQ==",
].join("");

    function decode(inst) {
        inst.exports._initialize();
        return function (in_buf) {
            var input_offset =  inst.exports.allocate_input(in_buf.byteLength);
            var input_mem = new Uint8Array(inst.exports.memory.buffer, input_offset, in_buf.byteLength);
            input_mem.set(new Uint8Array(in_buf));


            var output = [
                "GYROFLOW IMU LOG",
                "version,1.1",
                "id,esplog",
                "orientation,)--";

const char js_wasm_decoder_1[] = R"--(",
                "tscale,0.00180",
                "gscale,0.00053263221",
                "ascale,0.0001",
                "t,gx,gy,gz,ax,ay,az"
            ];
            
            while(true) {
                inst.exports.decode();
                var output_mem = new Int32Array(inst.exports.memory.buffer, inst.exports.get_output_ptr(), inst.exports.get_output_size());
                if (output_mem.length == 0) { break; }
                for (let i = 0; i < output_mem.length; i += 7) {
                    output.push(output_mem.slice(i, i + 7).join(","));
                }
            }
            var output_text = output.join("\n");
            return Promise.resolve(output_text);
        };
    }

    function downloadText(text, name) {
        var link = document.createElement("a");
        link.download = name;
        link.href = URL.createObjectURL(new Blob([text], {type: 'text/plain'}));
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        delete link;
    }

    function download_and_decode_log(log_url, log_name) {
        let mem = new WebAssembly.Memory({initial:1, maximum: 16000});
        fetch('data:application/octet-stream;base64,' + wasm)
            .then(response => response.arrayBuffer())
            .then(bytes => WebAssembly.instantiate(bytes, {env: {memory: mem, emscripten_notify_memory_growth:()=>{}}}))
            .then(({ instance }) => {
                return decode(instance);
            })
            .then(decoder => {
                fetch(log_url)
                    .then(response => response.arrayBuffer())
                    .then(decoder)
                    .then(text => downloadText(text, log_name));
            });
    }
</script>)--";

const char html_calibration[] = R"--(
<!doctype html>
<html lang=en>
<head>
    <meta charset=utf-8>
    <title>EspLog</title>
</head>
<body>
    <h1>Accelerometer calibration</h1>
    <div class="scene_container">
        <div class="scene">
            <div id="point_container">
            </div>
            <div class="big_circle object3d"></div>
            <div class="hor_bar object3d"></div>
            <div class="ver_bar object3d"></div>
        </div>
    </div>
    <div style="padding:0.5rem;" id="calc_result">---</div>
    <br>
    <div class="button" onclick="add_point();">Add point</div>
    <div class="button" onclick="remove_last_point();">Remove last</div>
    <div class="button" onclick="clear_points();">Clear points</div>
    <br>
    <div class="button" onclick="sphere_fit(points);">Calculate offsets</div>
    <div class="button" id="save_button" onclick="save_offsets(offsets);">Save to flash</div>
</body>
<style>
    .button {
        display: inline-block;
        border: 0.1rem solid black;
        cursor: default;
        margin: 0.2rem;
        padding: 0.3rem;
        user-select: none;
    }

    .button:hover {
        background-color: lightgray;
    }

    .button:active {
        background-color: gray;
    }

    .scene_container {
        width: 22rem;
        height: 22rem;
        position: relative;
    }

    .scene {
        width: 100%;
        height: 100%;
    }

    .object3d {
        position: absolute;
        top: 0rem;
        left: 0rem;
    }

    .big_circle {
        border-radius: 11rem;
        border: 0.1rem solid blue;

        width: 20rem;
        height: 20rem;
        top: 1rem;
        left: 1rem;
    }

    .hor_bar {
        background-color: red;

        width: 22.2rem;
        height: 0.1rem;
        transform: translate(0, 11rem) translate(0, -0.05rem);
    }

    .ver_bar {
        background-color: green;

        height: 22.2rem;
        width: 0.1rem;
        transform: translate(11rem, 0) translate(-0.05rem, 0);
    }

    .calib_point {
        background-color: red;
        border-radius: 1rem;

        width: 0.7rem;
        height: 0.7rem;
    }
</style>
<script type="text/javascript">

    function draw_points(points) {
        let scene_mult = 10;
        let scene_ofs = 1;
        let container = document.getElementById("point_container");

        container.innerHTML = '';

        for (let i = 0; i < points.length; ++i) {
            let x = scene_mult * (points[i][0] + 1) + scene_ofs;
            let y = scene_mult * (points[i][1] + 1) + scene_ofs;
            let z = scene_mult * (points[i][2]);
            let elem = document.createElement("div");
            elem.classList = "calib_point object3d";
            elem.style.transform = `translate3d(${x}rem,${y}rem, ${z}rem) translate3d(-0.35rem, -0.35rem, 0)`;

            container.appendChild(elem);
        }
    }

    let points = [];
    let offsets = [0,0,0];

    function add_point() {
        let xhr = new XMLHttpRequest();
        xhr.responseType = 'json';
        xhr.open('POST', '/calibration');
        xhr.send("get_acceleration");
        xhr.timeout = 2000;
        xhr.onload = function () {
            points.push(xhr.response.acceleration);
            draw_points(points);
            console.log(points);
        };
    }

    function save_offsets(xyz) {
        let btn = document.getElementById("save_button");
        btn.style.color = "red";
        let xhr = new XMLHttpRequest();
        xhr.responseType = 'json';
        xhr.open('POST', '/calibration');
        xhr.send(`set_offsets_ug/${-Math.round(xyz[0] * 1e6)}/${-Math.round(xyz[1] * 1e6)}/${-Math.round(xyz[2] * 1e6)}`);
        xhr.timeout = 2000;
        xhr.onload = function () {
            btn.style.color = "black";
        };
    }

    function clear_points() {
        points = [];
        draw_points(points);
    }

    function remove_last_point() {
        points.pop();
        draw_points(points);
    }

    function sphere_fit(points) {
        const lr = 1e-3;
        const x = new Array(4).fill(0);
        const f = new Array(points.length).fill(0);
        for (let i = 0; i < points.length; ++i) {
            for (let j = 0; j < 3; ++j) {
                f[i] += points[i][j] * points[i][j];
            }
        }

        console.log(f);

        for (let t = 0; t < 1000000; ++t) {
            for (let i = 0; i < points.length; ++i) {
                let aa = -f[i];
                for (let k = 0; k < 3; ++k) {
                    aa += points[i][k] * x[k];
                }
                aa += x[3];
                for (let k = 0; k < 3; ++k) {
                    x[k] -= lr * 2 * aa * points[i][k];
                }
                x[3] -= lr * 2 * aa;
            }
        }

        rad = Math.sqrt(x[0] * x[0] / 4 + x[1] * x[1] / 4 + x[2] * x[2] / 4 + x[3]);
        cx = x[0] / 2;
        cy = x[1] / 2;
        cz = x[2] / 2;

        let result_text = `X = ${cx.toFixed(4)}g, Y = ${cy.toFixed(4)}g, Z = ${cz.toFixed(4)}g, radius = ${rad.toFixed(4)}`;
        document.getElementById("calc_result").innerText = result_text;

        offsets = [cx, cy, cz];

        return offsets;
    }
</script>
</html>
)--";

}  // namespace