// SPDX-License-Identifier: LGPL-2.1-or-later

namespace {
const char html_prefix[] = R"--(
<!doctype html>
<html lang=en>

<head>
    <meta charset=utf-8>
    <title>EspLog</title>
</head>
)--";

constexpr char html_suffix[] = "</html>";

const char html_stylesheet[] = R"--(
<style>
    .command_btn {
        width: 4rem;
        height: 4rem;
        font-size: 2rem;
        border-radius: .5rem;
        border: .2rem solid gray;
    }

    .status_table {
        font-size: 1.5rem;
        font-style: bold;
    }

    .status_table_name_cell {
        width: 18rem;
    }

    .status_value_table_cell {
        padding-left: 2rem;
    }

    .download_table {
        font-size: 1.5rem;
    }

    .download_table_name_cell {
        width: 8rem;
    }

    .delete_btn {
        border: none;
        padding: 0 0 0 0;
    }

    .download_table_mid_cell {
        padding-left: 1rem;
        padding-right: 1rem;
    }

    #network_activity {
        display: inline-block;
        width: 1rem;
        height: 1rem;
        border-radius: 1rem;
    }
</style>
)--";

const char js_xhr_status_updater[] = R"--(
<script type="text/javascript">
    var ind_state = false;
    var indicate = function() {
        var elem = document.getElementById("network_activity");
        ind_state = !ind_state;
        if (ind_state) {
            elem.style.backgroundColor ="orange";
        } else {
            elem.style.backgroundColor ="black";
        }
    };
    var update = function(path, element, interval, timeout, indicate) {
        let controller = new AbortController();
        let restarted = false;
        function restart(t) {
            if (!restarted) {
                restarted = true;
                setTimeout(()=>{update(path, element, interval, timeout, indicate);}, t);
            }
        }
        let to = setTimeout(()=>{ controller.abort(); }, timeout);
        fetch(path, {signal: controller.signal}).then((resp)=>{
            resp.text().then((text)=>{ 
                clearTimeout(to); 
                document.getElementById(element).innerHTML = text; 
                indicate(); 
                restart(interval); 
            }, (error) => { clearTimeout(to); restart(1000); });
        }, (error) => { clearTimeout(to); restart(1000); });
    };
    function make_updater(path, element, interval, timeout, indicate) {
        
        var xhr = new XMLHttpRequest();
        var do_request = function() {
            xhr.open('GET', path);
            xhr.timeout = timeout;
            xhr.send();
        }
        xhr.onload = function() {
            setTimeout(do_request, interval);
            indicate();
            document.getElementById(element).innerHTML = xhr.responseText;
        };
        xhr.onerror = function() {
            setTimeout(do_request, 1000);
        };
        xhr.ontimeout = xhr.onerror;
        do_request();
    }
    var status_last_update = (new Date()).getTime();
    var files_last_update = (new Date()).getTime();
    update( '/status', 'status_table', 500, 1000, ()=>{
        indicate();
        status_last_update = (new Date()).getTime();});
    update( '/files', 'files_table', 1000, 1000,  ()=>{
        indicate();
        files_last_update = (new Date()).getTime();});

    setInterval(()=>{ 
        let status_label = document.getElementById("status_label");
        let files_label = document.getElementById("files_label");
        if ((new Date()).getTime() - status_last_update > 2000) {
            status_label.style.color = "red";
        } else {
            status_label.style.color = "black";
        }
        if ((new Date()).getTime() - files_last_update > 2000) {
            files_label.style.color = "red";
        } else {
            files_label.style.color = "black";
        }
    }, 1000);

    function post_command(command) {
        let xhr = new XMLHttpRequest();
        xhr.open('POST', '/');
        xhr.send(command);
        xhr.timeout = 10000;
    }
</script>)--";

const char js_wasm_decoder[] = R"--(<script type="text/javascript">
var wasm = [
    "AGFzbQEAAAABehNgAX8Bf2ACf38Bf2ABfwBgAAF/YAJ/fwBgA39/fwBgA39/fwF/YAR/f39/AGAF",
    "f39/f38AYAZ/f39/f38AYAAAYAR/f39/AX9gBn98f39/fwF/YAV/f39/fwF/YAJ/fAF/YAF/AXxg",
    "A39+fwF+YAJ8fwF8YAJ+fwF/AicBA2Vudh9lbXNjcmlwdGVuX25vdGlmeV9tZW1vcnlfZ3Jvd3Ro",
    "AAIDe3oKAAICAgIAAAIKAwAAAAMDAwMBDQQFDgsPAgIBAAECAAEAAQEBAAABAQECAgAGAAALBAIB",
    "AQACAAEEAQAHBAQBAQEBAQMDAQMGBQIBAQEBAAQEBQoFBwMQBQAAEQsFAAUSCAwEAQAAAgIGBgUH",
    "BwcFCAgJCQAAAwIAAAQFAXABGhoFBQEBAYB9BggBfwFB0NoDCwesAQsGbWVtb3J5AgAOYWxsb2Nh",
    "dGVfaW5wdXQADA9nZXRfb3V0cHV0X3NpemUADw5nZXRfb3V0cHV0X3B0cgARBmRlY29kZQASGV9f",
    "aW5kaXJlY3RfZnVuY3Rpb25fdGFibGUBAAtfaW5pdGlhbGl6ZQBUEF9fZXJybm9fbG9jYXRpb24A",
    "VwlzdGFja1NhdmUAdwxzdGFja1Jlc3RvcmUAeApzdGFja0FsbG9jAHkJHwEAQQELGQMJAS0uWGNk",
    "Dg5pBARrdHJtaXNxbml2aXUKic0BeiQAQYzVABACGkGY1QAQAhpBxNYAQdTVADYCAEH81QBBKjYC",
    "AAssAQF/IwBBEGsiASQAIABCADcCACABQQA2AgwgAEEIahA4GiABQRBqJAAgAAsIAEGM1QAQBQsD",
    "AAELLgEBfyAAEAYgACgCAARAIAAgACgCABBRIAAQBxogACgCACEBIAAQCBogARBoCwspACAAKAIA",
    "GiAAKAIAIAAQCGoaIAAoAgAgABANahogACgCACAAEAhqGgsHACAAQQhqCw8AIAAQBygCACAAKAIA",
    "awtdAQF/EApBmNUAKAIABEBBmNUAKAIAIQFBnNUAKAIAIQADQCAAIAFHBEBBmNUAEAcaIABBBGsh",
    "AAwBCwtBnNUAIAE2AgBBmNUAEAcaQZjVACgCACEAEAsaIAAQaAsLNABBmNUAKAIAGkGY1QAoAgAQ",
    "C0ECdGoaQZjVACgCABAQQQJ0ahpBmNUAKAIAEAtBAnRqGgsWAEGY1QAQBygCAEGY1QAoAgBrQQJ1",
    "C9sGAQd/AkAgAEGM1QAQDSIBSwRAIwBBIGsiBiQAAkAgACABayIFQYzVABAHKAIAQZDVACgCAGtN",
    "BEAjAEEQayIAJAAgAEGM1QA2AgAgAEGQ1QAoAgAiATYCBCAAIAEgBWo2AgggACIBKAIEIQAgASgC",
    "CCECA0AgACACRgRAIAEQSyABQRBqJAAFQYzVABAHIAAQUiABIABBAWoiADYCBAwBCwsMAQtBjNUA",
    "EAchByAGQQhqIQICf0GM1QAQDSAFaiEEIwBBEGsiASQAIAEgBDYCDCMAQRBrIgMkAEGM1QAQBxog",
    "A0F/NgIMIANB/////wc2AgggA0EMaiADQQhqEDkoAgAhACADQRBqJAAgACAETwRAQYzVABAIIgMg",
    "AEEBdkkEQCABIANBAXQ2AgggAUEIaiABQQxqEEwoAgAhAAsgAUEQaiQAIAAMAQsACyEBQYzVABAN",
    "IQRBACEAIwBBEGsiAyQAIANBADYCDCACQQxqIAcQOiABBEAgAigCEBogARBnIQALIAIgADYCACAC",
    "IAAgBGoiBDYCCCACIAQ2AgQgAhA8IAAgAWo2AgAgA0EQaiQAIwBBEGsiASQAIAEgAigCCDYCACAC",
    "KAIIIQAgASACQQhqNgIIIAEgACAFajYCBCABKAIAIQADQCABKAIEIABHBEAgAigCECABKAIAEFIg",
    "ASABKAIAQQFqIgA2AgAMAQsLIAEoAgggASgCADYCACABQRBqJABBjNUAEAZBjNUAEAdBjNUAKAIA",
    "QZDVACgCACACQQRqIgAQPUGM1QAgABA+QZDVACACQQhqED5BjNUAEAcgAhA8ED4gAiACKAIENgIA",
    "QYzVABANGkGM1QAoAgAaQYzVACgCAEGM1QAQCGoaQYzVACgCAEGM1QAQCGoaQYzVACgCABogAigC",
    "BCEAA0AgACACKAIIRwRAIAIoAhAaIAIgAigCCEEBazYCCAwBCwsgAigCAARAIAIoAhAaIAIoAgAh",
    "ACACEDwoAgAgAigCAGsaIAAQaAsLIAZBIGokAAwBCyAAIAFJBEBBjNUAKAIAIABqIQBBjNUAEA0a",
    "QYzVACAAEFFBjNUAKAIAGkGM1QAoAgBBjNUAEAhqGkGM1QAoAgAaQYzVACgCAEGM1QAQDWoaCwtB",
    "jNUAKAIACw0AIAAoAgQgACgCAGsLBAAgAAsEABAQCxQAQZzVACgCAEGY1QAoAgBrQQJ1CwkAQZjV",
    "ACgCAAuGGAIafwF8IwBB0AFrIgMkACADQZgBakEBEBMiCEEEakEAEBMaIAhBCGpBABATGiAIQQxq",
    "QQAQExogCEEQakEAEBMiAEEEakEAEBMaIABBCGpBABATGiAIQRY6ABwgCEGAAjYCICAIQSRqQX8Q",
    "ExogCEEANgIoIAhBLGoQAhogA0EANgKUASADQShqIRIgA0EgakEEciETIANByABqIRQgA0FAa0EE",
    "ciEVIANBgAFqIANB+ABqQQEQEygCAEEAQQBBABAUIREDQEGM1QAQDSAQSwRAIANB4ABqIQsgEEGM",
    "1QAoAgBqIQpBjNUAEA0gEGshAUEAIQ4jAEHgAGsiAiQAIAIgCi0AACIWNgJcAkAgAUEFTQRAIAsQ",
    "GwwBCyAKLQABIgBBBXYhFyACQdgAaiAAQR9xEBwhDCACIApBAmo2AlAgAigCUCIAKAAAIQQgAiAA",
    "QQRqNgJQIAIgBDYCVCACQUBrEAIiBiEAIAgoAiAhBCMAQSBrIgckAAJAAkAgABAvIARJBEAgABAw",
    "IARJDQEgABAHIQUgACAHQQhqIAQgABAdIAUQMSIAEDIgABAzCyAHQSBqJAAMAQsACyAIQRBqIQcg",
    "ASAKaiEYIAFBAEwhGQJAA0AgBhAdIAgoAiBJBEBBACEFIAJBADoAOiACQQA7ATgDQCAFQQNHBEAC",
    "QCAZDQAgGCACKAJQa0EDSg0AIAsQGwwFCyACQThqIAVqAn8gAigCVEH//wFxIQlB/34hBEGBASEB",
    "A0AgASABIARBAWpGDQEaIAwgASAEakECbSIAEB4gCUoEQCAAIQEMAQsgDCAAIgRBAWoQHiAJTA0A",
    "CyAECyIBOgAAIAwgARAeIQAgDCABQQFqEB4gAGshBCACKAJUIglB//8BcSAAayAJQQ92IARsaiIE",
    "Qf///wNNBEAgAigCUCEAA0AgAC0AACEJIABBAWohACAJIARBCHRyIgRBgICABEkNAAsgAiAANgJQ",
    "CyACIAQ2AlQgBUEBaiEFIAEgDmohDgwBCwsgAiACLQA6OgAGIAIgAi8BODsBBCACQShqIgAgAiwA",
    "BCAWQRh0QRh1IgF0ECAgAiwABSABdBAgIAIsAAYgAXQQIBAYGiAHIAAQNBogB0EEaiAAQQRqEDQa",
    "IAdBCGogAEEIahA0GkEBIQACQCACLQA4IgEgAUEYdEEfdSIBcyABa0H/AXFB/wBGDQAgAi0AOSIB",
    "IAFBGHRBH3UiAXMgAWtB/wFxQf8ARg0AIAItADoiACAAQRh0QR91IgBzIABrQf8BcUH/AEYhAAsg",
    "AA0BIwBBQGoiACQAIAJBCGoiBEIANwIAIARCADcCCCAAIAcgBxAjNgIwIAAgB0EEaiIFIAUQIzYC",
    "KCAAIABBMGogAEEoahAkNgIQIAAgB0EIaiIJIAkQIzYCICAAIABBEGoiASAAQSBqECQ2AjgCQCAA",
    "QThqIAFBABATEDUEQCAAIAAoAjgQJzYCMCAAIABBMGoiDSAAQRBqIgFEAAAAAAAA4D8QFxAjIg8Q",
    "NjYCECAAIAEgDRAqNgIoIAQgAQJ/IwBBEGsiASQAIAEgDzYCCCABEEY2AgAgASABQQhqECQQNiEN",
    "IAFBEGokACANCyAHIABBKGoiARAjIAUgARAjIAkgARAjEBQiASkCADcCAAwBCyAAQYCAgMAANgIw",
    "IABBCGpEAAAAAAAA8D8QFyENIAcgAEEwaiIBECMhDyAFIAEQIyEFIAkgARAjIQEgBCAAQRBqIA0o",
    "AgAgDyAFIAEQFCIBKQIANwIACyAEIAEpAgg3AgggAEFAayQAIAJBGGoiASAIIAQQFiMAQRBrIgQk",
    "ACMAQTBrIgAkACAAIAEgARAjNgIYIAAgAUEEaiIFIAUQIzYCECAAIABBGGogAEEQahAkNgIgIAAg",
    "AUEIaiIJIAkQIzYCCCAAIABBIGogAEEIahAkNgIoIAAgAUEMaiINIA0QIzYCACAAQShqIAAQJBAn",
    "IQ8gAEEwaiQAIAQgDzYCCCACQShqIAEgBEEIaiIAECogBSAAECogCSAAECogDSAAECoQFBogBEEQ",
    "aiQAIAggAikDMDcCCCAIIAIpAyg3AgACQCAGKAIEIAYQBygCAEcEQCMAQRBrIgEkACABIAZBARBJ",
    "IQAgBhAHIAAoAgQgCBBKIAAgACgCBEEQajYCBCAAEEsgAUEQaiQADAELIwBBIGsiBCQAIAYQByIJ",
    "IARBCGoCfyAGEB1BAWohBSMAQRBrIgAkACAAIAU2AgwgBSAGEDAiAU0EQCAGEC8iBSABQQF2SQRA",
    "IAAgBUEBdDYCCCAAQQhqIABBDGoQTCgCACEBCyAAQRBqJAAgAQwBCwALIAYQHSAJEDEiACgCCCAI",
    "EEogACAAKAIIQRBqNgIIIAYgABAyIAAQMyAEQSBqJAALDAELCyAOQQdxIBdHBEAgCxAbDAELIAIg",
    "AigCUCAKazYCKCALIAJBKGoQTSIMQQRqIQAjAEEQayIEJAAgAEIANwIAIARBADYCDCAGEAcaIABB",
    "CGoQOBogBhAdIgEEQCAAEDAgAUkEQAALIAAgABAHIAEQOyIHNgIAIAAgBzYCBCAAEAcgByABQQR0",
    "ajYCACAAQQAQPyAGKAIAIQcgBigCBCEFIwBBEGsiCiQAIAogACABEEkhASAAEAcaIAUgB2siAEEA",
    "SgRAIAEoAgQgByAAEFUgASABKAIEIABqNgIECyABEEsgCkEQaiQACyAEQRBqJAAgDEEQaiACQdwA",
    "ahBNGgsgBhAfCyACQeAAaiQAQQAhAQJAQaTVAC0AAA0AIAsoAgAiDEUNACADIAsoAgQQIDYCWCAD",
    "IAsoAggQIDYCUAN/IANB2ABqIANB0ABqECFBAXMEfyADQSBqIgsgAygCWCIEEBUgA0EwaiIBIAsg",
    "ERAWIANBQGshCiMAQTBrIgAkACAAIAFBBGoiAiACECM2AhggACABQQhqIgYgBhAjNgIQIAAgAEEY",
    "aiAAQRBqECQ2AiAgACABQQxqIgcgBxAjNgIIIAAgAEEgaiIFIABBCGoQJDYCKAJAIABBKGogBUQA",
    "AAAAAAAAABAXECUEQCAKIAIQJiAGECYgBxAmEBgaDAELIAAgACgCKBAnIgU2AiAgAEEQakECEBMh",
    "DiAAAn8gASAAQQAQExAoBEAgAEEgahAiIAEQIhApDAELIAUgASgCABApCzYCCCAAIA4gAEEIahAj",
    "NgIYIAAgAEEYaiAAQSBqECo2AhAgCiACIABBEGoiAhAjIAYgAhAjIAcgAhAjEBgaCyAAQTBqJAAg",
    "ASAEEBUgA0EQakEAQQAgA0EIakQAAAAAAADwvxAXKAIAEBghAiMAQdAAayIAJAAgAEEwaiIGIAEg",
    "AEEgaiAAQRhqQQAQEygCACACKAIAIAIoAgQgAigCCBAUEBYgAEEIaiICIAEQFSAAQUBrIAYgAhAW",
    "IAsgACgCRCAAKAJIIAAoAkwQGBogAEHQAGokACARIAQpAgg3AgggESAEKQIANwIAIAMgAygClAEE",
    "fyADQZQBaiEAAkBBnNUAKAIAQZjVABAHKAIARwRAIAAQKwwBCyAAECwLIAMCfyADQUBrEBlEzb+U",
    "s7vUL0GiIhqZRAAAAAAAAOBBYwRAIBqqDAELQYCAgIB4CzYCMCADQTBqEBogAwJ/IBUQGUTNv5Sz",
    "u9QvQaIiGplEAAAAAAAA4EFjBEAgGqoMAQtBgICAgHgLNgIwIANBMGoQGiADAn8gFBAZRM2/lLO7",
    "1C9BoiIamUQAAAAAAADgQWMEQCAaqgwBC0GAgICAeAs2AjAgA0EwahAaIAMCfyADQSBqEBlEAAAA",
    "AACIw0CiIhqZRAAAAAAAAOBBYwRAIBqqDAELQYCAgIB4CzYCMCADQTBqEBogAwJ/IBMQGUQAAAAA",
    "AIjDQKIiGplEAAAAAAAA4EFjBEAgGqoMAQtBgICAgHgLNgIwIANBMGoQGiADAn8gEhAZRAAAAAAA",
    "iMNAoiIamUQAAAAAAADgQWMEQCAaqgwBC0GAgICAeAs2AjAgA0EwahAaIAMoApQBBUEAC0EBajYC",
    "lAEgAyADKAJYQRBqNgJYDAEFIAwgEGohEEEBCwshAQsgA0HkAGoQHyABDQELCyAIQSxqEAUgA0HQ",
    "AWokAEEACw4AIAAgAUEcdDYCACAACyAAIAAgBDYCDCAAIAM2AgggACACNgIEIAAgATYCACAACyEA",
    "IAAgASgCACABQQRqECIgAUEIahAiIAFBDGoQIhAUGgvsAwEJfyAAIAEpAgA3AgAgACABKQIINwII",
    "IwBB0AFrIgEkACABIAAgAhAjNgKoASABIABBBGoiBCACQQRqIgUQIzYCoAEgASABQagBaiABQaAB",
    "ahBDNgKwASABIABBCGoiAyACQQhqIgYQIzYCmAEgASABQbABaiABQZgBahBDNgK4ASABIABBDGoi",
    "ByACQQxqIggQIzYCkAEgAUG4AWogAUGQAWoQQyEJIAEgACAFECM2AnggASAEIAIQIzYCcCABIAFB",
    "+ABqIAFB8ABqECQ2AoABIAEgAyAIECM2AmggASABQYABaiABQegAahAkNgKIASABIAcgBhAjNgJg",
    "IAFBiAFqIAFB4ABqEEMhCiABIAAgBhAjNgJIIAEgBCAIECM2AkAgASABQcgAaiABQUBrEEM2AlAg",
    "ASADIAIQIzYCOCABIAFB0ABqIAFBOGoQJDYCWCABIAcgBRAjNgIwIAFB2ABqIAFBMGoQJCELIAEg",
    "ACAIECM2AhggASAEIAYQIzYCECABIAFBGGogAUEQahAkNgIgIAEgAyAFECM2AgggASABQSBqIAFB",
    "CGoQQzYCKCABIAcgAhAjNgIAIAAgAUHAAWogCSAKIAsgAUEoaiABECQQFCIAKQIANwIAIAMgACkC",
    "CDcCACABQdABaiQAC1MAIAACfyABRAAAAAAAALBBokQAAAAAAADgP0QAAAAAAADgvyABRAAAAAAA",
    "AAAAZhugIgGZRAAAAAAAAOBBYwRAIAGqDAELQYCAgIB4CzYCACAACxkAIAAgAzYCCCAAIAI2AgQg",
    "ACABNgIAIAALEgAgACgCALdEAAAAAAAAMD6iCx8AQZzVACgCAEGY1QAQBygCAEkEQCAAECsPCyAA",
    "ECwLFgAgABA4IgBBBGoQAhogAEEQahA4GgsLACAAIAE2AgAgAAsQACAAKAIEIAAoAgBrQQR1CykB",
    "AX8gAUGBf04EfyAAKAIAQQJ0QYALaigCACABQQF0ai8BgAIFQQALC1MBAn8gABA3IAAoAgAEQCAA",
    "KAIAIQIgACgCBCEBA0AgASACRwRAIAAQBxogAUEQayEBDAELCyAAIAI2AgQgABAHGiAAKAIAIQEg",
    "ABAvGiABEGgLCyQBAX8jAEEQayIBJAAgAUEIaiAAEBwoAgAhACABQRBqJAAgAAsNACAAKAIAIAEo",
    "AgBGCwwAQQAgACgCAGsQIAtUAgF/AX4jAEEQayICJAAgAiAAKAIANgIIIAJBCGoiACABNAIAIAA0",
    "AgB+IgNCgICAwAB/QgKBIANCgICAgAF/fD4CACAAKAIAIQAgAkEQaiQAIAALLgEBfyMAQRBrIgIk",
    "ACACIAAoAgA2AgggAkEIaiABEDQoAgAhACACQRBqJAAgAAsNACAAKAIAIAEoAgBMCy4BAX8jAEEQ",
    "ayIBJAAgASAAKAIANgIIIAFBCGpBAhBHKAIAIQAgAUEQaiQAIAAL3QECAX8EfiMAQSBrIgEkACAB",
    "IAA2AhgCQCABQRhqIAFBEGpBABATEEEEQCABQRhqIAFBCGpBABATECEEQCABKAIYIQAMAgsgATQC",
    "GCICQhyGIQMgAlAEQEHLCUHDCEEXQasIEFYAC0IBIAJ5p0E/c0EcakF+ca2GIQIDQCACUARAIAQg",
    "AyAEVa18pxAgIQAMAwUgBEIBh0IAIAIgAyACIAR8IgVTIgAbfCEEIANCACAFIAAbfSEDIAJCAoch",
    "AgwBCwALAAtBrApBwwhB0QNBpggQVgALIAFBIGokACAACw0AIAAoAgAgASgCAEgL9gEBAX8jAEEw",
    "ayICJAAgAiABNgIgIAIgADYCKAJAAkAgAkEgaiACQRhqQQAQExAhBEAgAkEoaiACQRhqQQAQExBO",
    "RQ0CIAJBKGogAkEYakEAEBMQNSEBEEYhACABDQEgAiAANgIQIAJBEGoQIiEADAELIAIgACACKAIg",
    "EE8iADYCGCACQSBqIAJBEGpBABATEChFDQAgAkEoaiACQRBqQQAQExBBIQEQSCEAIAEEQCACIAA2",
    "AgggAkEYaiACQQhqECQhAAwBCyACIAA2AgggAkEYaiACQQhqEEMhAAsgAkEwaiQAIAAPC0G6CkHD",
    "CEGYBUHBCRBWAAtrAgF/An4jAEEQayICJAAgAiAAKAIANgIIIAJBCGohACABKAIAIgFFBEBBxwlB",
    "2whBqQFBtgkQVgALIAAgADQCAEIdhiABrH8iA0ICfyIEIAMgBEIBhn18PgIAIAAoAgAhACACQRBq",
    "JAAgAAtZAQJ/IwBBEGsiAiQAIAJBmNUANgIAIAJBnNUAKAIAIgE2AgQgAiABQQRqNgIIIAIhAUGY",
    "1QAQByABKAIEIAAQUyABIAEoAgRBBGo2AgQgARBLIAJBEGokAAuPBAEHfyMAQSBrIgYkAEGY1QAQ",
    "ByIHAn8gBkEIaiEBAn8QEEEBaiEFIwBBEGsiAiQAIAIgBTYCDCMAQRBrIgMkAEGY1QAQBxogA0H/",
    "////AzYCDCADQf////8HNgIIIANBDGogA0EIahA5KAIAIQQgA0EQaiQAIAQgBU8EQBALIgMgBEEB",
    "dkkEQCACIANBAXQ2AgggAkEIaiACQQxqEEwoAgAhBAsgAkEQaiQAIAQMAQsACyECEBAhBUEAIQQj",
    "AEEQayIDJAAgA0EANgIMIAFBDGogBxA6IAIEQCABKAIQGiACQf////8DSwRAAAsgAkECdBBnIQQL",
    "IAEgBDYCACABIAQgBUECdGoiBTYCCCABIAU2AgQgARA8IAQgAkECdGo2AgAgA0EQaiQAIAEoAggL",
    "IAAQUyABIAEoAghBBGo2AggQCkGY1QAQB0GY1QAoAgBBnNUAKAIAIAFBBGoiABA9QZjVACAAED5B",
    "nNUAIAFBCGoQPkGY1QAQByABEDwQPiABIAEoAgQ2AgAQEBpBmNUAKAIAGkGY1QAoAgAQC0ECdGoa",
    "QZjVACgCABALQQJ0ahpBmNUAKAIAGiABKAIEIQADQCAAIAEoAghHBEAgASgCEBogASABKAIIQQRr",
    "NgIIDAELCyABKAIABEAgASgCEBogASgCACEAIAEQPCgCACABKAIAaxogABBoCyAGQSBqJAALBABB",
    "AAsEAEEACxIAIAAQBygCACAAKAIAa0EEdQtCAQF/IwBBEGsiASQAIAAQBxogAUH/////ADYCDCAB",
    "Qf////8HNgIIIAFBDGogAUEIahA5KAIAIQAgAUEQaiQAIAALYgECfyMAQRBrIgUkACAFQQA2Agwg",
    "AEEMaiADEDogAQRAIAAoAhAgARA7IQQLIAAgBDYCACAAIAQgAkEEdGoiAjYCCCAAIAI2AgQgABA8",
    "IAQgAUEEdGo2AgAgBUEQaiQAIAALTQEBfyAAEDcgABAHIAAoAgAgACgCBCABQQRqIgIQPSAAIAIQ",
    "PiAAQQRqIAFBCGoQPiAAEAcgARA8ED4gASABKAIENgIAIAAgABAdED8LVQEBfyAAKAIEIQEDQCAB",
    "IAAoAghHBEAgACgCEBogACAAKAIIQRBrNgIIDAELCyAAKAIABEAgACgCEBogACgCACEBIAAQPCgC",
    "ACAAKAIAaxogARBoCwsUACAAIAAoAgAgASgCAGo2AgAgAAsNACAAKAIAIAEoAgBKC/0DAQN/IwBB",
    "8ABrIgEkABBFIQMjAEEQayICJAAgAiADNgIAIAIgADYCCCACKAIARQRAQdYJQcMIQb4BQYsJEFYA",
    "CyACKAIIIAIoAgBvECAhACACQRBqJAAgASAANgJoIAEQRjYCYCABIAFB6ABqIgAgAUHgAGoiAhAq",
    "NgJoIAAgAkEAEBMQKARAIAFB6ABqIAFB4ABqQQQQExA0GgtBASEAIAFB6ABqIAFB4ABqQQIQExA1",
    "BEAgAUHoAGogAUHgAGpBAhATEEIaQX8hAAsgAUHoAGogAUHgAGpBARATEDUEQCABIAFB4ABqQQIQ",
    "EyABQegAahBDNgJoCyABIAFB6ABqIgMgAxAjNgJgIwBBEGsiAiQAIAIgAygCADYCCCACQQhqIAAQ",
    "RygCACEAIAJBEGokACABIAA2AlAgARBINgJAIAEQRTYCICABIAFBIGpBBRBENgIoIAEQSDYCCCAB",
    "IAFBCGpBAxBENgIQIAEgAUHgAGoiACABQRBqECM2AhggASABQShqIAFBGGoQQzYCMCABIAAgAUEw",
    "ahAjNgI4IAEgAUFAayABQThqEEM2AkggASABQdAAaiABQcgAahAjNgJYIwBBEGsiACQAIAAgASgC",
    "WDYCCCAAQQhqIgIgAigCAEECbTYCACACKAIAIQIgAEEQaiQAIAFB8ABqJAAgAgsyACAAKAIAGiAA",
    "KAIAIAAQL0EEdGoaIAAoAgAgABAdQQR0ahogACgCACAAEC9BBHRqGgsLACAAQQA2AgAgAAsjAQJ/",
    "IwBBEGsiAiQAIAEgABBAIQMgAkEQaiQAIAEgACADGwsOACAAEDhBBGogARAcGgsWACABQf////8A",
    "SwRAAAsgAUEEdBBnCwcAIABBDGoLJgAgAyADKAIAIAIgAWsiAGsiAjYCACAAQQBKBEAgAiABIAAQ",
    "VQsLHAEBfyAAKAIAIQIgACABKAIANgIAIAEgAjYCAAsqACAAKAIAGiAAKAIAIAAQL0EEdGoaIAAo",
    "AgAgABAvQQR0ahogACgCABoLDQAgACgCACABKAIASQsNACAAKAIAIAEoAgBOCxQAIAAgACgCACAB",
    "KAIAazYCACAACy4BAX8jAEEQayICJAAgAiAAKAIANgIIIAJBCGogARBCKAIAIQAgAkEQaiQAIAAL",
    "PAEBfyMAQRBrIgIkACACIAAoAgA2AgggAkEIaiIAIAAoAgAgAUEcdGs2AgAgACgCACEAIAJBEGok",
    "ACAACwoAQdHan6QGEHoLCgBB1PaHyQEQegsRACAAIAAoAgAgAWw2AgAgAAsKAEGp7Y+SAxB6CyQA",
    "IAAgATYCACAAIAEoAgQiATYCBCAAIAEgAkEEdGo2AgggAAsWACABIAIpAgA3AgAgASACKQIINwII",
    "Cw8AIAAoAgAgACgCBDYCBAsjAQJ/IwBBEGsiAiQAIAAgARBAIQMgAkEQaiQAIAEgACADGwsOACAA",
    "IAEoAgA2AgAgAAsNACAAKAIAIAEoAgBHC9sCAQF/IwBBIGsiAiQAIAIgATYCECACIAA2AhgCQAJA",
    "IAJBEGogAkEIakEAEBMQTgRAAn8gAkEYaiACQQhqQQAQExAoBEAgAkEQaiACQQhqQQAQExAoBEAg",
    "AkEYahAiIAJBEGoQIhBPDAILIAIgAkEYahAiIAIoAhAQTzYCCCACQQhqECIMAQsgAkEQaiACQQhq",
    "QQAQExAoBEAgAiACKAIYIAJBEGoQIhBPNgIIIAJBCGoQIgwBCyACQRhqIAJBCGpBABATEEFFDQIg",
    "AkEQaiACQQhqQQAQExA1RQ0DIAJBGGogAkEQahA1BEAgAhBGNgIIIAIgAkEQaiACQRhqECoQUDYC",
    "ACACQQhqIAIQQwwBCyACQRhqIAJBEGoQKhBQCyEAIAJBIGokACAADwtByApBwwhBzARBnQgQVgAL",
    "QZ4KQcMIQdoEQZ0IEFYAC0GRCkHDCEHbBEGdCBBWAAvWAQECfyMAQdAAayIBJAAgASAANgJIAkAg",
    "AUHIAGogAUFAa0EAEBMQQQRAIAFByABqIAFBOGpBARATECUNAQtB8glBwwhBuARBkAkQVgALIAFB",
    "7p34CTYCQCABQZzWmls2AjggAUGhh7H/ADYCMCABIAFByABqIgAgABAjNgIoIAEgAUFAayABQShq",
    "IgIQIzYCCCABIAFBCGogAUE4ahAkNgIQIAEgAUEQaiACECM2AhggASABQRhqIAFBMGoQJDYCICAB",
    "QSBqIAAQIyEAIAFB0ABqJAAgAAsrAQF/IAAoAgQhAgNAIAEgAkcEQCAAEAcaIAJBAWshAgwBCwsg",
    "ACABNgIECwkAIAFBADoAAAsMACABIAIoAgA2AgALBAAQAQsrACACBEADQCAAIAEtAAA6AAAgAEEB",
    "aiEAIAFBAWohASACQQFrIgINAAsLC5YDAQJ/IwBBEGsiBCQAIAQgAjYCDCAEIAM2AgggBCABNgIE",
    "IAQgADYCACMAQRBrIgIkACACIAQ2AgxBACEBIwBB0AFrIgAkACAAIAQ2AswBIABBoAFqIgNBAEEo",
    "EFkgACAAKALMATYCyAECQEEAIABByAFqIABB0ABqIAMQXUEASA0AQcTUACgCAEEATiEEQfjTACgC",
    "ACEDQcDUACgCAEEATARAQfjTACADQV9xNgIACwJ/AkACQEGo1AAoAgBFBEBBqNQAQdAANgIAQZTU",
    "AEEANgIAQYjUAEIANwMAQaTUACgCACEBQaTUACAANgIADAELQYjUACgCAA0BC0F/QfjTABBaDQEa",
    "C0H40wAgAEHIAWogAEHQAGogAEGgAWoQXQshBSABBH9B+NMAQQBBAEGc1AAoAgARBgAaQajUAEEA",
    "NgIAQaTUACABNgIAQZTUAEEANgIAQYzUACgCABpBiNQAQgA3AwBBAAUgBQsaQfjTAEH40wAoAgAg",
    "A0EgcXI2AgAgBEUNAAsgAEHQAWokACACQRBqJAAACwYAQajVAAsKACAAKAI8GkIACyEAIAIEQANA",
    "IAAgAToAACAAQQFqIQAgAkEBayICDQALCwtZAQF/IAAgACgCSCIBQQFrIAFyNgJIIAAoAgAiAUEI",
    "cQRAIAAgAUEgcjYCAEF/DwsgAEIANwIEIAAgACgCLCIBNgIcIAAgATYCFCAAIAEgACgCMGo2AhBB",
    "AAsKACAAQTBrQQpJC34CAX8BfiAAvSIDQjSIp0H/D3EiAkH/D0cEfCACRQRAIAEgAEQAAAAAAAAA",
    "AGEEf0EABSAARAAAAAAAAPBDoiABEFwhACABKAIAQUBqCzYCACAADwsgASACQf4HazYCACADQv//",
    "//////+HgH+DQoCAgICAgIDwP4S/BSAACwuTFAITfwF+QdYKIQsjAEHQAGsiBSQAIAVB1go2Akwg",
    "BUE3aiEVIAVBOGohEAJAAkACQAJAA0AgCyEKIARB/////wcgDGtKDQEgBCAMaiEMAkACQAJAIAoi",
    "BC0AACIGBEADQAJAAkAgBkH/AXEiC0UEQCAEIQsMAQsgC0ElRw0BIAQhBgNAIAYtAAFBJUcEQCAG",
    "IQsMAgsgBEEBaiEEIAYtAAIhByAGQQJqIgshBiAHQSVGDQALCyAEIAprIgRB/////wcgDGsiFkoN",
    "ByAABEAgACAKIAQQXgsgBA0GIAUgCzYCTCALQQFqIQRBfyENAkAgCywAARBbRQ0AIAstAAJBJEcN",
    "ACALQQNqIQQgCywAAUEwayENQQEhEQsgBSAENgJMQQAhCAJAIAQsAAAiBkEgayILQR9LBEAgBCEH",
    "DAELIAQhB0EBIAt0IgtBidEEcUUNAANAIAUgBEEBaiIHNgJMIAggC3IhCCAELAABIgZBIGsiC0Eg",
    "Tw0BIAchBEEBIAt0IgtBidEEcQ0ACwsCQCAGQSpGBEACfwJAIAcsAAEQW0UNACAHLQACQSRHDQAg",
    "BywAAUECdCADakHAAWtBCjYCACAHQQNqIQZBASERIAcsAAFBA3QgAmpBgANrKAIADAELIBENBiAH",
    "QQFqIQYgAEUEQCAFIAY2AkxBACERQQAhDgwDCyABIAEoAgAiBEEEajYCAEEAIREgBCgCAAshDiAF",
    "IAY2AkwgDkEATg0BQQAgDmshDiAIQYDAAHIhCAwBCyAFQcwAahBfIg5BAEgNCCAFKAJMIQYLQQAh",
    "BEF/IQkCfyAGLQAAQS5HBEAgBiELQQAMAQsgBi0AAUEqRgRAAn8CQCAGLAACEFtFDQAgBi0AA0Ek",
    "Rw0AIAYsAAJBAnQgA2pBwAFrQQo2AgAgBkEEaiELIAYsAAJBA3QgAmpBgANrKAIADAELIBENBiAG",
    "QQJqIQtBACAARQ0AGiABIAEoAgAiB0EEajYCACAHKAIACyEJIAUgCzYCTCAJQX9zQR92DAELIAUg",
    "BkEBajYCTCAFQcwAahBfIQkgBSgCTCELQQELIRICQANAIAQhDyALIhMsAAAiBEH7AGtBRkkNASAT",
    "QQFqIQsgBCAPQTpsakH/CmotAAAiBEEBa0EISQ0ACyAFIAs2AkxBHCEHAkACQCAEQRtHBEAgBEUN",
    "DCANQQBOBEAgAyANQQJ0aiAENgIAIAUgAiANQQN0aikDADcDQAwCCyAARQ0JIAVBQGsgBCABEGAM",
    "AgsgDUEATg0LC0EAIQQgAEUNCAsgCEH//3txIgYgCCAIQYDAAHEbIQhBACENQYAIIRQgECEHAkAC",
    "QAJAAn8CQAJAAkACQAJ/AkACQAJAAkACQAJAAkAgEywAACIEQV9xIAQgBEEPcUEDRhsgBCAPGyIE",
    "QdgAaw4hBBUVFRUVFRUVDhUPBg4ODhUGFRUVFQIFAxUVCRUBFRUEAAsCQCAEQcEAaw4HDhULFQ4O",
    "DgALIARB0wBGDQkMFAsgBSkDQCEXQYAIDAULQQAhBAJAAkACQAJAAkACQAJAIA9B/wFxDggAAQID",
    "BBsFBhsLIAUoAkAgDDYCAAwaCyAFKAJAIAw2AgAMGQsgBSgCQCAMrDcDAAwYCyAFKAJAIAw7AQAM",
    "FwsgBSgCQCAMOgAADBYLIAUoAkAgDDYCAAwVCyAFKAJAIAysNwMADBQLIAlBCCAJQQhLGyEJIAhB",
    "CHIhCEH4ACEECyAQIQogBEEgcSEGIAUpA0AiF1BFBEADQCAKQQFrIgogF6dBD3FBkA9qLQAAIAZy",
    "OgAAIBdCD1YhDyAXQgSIIRcgDw0ACwsgCEEIcUUgBSkDQFByDQMgBEEEdkGACGohFEECIQ0MAwsg",
    "ECEEIAUpA0AiF1BFBEADQCAEQQFrIgQgF6dBB3FBMHI6AAAgF0IHViEKIBdCA4ghFyAKDQALCyAE",
    "IQogCEEIcUUNAiAJIBAgCmsiBEEBaiAEIAlIGyEJDAILIAUpA0AiF0IAUwRAIAVCACAXfSIXNwNA",
    "QQEhDUGACAwBCyAIQYAQcQRAQQEhDUGBCAwBC0GCCEGACCAIQQFxIg0bCyEUIBcgEBBhIQoLIBJB",
    "ACAJQQBIGw0PIAhB//97cSAIIBIbIQggBSkDQCIXQgBSIAlyRQRAIBAiCiEHQQAhCQwNCyAJIBdQ",
    "IBAgCmtqIgQgBCAJSBshCQwMCwJ/IAlB/////wcgCUH/////B0kbIg8iB0EARyEIAkACQAJAIAUo",
    "AkAiBEHrCSAEGyIKIgRBA3FFIAdFcg0AA0AgBC0AAEUNAiAHQQFrIgdBAEchCCAEQQFqIgRBA3FF",
    "DQEgBw0ACwsgCEUNAQsCQCAELQAARSAHQQRJckUEQANAIAQoAgAiCEF/cyAIQYGChAhrcUGAgYKE",
    "eHENAiAEQQRqIQQgB0EEayIHQQNLDQALCyAHRQ0BCwNAIAQgBC0AAEUNAhogBEEBaiEEIAdBAWsi",
    "Bw0ACwtBAAsiBCAKayAPIAQbIgQgCmohByAJQQBOBEAgBiEIIAQhCQwMCyAGIQggBCEJIActAAAN",
    "DgwLCyAJBEAgBSgCQAwCC0EAIQQgAEEgIA5BACAIEGIMAgsgBUEANgIMIAUgBSkDQD4CCCAFIAVB",
    "CGoiBDYCQEF/IQkgBAshBkEAIQQCQANAIAYoAgAiCkUNASAFQQRqIAoQZSIKQQBIIgcgCiAJIARr",
    "S3JFBEAgBkEEaiEGIAkgBCAKaiIESw0BDAILCyAHDQ4LQT0hByAEQQBIDQwgAEEgIA4gBCAIEGIg",
    "BEUEQEEAIQQMAQtBACEHIAUoAkAhBgNAIAYoAgAiCkUNASAFQQRqIAoQZSIKIAdqIgcgBEsNASAA",
    "IAVBBGogChBeIAZBBGohBiAEIAdLDQALCyAAQSAgDiAEIAhBgMAAcxBiIA4gBCAEIA5IGyEEDAkL",
    "IBJBACAJQQBIGw0JQT0hByAAIAUrA0AgDiAJIAggBEEHEQwAIgRBAE4NCAwKCyAFIAUpA0A8ADdB",
    "ASEJIBUhCiAGIQgMBQsgBSATNgJMDAMLIAQtAAEhBiAEQQFqIQQMAAsACyAADQcgEUUNAkEBIQQD",
    "QCADIARBAnRqKAIAIgAEQCACIARBA3RqIAAgARBgQQEhDCAEQQFqIgRBCkcNAQwJCwtBASEMIARB",
    "Ck8NBwNAIAMgBEECdGooAgANASAEQQFqIgRBCkcNAAsMBwtBHCEHDAQLIAkgByAKayIPIAkgD0ob",
    "IglB/////wcgDWtKDQJBPSEHIA4gCSANaiIGIAYgDkgbIgQgFkoNAyAAQSAgBCAGIAgQYiAAIBQg",
    "DRBeIABBMCAEIAYgCEGAgARzEGIgAEEwIAkgD0EAEGIgACAKIA8QXiAAQSAgBCAGIAhBgMAAcxBi",
    "DAELC0EAIQwMAwtBPSEHC0Go1QAgBzYCAAtBfyEMCyAFQdAAaiQAIAwLvQEBA38gAC0AAEEgcUUE",
    "QAJAIAEhAwJAIAIgACIBKAIQIgAEfyAABSABEFoNASABKAIQCyABKAIUIgVrSwRAIAEgAyACIAEo",
    "AiQRBgAaDAILAkAgASgCUEEASA0AIAIhAANAIAAiBEUNASADIARBAWsiAGotAABBCkcNAAsgASAD",
    "IAQgASgCJBEGACAESQ0BIAMgBGohAyACIARrIQIgASgCFCEFCyAFIAMgAhBVIAEgASgCFCACajYC",
    "FAsLCwtrAQR/IAAoAgAsAAAQW0UEQEEADwsDQCAAKAIAIQNBfyEBIAJBzJmz5gBNBEBBfyADLAAA",
    "QTBrIgQgAkEKbCIBaiAEQf////8HIAFrShshAQsgACADQQFqNgIAIAEhAiADLAABEFsNAAsgAgu8",
    "AgACQAJAAkACQAJAAkACQAJAAkACQAJAIAFBCWsOEgAICQoICQECAwQKCQoKCAkFBgcLIAIgAigC",
    "ACIBQQRqNgIAIAAgASgCADYCAA8LIAIgAigCACIBQQRqNgIAIAAgATIBADcDAA8LIAIgAigCACIB",
    "QQRqNgIAIAAgATMBADcDAA8LIAIgAigCACIBQQRqNgIAIAAgATAAADcDAA8LIAIgAigCACIBQQRq",
    "NgIAIAAgATEAADcDAA8LIAIgAigCAEEHakF4cSIBQQhqNgIAIAAgASsDADkDAA8LIAAgAkEIEQQA",
    "Cw8LIAIgAigCACIBQQRqNgIAIAAgATQCADcDAA8LIAIgAigCACIBQQRqNgIAIAAgATUCADcDAA8L",
    "IAIgAigCAEEHakF4cSIBQQhqNgIAIAAgASkDADcDAAuDAQIDfwF+AkAgAEKAgICAEFQEQCAAIQUM",
    "AQsDQCABQQFrIgEgACAAQgqAIgVCCn59p0EwcjoAACAAQv////+fAVYhAiAFIQAgAg0ACwsgBaci",
    "AgRAA0AgAUEBayIBIAIgAkEKbiIDQQpsa0EwcjoAACACQQlLIQQgAyECIAQNAAsLIAELbAEBfyMA",
    "QYACayIFJAAgBEGAwARxIAIgA0xyRQRAIAUgAUH/AXEgAiADayIDQYACIANBgAJJIgEbEFkgAUUE",
    "QANAIAAgBUGAAhBeIANBgAJrIgNB/wFLDQALCyAAIAUgAxBeCyAFQYACaiQAC54YAxJ/AXwCfiMA",
    "QbAEayILJAAgC0EANgIsAkAgAb0iGUIAUwRAQQEhEEGKCCETIAGaIgG9IRkMAQsgBEGAEHEEQEEB",
    "IRBBjQghEwwBC0GQCEGLCCAEQQFxIhAbIRMgEEUhFQsCQCAZQoCAgICAgID4/wCDQoCAgICAgID4",
    "/wBRBEAgAEEgIAIgEEEDaiIDIARB//97cRBiIAAgEyAQEF4gAEGDCUGuCSAFQSBxIgUbQYcJQbIJ",
    "IAUbIAEgAWIbQQMQXiAAQSAgAiADIARBgMAAcxBiIAMgAiACIANIGyEJDAELIAtBEGohEQJAAn8C",
    "QCABIAtBLGoQXCIBIAGgIgFEAAAAAAAAAABiBEAgCyALKAIsIgZBAWs2AiwgBUEgciIOQeEARw0B",
    "DAMLIAVBIHIiDkHhAEYNAiALKAIsIQpBBiADIANBAEgbDAELIAsgBkEdayIKNgIsIAFEAAAAAAAA",
    "sEGiIQFBBiADIANBAEgbCyEMIAtBMGpBAEGgAiAKQQBIG2oiDSEHA0AgBwJ/IAFEAAAAAAAA8EFj",
    "IAFEAAAAAAAAAABmcQRAIAGrDAELQQALIgM2AgAgB0EEaiEHIAEgA7ihRAAAAABlzc1BoiIBRAAA",
    "AAAAAAAAYg0ACwJAIApBAEwEQCAKIQMgByEGIA0hCAwBCyANIQggCiEDA0AgA0EdIANBHUgbIQMC",
    "QCAHQQRrIgYgCEkNACADrSEaQgAhGQNAIAYgGUL/////D4MgBjUCACAahnwiGSAZQoCU69wDgCIZ",
    "QoCU69wDfn0+AgAgBkEEayIGIAhPDQALIBmnIgZFDQAgCEEEayIIIAY2AgALA0AgCCAHIgZJBEAg",
    "BkEEayIHKAIARQ0BCwsgCyALKAIsIANrIgM2AiwgBiEHIANBAEoNAAsLIANBAEgEQCAMQRlqQQlu",
    "QQFqIQ8gDkHmAEYhEgNAQQAgA2siA0EJIANBCUgbIQkCQCAGIAhNBEAgCCgCACEHDAELQYCU69wD",
    "IAl2IRRBfyAJdEF/cyEWQQAhAyAIIQcDQCAHIAMgBygCACIXIAl2ajYCACAWIBdxIBRsIQMgB0EE",
    "aiIHIAZJDQALIAgoAgAhByADRQ0AIAYgAzYCACAGQQRqIQYLIAsgCygCLCAJaiIDNgIsIA0gCCAH",
    "RUECdGoiCCASGyIHIA9BAnRqIAYgBiAHa0ECdSAPShshBiADQQBIDQALC0EAIQMCQCAGIAhNDQAg",
    "DSAIa0ECdUEJbCEDQQohByAIKAIAIglBCkkNAANAIANBAWohAyAJIAdBCmwiB08NAAsLIAxBACAD",
    "IA5B5gBGG2sgDkHnAEYgDEEAR3FrIgcgBiANa0ECdUEJbEEJa0gEQEEEQaQCIApBAEgbIAtqIAdB",
    "gMgAaiIJQQltIg9BAnRqQdAfayEKQQohByAJIA9BCWxrIglBB0wEQANAIAdBCmwhByAJQQFqIglB",
    "CEcNAAsLAkAgCigCACISIBIgB24iDyAHbGsiCUUgCkEEaiIUIAZGcQ0AAkAgD0EBcUUEQEQAAAAA",
    "AABAQyEBIAdBgJTr3ANHIAggCk9yDQEgCkEEay0AAEEBcUUNAQtEAQAAAAAAQEMhAQtEAAAAAAAA",
    "4D9EAAAAAAAA8D9EAAAAAAAA+D8gBiAURhtEAAAAAAAA+D8gCSAHQQF2IhRGGyAJIBRJGyEYAkAg",
    "FQ0AIBMtAABBLUcNACAYmiEYIAGaIQELIAogEiAJayIJNgIAIAEgGKAgAWENACAKIAcgCWoiAzYC",
    "ACADQYCU69wDTwRAA0AgCkEANgIAIAggCkEEayIKSwRAIAhBBGsiCEEANgIACyAKIAooAgBBAWoi",
    "AzYCACADQf+T69wDSw0ACwsgDSAIa0ECdUEJbCEDQQohByAIKAIAIglBCkkNAANAIANBAWohAyAJ",
    "IAdBCmwiB08NAAsLIApBBGoiByAGIAYgB0sbIQYLA0AgBiIHIAhNIglFBEAgB0EEayIGKAIARQ0B",
    "CwsCQCAOQecARwRAIARBCHEhCgwBCyADQX9zQX8gDEEBIAwbIgYgA0ogA0F7SnEiChsgBmohDEF/",
    "QX4gChsgBWohBSAEQQhxIgoNAEF3IQYCQCAJDQAgB0EEaygCACIORQ0AQQohCUEAIQYgDkEKcA0A",
    "A0AgBiIKQQFqIQYgDiAJQQpsIglwRQ0ACyAKQX9zIQYLIAcgDWtBAnVBCWwhCSAFQV9xQcYARgRA",
    "QQAhCiAMIAYgCWpBCWsiBkEAIAZBAEobIgYgBiAMShshDAwBC0EAIQogDCADIAlqIAZqQQlrIgZB",
    "ACAGQQBKGyIGIAYgDEobIQwLQX8hCSAMQf3///8HQf7///8HIAogDHIiEhtKDQEgDCASQQBHakEB",
    "aiEOAkAgBUFfcSIVQcYARgRAIANB/////wcgDmtKDQMgA0EAIANBAEobIQYMAQsgESADIANBH3Ui",
    "BnMgBmutIBEQYSIGa0EBTARAA0AgBkEBayIGQTA6AAAgESAGa0ECSA0ACwsgBkECayIPIAU6AAAg",
    "BkEBa0EtQSsgA0EASBs6AAAgESAPayIGQf////8HIA5rSg0CCyAGIA5qIgMgEEH/////B3NKDQEg",
    "AEEgIAIgAyAQaiIFIAQQYiAAIBMgEBBeIABBMCACIAUgBEGAgARzEGICQAJAAkAgFUHGAEYEQCAL",
    "QRBqIgZBCHIhAyAGQQlyIQogDSAIIAggDUsbIgkhCANAIAg1AgAgChBhIQYCQCAIIAlHBEAgBiAL",
    "QRBqTQ0BA0AgBkEBayIGQTA6AAAgBiALQRBqSw0ACwwBCyAGIApHDQAgC0EwOgAYIAMhBgsgACAG",
    "IAogBmsQXiAIQQRqIgggDU0NAAsgEgRAIABB6QlBARBeCyAMQQBMIAcgCE1yDQEDQCAINQIAIAoQ",
    "YSIGIAtBEGpLBEADQCAGQQFrIgZBMDoAACAGIAtBEGpLDQALCyAAIAYgDEEJIAxBCUgbEF4gDEEJ",
    "ayEGIAhBBGoiCCAHTw0DIAxBCUohAyAGIQwgAw0ACwwCCwJAIAxBAEgNACAHIAhBBGogByAISxsh",
    "CSALQRBqIgZBCHIhAyAGQQlyIQ0gCCEHA0AgDSAHNQIAIA0QYSIGRgRAIAtBMDoAGCADIQYLAkAg",
    "ByAIRwRAIAYgC0EQak0NAQNAIAZBAWsiBkEwOgAAIAYgC0EQaksNAAsMAQsgACAGQQEQXiAGQQFq",
    "IQYgCiAMckUNACAAQekJQQEQXgsgACAGIAwgDSAGayIGIAYgDEobEF4gDCAGayEMIAdBBGoiByAJ",
    "Tw0BIAxBAE4NAAsLIABBMCAMQRJqQRJBABBiIAAgDyARIA9rEF4MAgsgDCEGCyAAQTAgBkEJakEJ",
    "QQAQYgsgAEEgIAIgBSAEQYDAAHMQYiAFIAIgAiAFSBshCQwBCyATIAVBGnRBH3VBCXFqIQwCQCAD",
    "QQtLDQBBDCADayEGRAAAAAAAADBAIRgDQCAYRAAAAAAAADBAoiEYIAZBAWsiBg0ACyAMLQAAQS1G",
    "BEAgGCABmiAYoaCaIQEMAQsgASAYoCAYoSEBCyARIAsoAiwiBiAGQR91IgZzIAZrrSAREGEiBkYE",
    "QCALQTA6AA8gC0EPaiEGCyAQQQJyIQogBUEgcSEIIAsoAiwhByAGQQJrIg0gBUEPajoAACAGQQFr",
    "QS1BKyAHQQBIGzoAACAEQQhxIQYgC0EQaiEHA0AgByIFAn8gAZlEAAAAAAAA4EFjBEAgAaoMAQtB",
    "gICAgHgLIgdBkA9qLQAAIAhyOgAAIAYgA0EASnJFIAEgB7ehRAAAAAAAADBAoiIBRAAAAAAAAAAA",
    "YXEgBUEBaiIHIAtBEGprQQFHckUEQCAFQS46AAEgBUECaiEHCyABRAAAAAAAAAAAYg0AC0F/IQlB",
    "/f///wcgCiARIA1rIgVqIgZrIANIDQAgAEEgIAIgBgJ/AkAgA0UNACAHIAtBEGprIghBAmsgA04N",
    "ACADQQJqDAELIAcgC0EQamsiCAsiB2oiAyAEEGIgACAMIAoQXiAAQTAgAiADIARBgIAEcxBiIAAg",
    "C0EQaiAIEF4gAEEwIAcgCGtBAEEAEGIgACANIAUQXiAAQSAgAiADIARBgMAAcxBiIAMgAiACIANI",
    "GyEJCyALQbAEaiQAIAkLiQUCBn4BfyABIAEoAgBBB2pBeHEiAUEQajYCACAAAnwgASkDACEEIAEp",
    "AwghBSMAQSBrIgAkAAJAIAVC////////////AIMiA0KAgICAgIDAgDx9IANCgICAgICAwP/DAH1U",
    "BEAgBUIEhiAEQjyIhCEDIARC//////////8PgyIEQoGAgICAgICACFoEQCADQoGAgICAgICAwAB8",
    "IQIMAgsgA0KAgICAgICAgEB9IQIgBEKAgICAgICAgAhSDQEgAiADQgGDfCECDAELIARQIANCgICA",
    "gICAwP//AFQgA0KAgICAgIDA//8AURtFBEAgBUIEhiAEQjyIhEL/////////A4NCgICAgICAgPz/",
    "AIQhAgwBC0KAgICAgICA+P8AIQIgA0L///////+//8MAVg0AQgAhAiADQjCIpyIBQZH3AEkNACAE",
    "IQIgBUL///////8/g0KAgICAgIDAAIQiAyEGAkAgAUGB9wBrIghBwABxBEAgAiAIQUBqrYYhBkIA",
    "IQIMAQsgCEUNACAGIAitIgeGIAJBwAAgCGutiIQhBiACIAeGIQILIAAgAjcDECAAIAY3AxgCQEGB",
    "+AAgAWsiAUHAAHEEQCADIAFBQGqtiCEEQgAhAwwBCyABRQ0AIANBwAAgAWuthiAEIAGtIgKIhCEE",
    "IAMgAoghAwsgACAENwMAIAAgAzcDCCAAKQMIQgSGIAApAwAiBEI8iIQhAiAAKQMQIAApAxiEQgBS",
    "rSAEQv//////////D4OEIgRCgYCAgICAgIAIWgRAIAJCAXwhAgwBCyAEQoCAgICAgICACFINACAC",
    "QgGDIAJ8IQILIABBIGokACACIAVCgICAgICAgICAf4OEvws5AwALmQIAIABFBEBBAA8LAn8CQCAA",
    "BH8gAUH/AE0NAQJAQcTWACgCACgCAEUEQCABQYB/cUGAvwNGDQMMAQsgAUH/D00EQCAAIAFBP3FB",
    "gAFyOgABIAAgAUEGdkHAAXI6AABBAgwECyABQYBAcUGAwANHIAFBgLADT3FFBEAgACABQT9xQYAB",
    "cjoAAiAAIAFBDHZB4AFyOgAAIAAgAUEGdkE/cUGAAXI6AAFBAwwECyABQYCABGtB//8/TQRAIAAg",
    "AUE/cUGAAXI6AAMgACABQRJ2QfABcjoAACAAIAFBBnZBP3FBgAFyOgACIAAgAUEMdkE/cUGAAXI6",
    "AAFBBAwECwtBqNUAQRk2AgBBfwVBAQsMAQsgACABOgAAQQELC28BAn9BiNUAKAIAIgEgAEEDakF8",
    "cSICaiEAAkAgAkEAIAAgAU0bDQAgAD8AQRB0SwRAIAA/AEEQdGtB//8DakEQdkAAQX9GBH9BAAVB",
    "ABAAQQELRQ0BC0GI1QAgADYCACABDwtBqNUAQTA2AgBBfwuXLgEMfyAAQQEgABshCwJAA0BBACED",
    "IwBBEGsiDCQAAkACQAJAAkACQAJAAkACQAJAAkACQCALQfQBTQRAQdzWACgCACIGQRAgC0ELakF4",
    "cSALQQtJGyIHQQN2IgJ2IgFBA3EEQAJAIAFBf3NBAXEgAmoiAkEDdCIAQYTXAGoiASAAQYzXAGoo",
    "AgAiAygCCCIARgRAQdzWACAGQX4gAndxNgIADAELIAAgATYCDCABIAA2AggLIANBCGohASADIAJB",
    "A3QiAEEDcjYCBCAAIANqIgAgACgCBEEBcjYCBAwMCyAHQeTWACgCACIKTQ0BIAEEQAJAQQIgAnQi",
    "AEEAIABrciABIAJ0cSIAQQAgAGtxQQFrIgAgAEEMdkEQcSICdiIBQQV2QQhxIgAgAnIgASAAdiIB",
    "QQJ2QQRxIgByIAEgAHYiAUEBdkECcSIAciABIAB2IgFBAXZBAXEiAHIgASAAdmoiA0EDdCIAQYTX",
    "AGoiASAAQYzXAGooAgAiBCgCCCIARgRAQdzWACAGQX4gA3dxIgY2AgAMAQsgACABNgIMIAEgADYC",
    "CAsgBCAHQQNyNgIEIAQgB2oiAiADQQN0IgAgB2siA0EBcjYCBCAAIARqIAM2AgAgCgRAIApBeHFB",
    "hNcAaiEFQfDWACgCACEBAn8gBkEBIApBA3Z0IgBxRQRAQdzWACAAIAZyNgIAIAUMAQsgBSgCCAsh",
    "ACAFIAE2AgggACABNgIMIAEgBTYCDCABIAA2AggLIARBCGohAUHw1gAgAjYCAEHk1gAgAzYCAAwM",
    "C0Hg1gAoAgAiCUUNASAJQQAgCWtxQQFrIgAgAEEMdkEQcSICdiIBQQV2QQhxIgAgAnIgASAAdiIB",
    "QQJ2QQRxIgByIAEgAHYiAUEBdkECcSIAciABIAB2IgFBAXZBAXEiAHIgASAAdmpBAnRBjNkAaigC",
    "ACICKAIEQXhxIAdrIQUgAiEAA0ACQCAAKAIQIgFFBEAgACgCFCIBRQ0BCyABKAIEQXhxIAdrIgAg",
    "BSAAIAVJIgAbIQUgASACIAAbIQIgASEADAELCyACKAIYIQggAiACKAIMIgNHBEAgAigCCCIAQezW",
    "ACgCAEkaIAAgAzYCDCADIAA2AggMCwsgAkEUaiIAKAIAIgFFBEAgAigCECIBRQ0DIAJBEGohAAsD",
    "QCAAIQQgASIDQRRqIgAoAgAiAQ0AIANBEGohACADKAIQIgENAAsgBEEANgIADAoLQX8hByALQb9/",
    "Sw0AIAtBC2oiAEF4cSEHQeDWACgCACIJRQ0AQQAgB2shBQJAAkACQAJ/QQAgB0GAAkkNABpBHyAH",
    "Qf///wdLDQAaIABBCHYiACAAQYD+P2pBEHZBCHEiAnQiACAAQYDgH2pBEHZBBHEiAXQiACAAQYCA",
    "D2pBEHZBAnEiAHRBD3YgASACciAAcmsiAEEBdCAHIABBFWp2QQFxckEcagsiBkECdEGM2QBqKAIA",
    "IgBFBEBBACEBDAELQQAhASAHQQBBGSAGQQF2ayAGQR9GG3QhAgNAAkAgACgCBEF4cSAHayIEIAVP",
    "DQAgACEDIAQiBQ0AQQAhBSAAIQEMAwsgASAAKAIUIgQgBCAAIAJBHXZBBHFqKAIQIgBGGyABIAQb",
    "IQEgAkEBdCECIAANAAsLIAEgA3JFBEBBACEDQQIgBnQiAEEAIABrciAJcSIARQ0DIABBACAAa3FB",
    "AWsiACAAQQx2QRBxIgJ2IgFBBXZBCHEiACACciABIAB2IgFBAnZBBHEiAHIgASAAdiIBQQF2QQJx",
    "IgByIAEgAHYiAUEBdkEBcSIAciABIAB2akECdEGM2QBqKAIAIQELIAFFDQELA0AgASgCBEF4cSAH",
    "ayIAIAVJIQIgACAFIAIbIQUgASADIAIbIQMgASgCECIABH8gAAUgASgCFAsiAQ0ACwsgA0UNACAF",
    "QeTWACgCACAHa08NACADKAIYIQYgAyADKAIMIgJHBEAgAygCCCIAQezWACgCAEkaIAAgAjYCDCAC",
    "IAA2AggMCQsgA0EUaiIAKAIAIgFFBEAgAygCECIBRQ0DIANBEGohAAsDQCAAIQQgASICQRRqIgAo",
    "AgAiAQ0AIAJBEGohACACKAIQIgENAAsgBEEANgIADAgLIAdB5NYAKAIAIgJNBEBB8NYAKAIAIQMC",
    "QCACIAdrIgFBEE8EQEHk1gAgATYCAEHw1gAgAyAHaiIANgIAIAAgAUEBcjYCBCACIANqIAE2AgAg",
    "AyAHQQNyNgIEDAELQfDWAEEANgIAQeTWAEEANgIAIAMgAkEDcjYCBCACIANqIgAgACgCBEEBcjYC",
    "BAsgA0EIaiEBDAoLIAdB6NYAKAIAIghJBEBB6NYAIAggB2siATYCAEH01gBB9NYAKAIAIgIgB2oi",
    "ADYCACAAIAFBAXI2AgQgAiAHQQNyNgIEIAJBCGohAQwKC0EAIQEgB0EvaiIJAn9BtNoAKAIABEBB",
    "vNoAKAIADAELQcDaAEJ/NwIAQbjaAEKAoICAgIAENwIAQbTaACAMQQxqQXBxQdiq1aoFczYCAEHI",
    "2gBBADYCAEGY2gBBADYCAEGAIAsiAGoiBkEAIABrIgRxIgAgB00NCUGU2gAoAgAiBQRAQYzaACgC",
    "ACIDIABqIgIgA00gAiAFS3INCgtBmNoALQAAQQRxDQQCQAJAQfTWACgCACIDBEBBnNoAIQEDQCAD",
    "IAEoAgAiAk8EQCACIAEoAgRqIANLDQMLIAEoAggiAQ0ACwtBABBmIgJBf0YNBSAAIQZBuNoAKAIA",
    "IgNBAWsiASACcQRAIAAgAmsgASACakEAIANrcWohBgsgBiAHTSAGQf7///8HS3INBUGU2gAoAgAi",
    "BQRAQYzaACgCACIDIAZqIgEgA00gASAFS3INBgsgBhBmIgEgAkcNAQwHCyAGIAhrIARxIgZB/v//",
    "/wdLDQQgBhBmIgIgASgCACABKAIEakYNAyACIQELIAFBf0YgB0EwaiAGTXJFBEBBvNoAKAIAIgIg",
    "CSAGa2pBACACa3EiAkH+////B0sEQCABIQIMBwsgAhBmQX9HBEAgAiAGaiEGIAEhAgwHC0EAIAZr",
    "EGYaDAQLIAEiAkF/Rw0FDAMLQQAhAwwHC0EAIQIMBQsgAkF/Rw0CC0GY2gBBmNoAKAIAQQRyNgIA",
    "CyAAQf7///8HSw0BIAAQZiICQX9GQQAQZiIAQX9GciAAIAJNcg0BIAAgAmsiBiAHQShqTQ0BC0GM",
    "2gBBjNoAKAIAIAZqIgA2AgBBkNoAKAIAIABJBEBBkNoAIAA2AgALAkACQAJAQfTWACgCACIEBEBB",
    "nNoAIQEDQCACIAEoAgAiAyABKAIEIgBqRg0CIAEoAggiAQ0ACwwCC0Hs1gAoAgAiAEEAIAAgAk0b",
    "RQRAQezWACACNgIAC0EAIQFBoNoAIAY2AgBBnNoAIAI2AgBB/NYAQX82AgBBgNcAQbTaACgCADYC",
    "AEGo2gBBADYCAANAIAFBA3QiA0GM1wBqIANBhNcAaiIANgIAIANBkNcAaiAANgIAIAFBAWoiAUEg",
    "Rw0AC0Ho1gAgBkEoayIDQXggAmtBB3FBACACQQhqQQdxGyIAayIBNgIAQfTWACAAIAJqIgA2AgAg",
    "ACABQQFyNgIEIAIgA2pBKDYCBEH41gBBxNoAKAIANgIADAILIAEtAAxBCHEgAyAES3IgAiAETXIN",
    "ACABIAAgBmo2AgRB9NYAIARBeCAEa0EHcUEAIARBCGpBB3EbIgBqIgI2AgBB6NYAQejWACgCACAG",
    "aiIBIABrIgA2AgAgAiAAQQFyNgIEIAEgBGpBKDYCBEH41gBBxNoAKAIANgIADAELQezWACgCACAC",
    "SwRAQezWACACNgIACyACIAZqIQBBnNoAIQECQAJAAkACQAJAAkADQCAAIAEoAgBHBEAgASgCCCIB",
    "DQEMAgsLIAEtAAxBCHFFDQELQZzaACEBA0AgBCABKAIAIgBPBEAgACABKAIEaiIFIARLDQMLIAEo",
    "AgghAQwACwALIAEgAjYCACABIAEoAgQgBmo2AgQgAkF4IAJrQQdxQQAgAkEIakEHcRtqIgkgB0ED",
    "cjYCBCAAQXggAGtBB3FBACAAQQhqQQdxG2oiBiAHIAlqIghrIQEgBCAGRgRAQfTWACAINgIAQejW",
    "AEHo1gAoAgAgAWoiADYCACAIIABBAXI2AgQMAwtB8NYAKAIAIAZGBEBB8NYAIAg2AgBB5NYAQeTW",
    "ACgCACABaiIANgIAIAggAEEBcjYCBCAAIAhqIAA2AgAMAwsgBigCBCIFQQNxQQFGBEAgBUF4cSEE",
    "AkAgBUH/AU0EQCAGKAIIIgMgBUEDdiIAQQN0QYTXAGpGGiADIAYoAgwiAkYEQEHc1gBB3NYAKAIA",
    "QX4gAHdxNgIADAILIAMgAjYCDCACIAM2AggMAQsgBigCGCEHAkAgBiAGKAIMIgJHBEAgBigCCCIA",
    "IAI2AgwgAiAANgIIDAELAkAgBkEUaiIFKAIAIgANACAGQRBqIgUoAgAiAA0AQQAhAgwBCwNAIAUh",
    "AyAAIgJBFGoiBSgCACIADQAgAkEQaiEFIAIoAhAiAA0ACyADQQA2AgALIAdFDQACQCAGKAIcIgNB",
    "AnRBjNkAaiIAKAIAIAZGBEAgACACNgIAIAINAUHg1gBB4NYAKAIAQX4gA3dxNgIADAILIAdBEEEU",
    "IAcoAhAgBkYbaiACNgIAIAJFDQELIAIgBzYCGCAGKAIQIgAEQCACIAA2AhAgACACNgIYCyAGKAIU",
    "IgBFDQAgAiAANgIUIAAgAjYCGAsgBCAGaiIGKAIEIQUgASAEaiEBCyAGIAVBfnE2AgQgCCABQQFy",
    "NgIEIAEgCGogATYCACABQf8BTQRAIAFBeHFBhNcAaiEDAn9B3NYAKAIAIgJBASABQQN2dCIAcUUE",
    "QEHc1gAgACACcjYCACADDAELIAMoAggLIQAgAyAINgIIIAAgCDYCDCAIIAM2AgwgCCAANgIIDAML",
    "QR8hBSABQf///wdNBEAgAUEIdiIAIABBgP4/akEQdkEIcSIDdCIAIABBgOAfakEQdkEEcSICdCIA",
    "IABBgIAPakEQdkECcSIAdEEPdiACIANyIAByayIAQQF0IAEgAEEVanZBAXFyQRxqIQULIAggBTYC",
    "HCAIQgA3AhAgBUECdEGM2QBqIQACQEHg1gAoAgAiA0EBIAV0IgJxRQRAQeDWACACIANyNgIAIAAg",
    "CDYCAAwBCyABQQBBGSAFQQF2ayAFQR9GG3QhBSAAKAIAIQIDQCACIgAoAgRBeHEgAUYNAyAFQR12",
    "IQIgBUEBdCEFIAAgAkEEcWoiAygCECICDQALIAMgCDYCEAsgCCAANgIYIAggCDYCDCAIIAg2AggM",
    "AgtB6NYAIAZBKGsiA0F4IAJrQQdxQQAgAkEIakEHcRsiAGsiATYCAEH01gAgACACaiIANgIAIAAg",
    "AUEBcjYCBCACIANqQSg2AgRB+NYAQcTaACgCADYCACAEIAVBJyAFa0EHcUEAIAVBJ2tBB3EbakEv",
    "ayIAIAAgBEEQakkbIgNBGzYCBCADQaTaACkCADcCECADQZzaACkCADcCCEGk2gAgA0EIajYCAEGg",
    "2gAgBjYCAEGc2gAgAjYCAEGo2gBBADYCACADQRhqIQEDQCABQQc2AgQgAUEIaiEAIAFBBGohASAA",
    "IAVJDQALIAMgBEYNAyADIAMoAgRBfnE2AgQgBCADIARrIgVBAXI2AgQgAyAFNgIAIAVB/wFNBEAg",
    "BUF4cUGE1wBqIQICf0Hc1gAoAgAiAUEBIAVBA3Z0IgBxRQRAQdzWACAAIAFyNgIAIAIMAQsgAigC",
    "CAshACACIAQ2AgggACAENgIMIAQgAjYCDCAEIAA2AggMBAtBHyEBIAVB////B00EQCAFQQh2IgAg",
    "AEGA/j9qQRB2QQhxIgJ0IgAgAEGA4B9qQRB2QQRxIgF0IgAgAEGAgA9qQRB2QQJxIgB0QQ92IAEg",
    "AnIgAHJrIgBBAXQgBSAAQRVqdkEBcXJBHGohAQsgBCABNgIcIARCADcCECABQQJ0QYzZAGohAAJA",
    "QeDWACgCACIDQQEgAXQiAnFFBEBB4NYAIAIgA3I2AgAgACAENgIADAELIAVBAEEZIAFBAXZrIAFB",
    "H0YbdCEBIAAoAgAhAwNAIAMiACgCBEF4cSAFRg0EIAFBHXYhAiABQQF0IQEgACACQQRxaiICKAIQ",
    "IgMNAAsgAiAENgIQCyAEIAA2AhggBCAENgIMIAQgBDYCCAwDCyAAKAIIIgEgCDYCDCAAIAg2Aggg",
    "CEEANgIYIAggADYCDCAIIAE2AggLIAlBCGohAQwFCyAAKAIIIgEgBDYCDCAAIAQ2AgggBEEANgIY",
    "IAQgADYCDCAEIAE2AggLQejWACgCACIAIAdNDQBB6NYAIAAgB2siATYCAEH01gBB9NYAKAIAIgIg",
    "B2oiADYCACAAIAFBAXI2AgQgAiAHQQNyNgIEIAJBCGohAQwDC0Go1QBBMDYCAEEAIQEMAgsCQCAG",
    "RQ0AAkAgAygCHCIBQQJ0QYzZAGoiACgCACADRgRAIAAgAjYCACACDQFB4NYAIAlBfiABd3EiCTYC",
    "AAwCCyAGQRBBFCAGKAIQIANGG2ogAjYCACACRQ0BCyACIAY2AhggAygCECIABEAgAiAANgIQIAAg",
    "AjYCGAsgAygCFCIARQ0AIAIgADYCFCAAIAI2AhgLAkAgBUEPTQRAIAMgBSAHaiIAQQNyNgIEIAAg",
    "A2oiACAAKAIEQQFyNgIEDAELIAMgB0EDcjYCBCADIAdqIgQgBUEBcjYCBCAEIAVqIAU2AgAgBUH/",
    "AU0EQCAFQXhxQYTXAGohAgJ/QdzWACgCACIBQQEgBUEDdnQiAHFFBEBB3NYAIAAgAXI2AgAgAgwB",
    "CyACKAIICyEAIAIgBDYCCCAAIAQ2AgwgBCACNgIMIAQgADYCCAwBC0EfIQEgBUH///8HTQRAIAVB",
    "CHYiACAAQYD+P2pBEHZBCHEiAnQiACAAQYDgH2pBEHZBBHEiAXQiACAAQYCAD2pBEHZBAnEiAHRB",
    "D3YgASACciAAcmsiAEEBdCAFIABBFWp2QQFxckEcaiEBCyAEIAE2AhwgBEIANwIQIAFBAnRBjNkA",
    "aiEAAkACQCAJQQEgAXQiAnFFBEBB4NYAIAIgCXI2AgAgACAENgIADAELIAVBAEEZIAFBAXZrIAFB",
    "H0YbdCEBIAAoAgAhBwNAIAciACgCBEF4cSAFRg0CIAFBHXYhAiABQQF0IQEgACACQQRxaiICKAIQ",
    "IgcNAAsgAiAENgIQCyAEIAA2AhggBCAENgIMIAQgBDYCCAwBCyAAKAIIIgEgBDYCDCAAIAQ2Aggg",
    "BEEANgIYIAQgADYCDCAEIAE2AggLIANBCGohAQwBCwJAIAhFDQACQCACKAIcIgFBAnRBjNkAaiIA",
    "KAIAIAJGBEAgACADNgIAIAMNAUHg1gAgCUF+IAF3cTYCAAwCCyAIQRBBFCAIKAIQIAJGG2ogAzYC",
    "ACADRQ0BCyADIAg2AhggAigCECIABEAgAyAANgIQIAAgAzYCGAsgAigCFCIARQ0AIAMgADYCFCAA",
    "IAM2AhgLAkAgBUEPTQRAIAIgBSAHaiIAQQNyNgIEIAAgAmoiACAAKAIEQQFyNgIEDAELIAIgB0ED",
    "cjYCBCACIAdqIgEgBUEBcjYCBCABIAVqIAU2AgAgCgRAIApBeHFBhNcAaiEEQfDWACgCACEDAn9B",
    "ASAKQQN2dCIAIAZxRQRAQdzWACAAIAZyNgIAIAQMAQsgBCgCCAshACAEIAM2AgggACADNgIMIAMg",
    "BDYCDCADIAA2AggLQfDWACABNgIAQeTWACAFNgIACyACQQhqIQELIAxBEGokACABIgANAUHM2gAo",
    "AgAiAARAIAARCgAMAQsLAAsgAAvMDAEHfwJAIABFDQAgAEEIayICIABBBGsoAgAiAEF4cSIEaiEF",
    "AkAgAEEBcQ0AIABBA3FFDQEgAiACKAIAIgBrIgJB7NYAKAIASQ0BIAAgBGohBEHw1gAoAgAgAkcE",
    "QCAAQf8BTQRAIAIoAggiASAAQQN2IgNBA3RBhNcAakYaIAEgAigCDCIARgRAQdzWAEHc1gAoAgBB",
    "fiADd3E2AgAMAwsgASAANgIMIAAgATYCCAwCCyACKAIYIQYCQCACIAIoAgwiAEcEQCACKAIIIgEg",
    "ADYCDCAAIAE2AggMAQsCQCACQRRqIgEoAgAiAw0AIAJBEGoiASgCACIDDQBBACEADAELA0AgASEH",
    "IAMiAEEUaiIBKAIAIgMNACAAQRBqIQEgACgCECIDDQALIAdBADYCAAsgBkUNAQJAIAIoAhwiAUEC",
    "dEGM2QBqIgMoAgAgAkYEQCADIAA2AgAgAA0BQeDWAEHg1gAoAgBBfiABd3E2AgAMAwsgBkEQQRQg",
    "BigCECACRhtqIAA2AgAgAEUNAgsgACAGNgIYIAIoAhAiAQRAIAAgATYCECABIAA2AhgLIAIoAhQi",
    "AUUNASAAIAE2AhQgASAANgIYDAELIAUoAgQiAEEDcUEDRw0AQeTWACAENgIAIAUgAEF+cTYCBCAC",
    "IARBAXI2AgQgAiAEaiAENgIADAELIAIgBU8NACAFKAIEIgBBAXFFDQACQCAAQQJxRQRAQfTWACgC",
    "ACAFRgRAQfTWACACNgIAQejWAEHo1gAoAgAgBGoiADYCACACIABBAXI2AgQgAkHw1gAoAgBHDQNB",
    "5NYAQQA2AgBB8NYAQQA2AgAMAwtB8NYAKAIAIAVGBEBB8NYAIAI2AgBB5NYAQeTWACgCACAEaiIA",
    "NgIAIAIgAEEBcjYCBCAAIAJqIAA2AgAMAwsgAEF4cSAEaiEEAkAgAEH/AU0EQCAFKAIIIgEgAEED",
    "diIDQQN0QYTXAGpGGiABIAUoAgwiAEYEQEHc1gBB3NYAKAIAQX4gA3dxNgIADAILIAEgADYCDCAA",
    "IAE2AggMAQsgBSgCGCEGAkAgBSAFKAIMIgBHBEAgBSgCCCIBQezWACgCAEkaIAEgADYCDCAAIAE2",
    "AggMAQsCQCAFQRRqIgEoAgAiAw0AIAVBEGoiASgCACIDDQBBACEADAELA0AgASEHIAMiAEEUaiIB",
    "KAIAIgMNACAAQRBqIQEgACgCECIDDQALIAdBADYCAAsgBkUNAAJAIAUoAhwiAUECdEGM2QBqIgMo",
    "AgAgBUYEQCADIAA2AgAgAA0BQeDWAEHg1gAoAgBBfiABd3E2AgAMAgsgBkEQQRQgBigCECAFRhtq",
    "IAA2AgAgAEUNAQsgACAGNgIYIAUoAhAiAQRAIAAgATYCECABIAA2AhgLIAUoAhQiAUUNACAAIAE2",
    "AhQgASAANgIYCyACIARBAXI2AgQgAiAEaiAENgIAIAJB8NYAKAIARw0BQeTWACAENgIADAILIAUg",
    "AEF+cTYCBCACIARBAXI2AgQgAiAEaiAENgIACyAEQf8BTQRAIARBeHFBhNcAaiEAAn9B3NYAKAIA",
    "IgFBASAEQQN2dCIDcUUEQEHc1gAgASADcjYCACAADAELIAAoAggLIQEgACACNgIIIAEgAjYCDCAC",
    "IAA2AgwgAiABNgIIDAELQR8hASAEQf///wdNBEAgBEEIdiIAIABBgP4/akEQdkEIcSIAdCIBIAFB",
    "gOAfakEQdkEEcSIBdCIDIANBgIAPakEQdkECcSIDdEEPdiAAIAFyIANyayIAQQF0IAQgAEEVanZB",
    "AXFyQRxqIQELIAIgATYCHCACQgA3AhAgAUECdEGM2QBqIQACQAJAAkBB4NYAKAIAIgNBASABdCIH",
    "cUUEQEHg1gAgAyAHcjYCACAAIAI2AgAgAiAANgIYDAELIARBAEEZIAFBAXZrIAFBH0YbdCEBIAAo",
    "AgAhAANAIAAiAygCBEF4cSAERg0CIAFBHXYhACABQQF0IQEgAyAAQQRxaiIHKAIQIgANAAsgByAC",
    "NgIQIAIgAzYCGAsgAiACNgIMIAIgAjYCCAwBCyADKAIIIgAgAjYCDCADIAI2AgggAkEANgIYIAIg",
    "AzYCDCACIAA2AggLQfzWAEH81gAoAgBBAWsiAEF/IAAbNgIACwsGACAAEGgLcQEBfyACRQRAIAAo",
    "AgQgASgCBEYPCyAAIAFGBEBBAQ8LAkAgACgCBCICLQAAIgBFIAAgASgCBCIBLQAAIgNHcg0AA0Ag",
    "AS0AASEDIAItAAEiAEUNASABQQFqIQEgAkEBaiECIAAgA0YNAAsLIAAgA0YLzQMBBH8jAEFAaiIE",
    "JAACf0EBIAAgAUEAEGoNABpBACABRQ0AGiMAQUBqIgMkACABKAIAIgVBBGsoAgAhBiAFQQhrKAIA",
    "IQUgA0IANwMgIANCADcDKCADQgA3AzAgA0IANwA3IANCADcDGCADQQA2AhQgA0HEDzYCECADIAE2",
    "AgwgA0H0DzYCCCABIAVqIQFBACEFAkAgBkH0D0EAEGoEQCADQQE2AjggBiADQQhqIAEgAUEBQQAg",
    "BigCACgCFBEJACABQQAgAygCIEEBRhshBQwBCyAGIANBCGogAUEBQQAgBigCACgCGBEIAAJAAkAg",
    "AygCLA4CAAECCyADKAIcQQAgAygCKEEBRhtBACADKAIkQQFGG0EAIAMoAjBBAUYbIQUMAQsgAygC",
    "IEEBRwRAIAMoAjANASADKAIkQQFHDQEgAygCKEEBRw0BCyADKAIYIQULIANBQGskAEEAIAUiAUUN",
    "ABogBEEIaiIDQQRyQQBBNBBZIARBATYCOCAEQX82AhQgBCAANgIQIAQgATYCCCABIAMgAigCAEEB",
    "IAEoAgAoAhwRBwAgBCgCICIAQQFGBEAgAiAEKAIYNgIACyAAQQFGCyEAIARBQGskACAAC10BAX8g",
    "ACgCECIDRQRAIABBATYCJCAAIAI2AhggACABNgIQDwsCQCABIANGBEAgACgCGEECRw0BIAAgAjYC",
    "GA8LIABBAToANiAAQQI2AhggACAAKAIkQQFqNgIkCwsYACAAIAEoAghBABBqBEAgASACIAMQbAsL",
    "MQAgACABKAIIQQAQagRAIAEgAiADEGwPCyAAKAIIIgAgASACIAMgACgCACgCHBEHAAuaAQAgAEEB",
    "OgA1AkAgACgCBCACRw0AIABBAToANAJAIAAoAhAiAkUEQCAAQQE2AiQgACADNgIYIAAgATYCECAD",
    "QQFHDQIgACgCMEEBRg0BDAILIAEgAkYEQCAAKAIYIgJBAkYEQCAAIAM2AhggAyECCyAAKAIwQQFH",
    "DQIgAkEBRg0BDAILIAAgACgCJEEBajYCJAsgAEEBOgA2CwsgAAJAIAAoAgQgAUcNACAAKAIcQQFG",
    "DQAgACACNgIcCwvyAQAgACABKAIIIAQQagRAIAEgAiADEHAPCwJAIAAgASgCACAEEGoEQAJAIAIg",
    "ASgCEEcEQCABKAIUIAJHDQELIANBAUcNAiABQQE2AiAPCyABIAM2AiACQCABKAIsQQRGDQAgAUEA",
    "OwE0IAAoAggiACABIAIgAkEBIAQgACgCACgCFBEJACABLQA1BEAgAUEDNgIsIAEtADRFDQEMAwsg",
    "AUEENgIsCyABIAI2AhQgASABKAIoQQFqNgIoIAEoAiRBAUcNASABKAIYQQJHDQEgAUEBOgA2Dwsg",
    "ACgCCCIAIAEgAiADIAQgACgCACgCGBEIAAsLkQEAIAAgASgCCCAEEGoEQCABIAIgAxBwDwsCQCAA",
    "IAEoAgAgBBBqRQ0AAkAgAiABKAIQRwRAIAEoAhQgAkcNAQsgA0EBRw0BIAFBATYCIA8LIAEgAjYC",
    "FCABIAM2AiAgASABKAIoQQFqNgIoAkAgASgCJEEBRw0AIAEoAhhBAkcNACABQQE6ADYLIAFBBDYC",
    "LAsLNwAgACABKAIIIAUQagRAIAEgAiADIAQQbw8LIAAoAggiACABIAIgAyAEIAUgACgCACgCFBEJ",
    "AAsaACAAIAEoAgggBRBqBEAgASACIAMgBBBvCwsFAEH0CAsFAEGfCQsEACMACwYAIAAkAAsQACMA",
    "IABrQXBxIgAkACAACyQBAn8jAEEQayIBJAAgAUEIaiAAEBwoAgAhAiABQRBqJAAgAgsLsEojAEGA",
    "CAv4Ai0rICAgMFgweAAtMFgrMFggMFgtMHgrMHggMHgAYXRhbl9kaXYAc3FydABmaW5kX2hpZ2hl",
    "c3RfYml0AHZlY3RvcgAuLi9zcmMvbGliL2ZwbS9tYXRoLmhwcAAuLi9zcmMvbGliL2ZwbS9maXhl",
    "ZC5ocHAAc3RkOjpleGNlcHRpb24AbmFuAGluZgBmbW9kAGF0YW5fc2FuaXRpemVkAHN0ZDo6YmFk",
    "X2FsbG9jAE5BTgBJTkYAb3BlcmF0b3IvPQBhdGFuMgB5Lm1fdmFsdWUgIT0gMAB5LnJhd192YWx1",
    "ZSgpICE9IDAALgAobnVsbCkAeCA+PSBGaXhlZCgwKSAmJiB4IDw9IEZpeGVkKDEpAHggPiBGaXhl",
    "ZCgwKQB5ID49IEZpeGVkKDApAHggPj0gRml4ZWQoMCkAeSAhPSBGaXhlZCgwKQB4ICE9IEZpeGVk",
    "KDApAEFzc2VydGlvbiBmYWlsZWQ6ICVzICglczogJXM6ICVkKQoAQYELC4ABCQAAEAsAACANAAAw",
    "DwAAQBEAAFATAABgFQAAcBcAAIAZAACQGwAAoB0AALAfAADAIQAA0CMAAOAlAADwJwAAGQAKABkZ",
    "GQAAAAAFAAAAAAAACQAAAAALAAAAAAAAAAAZABEKGRkZAwoHAAEACQsYAAAJBgsAAAsABhkAAAAZ",
    "GRkAQZEMCyEOAAAAAAAAAAAZAAoNGRkZAA0AAAIACQ4AAAAJAA4AAA4AQcsMCwEMAEHXDAsVEwAA",
    "AAATAAAAAAkMAAAAAAAMAAAMAEGFDQsBEABBkQ0LFQ8AAAAEDwAAAAAJEAAAAAAAEAAAEABBvw0L",
    "ARIAQcsNCx4RAAAAABEAAAAACRIAAAAAABIAABIAABoAAAAaGhoAQYIOCw4aAAAAGhoaAAAAAAAA",
    "CQBBsw4LARQAQb8OCxUXAAAAABcAAAAACRQAAAAAABQAABQAQe0OCwEWAEH5Dgv9AhUAAAAAFQAA",
    "AAAJFgAAAAAAFgAAFgAAMDEyMzQ1Njc4OUFCQ0RFRk4xMF9fY3h4YWJpdjExNl9fc2hpbV90eXBl",
    "X2luZm9FAAAAADAIAACgBwAA8AgAAE4xMF9fY3h4YWJpdjExN19fY2xhc3NfdHlwZV9pbmZvRQAA",
    "ADAIAADQBwAAxAcAAAAAAAD0BwAACgAAAAsAAAAMAAAADQAAAA4AAAAPAAAAEAAAABEAAAAAAAAA",
    "eAgAAAoAAAASAAAADAAAAA0AAAAOAAAAEwAAABQAAAAVAAAATjEwX19jeHhhYml2MTIwX19zaV9j",
    "bGFzc190eXBlX2luZm9FAAAAADAIAABQCAAA9AcAAAAAAADUCAAACQAAABYAAAAXAAAAAAAAALwI",
    "AAAJAAAAGAAAABkAAABTdDlleGNlcHRpb24AAAAACAgAAKwIAABTdDliYWRfYWxsb2MAAAAAMAgA",
    "AMQIAAC8CAAAU3Q5dHlwZV9pbmZvAAAAAAgIAADgCABBghILggQBAAIAAwAEAAUABgAHAAgACQAK",
    "AAsADAANAA4ADwAQABEAEgATABQAFQAWABcAGAAZABoAGwAcAB0AHgAfACAAIQAiACMAJAAlACYA",
    "JwAoACkAKgArACwALQAuAC8AMAAxADIAMwA0ADUANgA3ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBD",
    "AEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBYAFkAWgBbAFwAXQBeAF8A",
    "YABhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG4AbwBwAHEAcgBzAHQAdQB2AHcAeAB5AHoAewB8",
    "AH0AfgB/ALgAR3+Af4F/g3+Ef4V/hn+Hf4h/iX+Kf4t/jH+Nf45/j3+Qf5F/kn+Tf5R/lX+Wf5d/",
    "mH+Zf5p/m3+cf51/nn+ff6B/oX+if6N/pH+lf6Z/p3+of6l/qn+rf6x/rX+uf69/sH+xf7J/s3+0",
    "f7V/tn+3f7h/uX+6f7t/vH+9f75/v3/Af8F/wn/Df8R/xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/",
    "0X/Sf9N/1H/Vf9Z/13/Yf9l/2n/bf9x/3X/ef99/4H/hf+J/43/kf+V/5n/nf+h/6X/qf+t/7H/t",
    "f+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1//n//fwCAAEGSFguCBAEAAgADAAQABQAG",
    "AAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIA",
    "IwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/",
    "AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsA",
    "XABdAF4AXwBgAGEAYgBjAGQAZQBmAGcAaABpAGoAawBsAG0AbgBvAHAAcQByAHMAdAB1AHYAdwB4",
    "AHkAegB7AHwAfQB+AH8AqQFWfoB/gX+Cf4N/hX+Gf4d/iH+Jf4p/i3+Mf41/jn+Pf5B/kX+Sf5N/",
    "lH+Vf5Z/l3+Yf5l/mn+bf5x/nX+ef59/oH+hf6J/o3+kf6V/pn+nf6h/qX+qf6t/rH+tf65/r3+w",
    "f7F/sn+zf7R/tX+2f7d/uH+5f7p/u3+8f71/vn+/f8B/wX/Cf8N/xH/Ff8Z/x3/If8l/yn/Lf8x/",
    "zX/Of89/0H/Rf9J/03/Uf9V/1n/Xf9h/2X/af9t/3H/df95/33/gf+F/4n/jf+R/5X/mf+d/6H/p",
    "f+p/63/sf+1/7n/vf/B/8X/yf/N/9H/1f/Z/93/4f/l/+n/7f/x//X/+f/9/AIAAQaIaC4IEAQAC",
    "AAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAXABgAGQAaABsAHAAdAB4A",
    "HwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAvADAAMQAyADMANAA1ADYANwA4ADkAOgA7",
    "ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQAFEAUgBTAFQAVQBWAFcA",
    "WABZAFoAWwBcAF0AXgBfAGAAYQBiAGMAZABlAGYAZwBoAGkAagBrAGwAbQBuAG8AcABxAHIAcwB0",
    "AHUAdgB3AHgAeQB6AHsAfAB9AH4AggBABL97fX+Bf4J/g3+Ef4Z/h3+If4l/in+Lf4x/jX+Of49/",
    "kH+Rf5J/k3+Uf5V/ln+Xf5h/mX+af5t/nH+df55/n3+gf6F/on+jf6R/pX+mf6d/qH+pf6p/q3+s",
    "f61/rn+vf7B/sX+yf7N/tH+1f7Z/t3+4f7l/un+7f7x/vX++f79/wH/Bf8J/w3/Ef8V/xn/Hf8h/",
    "yX/Kf8t/zH/Nf85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Zf9p/23/cf91/3n/ff+B/4X/if+N/5H/l",
    "f+Z/53/of+l/6n/rf+x/7X/uf+9/8H/xf/J/83/0f/V/9n/3f/h/+X/6f/t//H/9f/5//38AgABB",
    "sh4LggQBAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAQABEAEgATABQAFQAWABcAGAAZABoA",
    "GwAcAB0AHgAfACAAIQAiACMAJAAlACYAJwAoACkAKgArACwALQAuAC8AMAAxADIAMwA0ADUANgA3",
    "ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBDAEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMA",
    "VABVAFYAVwBYAFkAWgBbAFwAXQBeAF8AYABhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG4AbwBw",
    "AHEAcgBzAHQAdQB2AHcAeAB5AHoAewB8AH0AfgCnABcJ6HZYf4F/gn+Df4R/hX+Gf4d/iX+Kf4t/",
    "jH+Nf45/j3+Qf5F/kn+Tf5R/lX+Wf5d/mH+Zf5p/m3+cf51/nn+ff6B/oX+if6N/pH+lf6Z/p3+o",
    "f6l/qn+rf6x/rX+uf69/sH+xf7J/s3+0f7V/tn+3f7h/uX+6f7t/vH+9f75/v3/Af8F/wn/Df8R/",
    "xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/0X/Sf9N/1H/Vf9Z/13/Yf9l/2n/bf9x/3X/ef99/4H/h",
    "f+J/43/kf+V/5n/nf+h/6X/qf+t/7H/tf+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1/",
    "/n//fwCAAEHCIguCBAEAAgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYA",
    "FwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAz",
    "ADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8A",
    "UABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAYgBjAGQAZQBmAGcAaABpAGoAawBs",
    "AG0AbgBvAHAAcQByAHMAdAB1AHYAdwB4AHkAegB7AHwAfQCLAGgB7w8QcJd+dH+Cf4N/hH+Ff4Z/",
    "h3+If4l/in+Lf41/jn+Pf5B/kX+Sf5N/lH+Vf5Z/l3+Yf5l/mn+bf5x/nX+ef59/oH+hf6J/o3+k",
    "f6V/pn+nf6h/qX+qf6t/rH+tf65/r3+wf7F/sn+zf7R/tX+2f7d/uH+5f7p/u3+8f71/vn+/f8B/",
    "wX/Cf8N/xH/Ff8Z/x3/If8l/yn/Lf8x/zX/Of89/0H/Rf9J/03/Uf9V/1n/Xf9h/2X/af9t/3H/d",
    "f95/33/gf+F/4n/jf+R/5X/mf+d/6H/pf+p/63/sf+1/7n/vf/B/8X/yf/N/9H/1f/Z/93/4f/l/",
    "+n/7f/x//X/+f/9/AIAAQdImC4IEAQACAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIA",
    "EwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAv",
    "ADAAMQAyADMANAA1ADYANwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsA",
    "TABNAE4ATwBQAFEAUgBTAFQAVQBWAFcAWABZAFoAWwBcAF0AXgBfAGAAYQBiAGMAZABlAGYAZwBo",
    "AGkAagBrAGwAbQBuAG8AcABxAHIAcwB0AHUAdgB3AHgAeQB6AHsAfgCLAOsAqAPcFyNoV3wUf3R/",
    "gX+Ef4V/hn+Hf4h/iX+Kf4t/jH+Nf45/j3+Qf5J/k3+Uf5V/ln+Xf5h/mX+af5t/nH+df55/n3+g",
    "f6F/on+jf6R/pX+mf6d/qH+pf6p/q3+sf61/rn+vf7B/sX+yf7N/tH+1f7Z/t3+4f7l/un+7f7x/",
    "vX++f79/wH/Bf8J/w3/Ef8V/xn/Hf8h/yX/Kf8t/zH/Nf85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Z",
    "f9p/23/cf91/3n/ff+B/4X/if+N/5H/lf+Z/53/of+l/6n/rf+x/7X/uf+9/8H/xf/J/83/0f/V/",
    "9n/3f/h/+X/6f/t//H/9f/5//38AgABB4ioLggQBAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4A",
    "DwAQABEAEgATABQAFQAWABcAGAAZABoAGwAcAB0AHgAfACAAIQAiACMAJAAlACYAJwAoACkAKgAr",
    "ACwALQAuAC8AMAAxADIAMwA0ADUANgA3ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBDAEQARQBGAEcA",
    "SABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBYAFkAWgBbAFwAXQBeAF8AYABhAGIAYwBk",
    "AGUAZgBnAGgAaQBqAGsAbABtAG4AbwBwAHEAcgBzAHQAdQB2AHcAeAB5AHsAgQCYAPAAVwIbCM8f",
    "MGDkd6h9D39nf35/hH+Gf4d/iH+Jf4p/i3+Mf41/jn+Pf5B/kX+Sf5N/lH+Vf5Z/l3+Yf5p/m3+c",
    "f51/nn+ff6B/oX+if6N/pH+lf6Z/p3+of6l/qn+rf6x/rX+uf69/sH+xf7J/s3+0f7V/tn+3f7h/",
    "uX+6f7t/vH+9f75/v3/Af8F/wn/Df8R/xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/0X/Sf9N/1H/V",
    "f9Z/13/Yf9l/2n/bf9x/3X/ef99/4H/hf+J/43/kf+V/5n/nf+h/6X/qf+t/7H/tf+5/73/wf/F/",
    "8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1//n//fwCAAEHyLguCBAEAAgADAAQABQAGAAcACAAJAAoA",
    "CwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAn",
    "ACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMA",
    "RABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBg",
    "AGEAYgBjAGQAZQBmAGcAaABpAGoAawBsAG0AbgBvAHAAcQByAHMAdAB1AHYAeAB7AIEAkgC9ADAB",
    "ZwK0BaoOAyf8WFVxS3qYfc9+Qn9tf35/hH+Hf4l/in+Lf4x/jX+Of49/kH+Rf5J/k3+Uf5V/ln+X",
    "f5h/mX+af5t/nH+df55/n3+gf6F/on+jf6V/pn+nf6h/qX+qf6t/rH+tf65/r3+wf7F/sn+zf7R/",
    "tX+2f7d/uH+5f7p/u3+8f71/vn+/f8B/wX/Cf8N/xH/Ff8Z/x3/If8l/yn/Lf8x/zX/Of89/0H/R",
    "f9J/03/Uf9V/1n/Xf9h/2X/af9t/3H/df95/33/gf+F/4n/jf+R/5X/mf+d/6H/pf+p/63/sf+1/",
    "7n/vf/B/8X/yf/N/9H/1f/Z/93/4f/l/+n/7f/x//X/+f/9/AIAAQYIzC4IEAQACAAMABAAFAAYA",
    "BwAIAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAj",
    "ACQAJQAmACcAKAApACoAKwAsAC0ALgAvADAAMQAyADMANAA1ADYANwA4ADkAOgA7ADwAPQA+AD8A",
    "QABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQAFEAUgBTAFQAVQBWAFcAWABZAFoAWwBc",
    "AF0AXgBfAGAAYQBiAGMAZABlAGYAZwBoAGkAagBrAGwAbQBuAG8AcABxAHIAdAB2AHkAfwCKAJ8A",
    "yQAeAccBHgPVBVULexYWLelShGmqdCp64Xw4fuF+Nn9gf3V/gH+Gf4l/i3+Nf45/j3+Qf5F/kn+T",
    "f5R/lX+Wf5d/mH+Zf5p/m3+cf51/nn+ff6B/oX+if6N/pH+lf6Z/p3+of6l/qn+rf6x/rX+uf69/",
    "sH+xf7J/tH+1f7Z/t3+4f7l/un+7f7x/vX++f79/wH/Bf8J/w3/Ef8V/xn/Hf8h/yX/Kf8t/zH/N",
    "f85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Zf9p/23/cf91/3n/ff+B/4X/if+N/5H/lf+Z/53/of+l/",
    "6n/rf+x/7X/uf+9/8H/xf/J/83/0f/V/9n/3f/h/+X/6f/t//H/9f/5//38AgABBkjcLggQBAAIA",
    "AwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAQABEAEgATABQAFQAWABcAGAAZABoAGwAcAB0AHgAf",
    "ACAAIQAiACMAJAAlACYAJwAoACkAKgArACwALQAuAC8AMAAxADIAMwA0ADUANgA3ADgAOQA6ADsA",
    "PAA9AD4APwBAAEEAQgBDAEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBY",
    "AFkAWgBbAFwAXQBeAF8AYABhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG8AcQB0AHgAfQCGAJMA",
    "qADLAAMBXwH3AfACigQtB4ULrxJ9HvMxDE6CYVBtenTSeHV7D30IfqB+/H40f1d/bH95f4J/h3+L",
    "f45/kH+Sf5N/lH+Vf5Z/l3+Yf5l/mn+bf5x/nX+ef59/oH+hf6J/o3+kf6V/pn+nf6h/qX+qf6t/",
    "rH+tf65/r3+wf7F/sn+zf7R/tX+2f7d/uH+5f7p/u3+8f71/vn+/f8B/wX/Cf8N/xH/Ff8Z/x3/J",
    "f8p/y3/Mf81/zn/Pf9B/0X/Sf9N/1H/Vf9Z/13/Yf9l/2n/bf9x/3X/ef99/4H/hf+J/43/kf+V/",
    "5n/nf+h/6X/qf+t/7H/tf+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1//n//fwCAAEGi",
    "OwuCBAEAAgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAb",
    "ABwAHQAeAB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcA",
    "OAA5ADoAOwA8AD0APgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBU",
    "AFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAYgBjAGQAZQBnAGgAagBtAG8AcwB3AH0AhQCQAJ8A",
    "tADSAPwANwGLAQICrAKdA/ME2gaQCWsN6RK6GtsltTVKSiRaRWUWbZRyb3YleQx7YnxTff19dH7I",
    "fgN/LX9Lf2B/b396f4J/iH+Mf5B/kn+Vf5d/mH+af5t/nH+df55/n3+gf6F/on+jf6R/pX+mf6d/",
    "qH+pf6p/q3+sf61/rn+vf7B/sX+yf7N/tH+1f7Z/t3+4f7l/un+7f7x/vX++f79/wH/Bf8J/w3/E",
    "f8V/xn/Hf8h/yX/Kf8t/zH/Nf85/z3/Qf9F/0n/Tf9R/1X/Wf9d/2H/Zf9p/23/cf91/3n/ff+B/",
    "4X/if+N/5H/lf+Z/6H/pf+p/63/sf+1/7n/vf/B/8X/yf/N/9H/1f/Z/93/4f/l/+n/7f/x//X/+",
    "f/9/AIAAQbI/C4IEAQACAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAX",
    "ABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAvADAAMQAyADMA",
    "NAA1ADYANwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQ",
    "AFEAUgBTAFQAVQBWAFcAWABZAFsAXABdAF8AYABiAGQAZwBpAG0AcQB1AHsAggCLAJYApAC2AMwA",
    "6QANATsBdgHCASMCnwI+AwoEDwVeBg0INQr6DIkQGRX1GnoiIyyJOHZH3FOFXQpl5mp2bwVzynXy",
    "d6F58Hr1e8F8YH3cfT1+iX7EfvJ+Fn8zf0l/W39pf3R/fX+Ef4p/jn+Sf5Z/mH+bf51/n3+gf6J/",
    "o3+kf6Z/p3+of6l/qn+rf6x/rX+uf69/sH+xf7J/s3+0f7V/tn+3f7h/uX+6f7t/vH+9f75/v3/A",
    "f8F/wn/Df8R/xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/0X/Sf9N/1H/Vf9Z/13/Yf9l/2n/bf9x/",
    "3X/ef99/4H/hf+J/43/kf+V/5n/nf+h/6X/qf+t/7H/tf+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5",
    "f/p/+3/8f/1//n8AgABBwsMAC4IEAQACAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIA",
    "EwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAv",
    "ADAAMQAyADMANAA1ADYANwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBLAEwA",
    "TQBOAFAAUQBTAFQAVgBYAFoAXABeAGEAZABoAGsAcAB1AHsAggCKAJMAnwCsALsAzQDiAPwAGgE9",
    "AWgBmgHWAR0CcgLXAlAD3wOKBFYFSQZrB8UIYgpODJkOVhGZFH8YJR2wIk4pNDGgOl9Fy06xVk9d",
    "2mKAZ2ZrqW5mcbFznXU6d5R4tnmpenV7IHyvfCh9jX3ifSl+ZX6XfsJ+5X4Dfx1/Mn9Ef1N/YH9s",
    "f3V/fX+Ef4p/j3+Uf5d/m3+ef6F/o3+lf6d/qX+rf6x/rn+vf7F/sn+zf7R/tn+3f7h/uX+6f7t/",
    "vH+9f75/v3/Af8F/wn/Df8R/xX/Gf8d/yH/Jf8p/y3/Mf81/zn/Pf9B/0X/Sf9N/1H/Vf9Z/13/Y",
    "f9l/2n/bf9x/3X/ef99/4H/hf+J/43/kf+V/5n/nf+h/6X/qf+t/7H/tf+5/73/wf/F/8n/zf/R/",
    "9X/2f/d/+H/5f/p/+3/8f/1//n8AgABB0scAC4IEAQACAAMABAAFAAYABwAIAAkACgALAAwADQAO",
    "AA8AEAARABIAEwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoA",
    "KwAsAC0ALgAvADAAMQAyADQANQA2ADcAOAA5ADsAPAA9AD8AQABBAEMARQBGAEgASgBMAE4AUABT",
    "AFUAWABbAF8AYgBnAGsAcAB1AHsAggCKAJIAmwCmALEAvgDNAN4A8AAFAR0BNwFVAXcBnQHJAfkB",
    "MQJvArYCBQNgA8YDOgS9BFEF+QW3Bo4HggiWCc8KMQzDDYoPjRHUE2kWVhmnHGggqiR8KfIuIzUm",
    "PNlD3EoNUYNWVVuXX1hjqWaWaStscm51cDxyznMwdWl2fXdxeEh5BnquekJ7xXs5fJ98+nxJfZB9",
    "zn0GfjZ+Yn6Ifqp+yH7ifvp+D38hfzJ/QX9Of1l/ZH9tf3V/fX+Ef4p/j3+Uf5h/nX+gf6R/p3+q",
    "f6x/r3+xf7N/tX+3f7l/un+8f75/v3/Af8J/w3/Ef8Z/x3/If8l/yn/Lf81/zn/Pf9B/0X/Sf9N/",
    "1H/Vf9Z/13/Yf9l/2n/bf9x/3X/ef99/4H/hf+J/43/kf+V/5n/nf+h/6X/qf+t/7H/tf+5/73/w",
    "f/F/8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1//n8AgABB4ssAC4IEAQACAAMABAAFAAYABwAIAAkA",
    "CgALAAwADQAOAA8AEAARABIAFAAVABYAFwAYABkAGgAbAB0AHgAfACAAIQAjACQAJQAnACgAKQAr",
    "ACwALgAwADEAMwA1ADcAOQA7AD0APwBBAEQARgBJAEwATwBSAFYAWQBdAGIAZgBrAHAAdgB8AIIA",
    "iQCRAJkAogCrALYAwQDNANoA6AD4AAkBGwEvAUUBXAF2AZIBsAHRAfUBHQJIAnYCqQLhAh4DYAOo",
    "A/cDTQSrBBEFgQX7BYAGEQewB10IGgnpCcsKwQvODPQNNQ+TEBIStBN8FW8XkBniG2weMiE5JIgn",
    "JCsXL2YzHDhAPb9C40eZTOhQ21R3WMZbzV6TYR1kb2aQaINqS2ztbWxvynALcjFzPnQ0dRZ25Xai",
    "d0947nh/eQR6fnruelR7snsIfFd8n3zhfB59Vn2Jfbd94n0Kfi5+T35tfol+o366ftB+5H72fgd/",
    "F38lfzJ/Pn9Jf1R/XX9mf25/dn99f4N/iX+Pf5R/mX+df6J/pn+pf61/sH+zf7Z/uX+7f75/wH/C",
    "f8R/xn/If8p/zH/Of89/0X/Tf9R/1n/Xf9h/2n/bf9x/3n/ff+B/4X/if+R/5X/mf+d/6H/pf+p/",
    "63/tf+5/73/wf/F/8n/zf/R/9X/2f/d/+H/5f/p/+3/8f/1//n8AgABB8s8AC4cEBgAHAAkACgAM",
    "AA0ADwAQABIAEwAVABcAGAAaABwAHgAgACIAJAAmACgAKgAtAC8AMgA0ADcAOgA9AEAAQwBHAEoA",
    "TgBSAFYAWgBeAGMAaABtAHIAeAB+AIUAiwCSAJoAogCqALMAvADGANAA2wDnAPMAAAEOARwBLAE8",
    "AU4BYAF0AYgBnwG2Ac8B6QEFAiMCQwJlAogCrgLXAgIDLwNgA5QDygMFBEMEhQTLBBUFZQW5BRMG",
    "cgbYBkQHtwcyCLQIPgnSCW4KFQvHC4QMTQ0jDgcP+Q/7EA0SMhNpFLMVFBeKGBkawhuGHWcfZyGI",
    "I8wlNSjGKoEtajCCM842TzoLPvRBsEUxSX1MlU9+UjlVylczWndcmF6YYHliPWTmZXVn62hMapZr",
    "zWzybQRvBnD4cNxxsnJ7czh06nSRdS12wXZLd813SHi7eCd5jXnseUZ6mnrqejR7enu8e/p7NXxr",
    "fJ980Hz9fCh9UX13fZp9vH3cffp9Fn4wfkl+YH53fot+n36xfsN+037jfvF+/34Mfxh/JH8vfzl/",
    "Q39Mf1V/XX9lf21/dH96f4F/h3+Nf5J/l3+cf6F/pX+pf61/sX+1f7h/vH+/f8J/xX/If8t/zX/Q",
    "f9J/1X/Xf9l/23/df99/4X/jf+V/53/of+p/7H/tf+9/8H/yf/N/9X/2f/h/+X8AgAAAAAAFAEGE",
    "1AALAQQAQZzUAAsKBQAAAAYAAAC0KgBBtNQACwECAEHE1AALCP//////////AEGI1QALAlDt",
].join("");

    function decode(inst) {
        inst.exports._initialize();
        return function (in_buf) {
            var input_offset =  inst.exports.allocate_input(in_buf.byteLength);
            var input_mem = new Uint8Array(inst.exports.memory.buffer, input_offset, in_buf.byteLength);
            input_mem.set(new Uint8Array(in_buf));

            inst.exports.decode();

            var output = [
                "GYROFLOW IMU LOG",
                "version,1.1",
                "id,esplog",
                "orientation,YxZ",
                "tscale,0.00180",
                "gscale,0.00053263221",
                "ascale,0.0001",
                "t,gx,gy,gz,ax,ay,az"
            ];
            var output_mem = new Int32Array(inst.exports.memory.buffer, inst.exports.get_output_ptr(), inst.exports.get_output_size());
            for (let i = 0; i < output_mem.length; i += 7) {
                output.push(output_mem.slice(i, i + 7).join(","));
            }
            var output_text = output.join("\n");
            return Promise.resolve(output_text);
        };
    }

    function downloadText(text, name) {
        var link = document.createElement("a");
        link.download = name;
        link.href = URL.createObjectURL(new Blob([text], {type: 'text/plain'}));
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        delete link;
    }

    function download_and_decode_log(log_url, log_name) {
        let mem = new WebAssembly.Memory({initial:1, maximum: 16000});
        fetch('data:application/octet-stream;base64,' + wasm)
            .then(response => response.arrayBuffer())
            .then(bytes => WebAssembly.instantiate(bytes, {env: {memory: mem, emscripten_notify_memory_growth:()=>{}}}))
            .then(({ instance }) => {
                return decode(instance);
            })
            .then(decoder => {
                fetch(log_url)
                    .then(response => response.arrayBuffer())
                    .then(decoder)
                    .then(text => downloadText(text, log_name));
            });
    }
</script>)--";

}  // namespace