name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v4.4.1
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          idf.py set-target esp32c3
          idf.py build
